### ISSUE TITLE
app/styles/app.[scss/sass] does not exist

### ISSUE THREAD

**Issue by altrim** [miguelcobain/ember-paper#1]
After installing the addon when trying to run `ember serve` I get the following error `app/styles/app.[scss/sass] does not exist`.

**Comment by jamesdixon** [comment]
@miguelcobain this bug appears to be back. I'm running the latest version of Ember CLI (1.13.8) and receiving the same error mentioned above. Would you like to re-open this issue or would you prefer I keep open a separate issue?

**Comment by jamesdixon** [comment]
@miguelcobain I take it back. Must be an issue with my project. It works fine in a fresh project.

**Comment by jerel** [comment]
I'm also seeing this bug using ember-paper 0.2.7 and Ember CLI 1.13.8. The only thing out of the ordinary is that I'm using pods

**Comment by jamesdixon** [comment]
@jerel I wasn't able to resolve this, but for me, I tracked the issue down to being a conflict of some sorts between `ember-cli-less` and `ember-cli-sass`. After removing `ember-cli-less`, things started to function. May be worth a try.

**Comment by jerel** [comment]
@jamesdixon thanks for the tip! broccoli-sass was already added to my project and ember-paper added ember-cli-sass (which I didn't notice). Removing ember-cli-sass fixed the issue

**Comment by jamesdixon** [comment]
@jerel glad you were able to resolve it!
