### ISSUE TITLE
Versioning of ember-paper

### ISSUE THREAD

**Issue by benedikt-d** [miguelcobain/ember-paper#100]
Ember Data and Ember Liquid Fire are going to switch to a new versioning system. Should this library follow?

http://emberjs.com/blog/2015/06/16/ember-project-at-2-0.html

**Comment by SirZach** [comment]
:+1:

**Comment by miguelcobain** [comment]
Doesn't seem like a common practice with 3rd party libraries, and ember-paper isn't **that much** tied to each ember version.

Closing for now.
