### ISSUE TITLE
Wondering how I would integrate Text-Support for a {{paper-text}} component.

### ISSUE THREAD

**Issue by benedikt-d** [miguelcobain/ember-paper#102]
Wondering how I would integrate Text-Support for a {{paper-text}} component.
For example {{input escape-press='fooAction'}}.

http://emberjs.com/api/classes/Ember.TextSupport.html
This is something that probably has to be done in the component?

**Comment by miguelcobain** [comment]
That would be a cool feature.

We're using `Ember.TextField` in our `paper-text` component (through the `{{input}}` helper) [here](https://github.com/miguelcobain/ember-paper/blob/master/app%2Ftemplates%2Fcomponents%2Fpaper-text.hbs#L2).

I think its just a matter of passing in to the helper all the available events that `Ember.TextSupport` supports.

We're already using `focusIn` and `focusOut` actions, but we could easily use them as "proxies" to the user action. PR is welcome!

**Comment by benedikt-d** [comment]
https://github.com/miguelcobain/ember-paper/pull/103

**Comment by miguelcobain** [comment]
We no longer have "paper-text". The new paper-input supports a myriad of events. Should be fixed.
