### ISSUE TITLE
Add documentation for whitelist/blacklist of components

### ISSUE THREAD

**Issue by panthony** [miguelcobain/ember-paper#1049]
I've stumble upon the fact that we can now whitelist or blacklist components at build time but I couldn't find how to do it anywhere.

Not in the docs website nor the README.

I had to dig up the changeset implementing the feature.

**Comment by betocantu93** [comment]
@panthony yes, it was part of the effort of removing jQuery to try to shrink build size. It's documented, but I think we need a new guides release.

https://github.com/miguelcobain/ember-paper/blob/12d6c7ada622b46da7befbd174373d9df2bfc465/tests/dummy/app/templates/index.hbs#L56

**Comment by panthony** [comment]
@betocantu93 Ok, so it is just missing an update of the currently deployed website because it is not here:

http://miguelcobain.github.io/ember-paper/#/

That's why I missed it

**Comment by betocantu93** [comment]
Yup, hope we can get a release soon to the website

**Comment by panthony** [comment]
Closing this issue now because I might not see the released website and forget about it
