### ISSUE TITLE
IE11: Object doesn't support property or method 'forEach'

### ISSUE THREAD

**Issue by panthony** [miguelcobain/ember-paper#1058]
I have this issue on IE 11 in `paper-dialog-inner` because of the following line:

```
    let imageElements = this.element.querySelectorAll('img');
    // ...
    imageElements.forEach((image) => {
      image.addEventListener('load', this._checkContentOverflowOnLoad);
    });
```

As IE11 does not support `.forEach` on `querySelectorAll` result ([see here](https://developer.mozilla.org/en-US/docs/Web/API/NodeList/forEach#Browser_Compatibility)).

The fix could be either to transform `imageElements` as an array `[...document.querySelectorAll()]` or add a small polyfill to add `forEach` on `NodeList` as suggested on developer.mozilla.org

**Comment by panthony** [comment]
@m3l1x I added the suggered polyfill to fix the issue:

```js
// missing forEach on NodeList for IE11
if (window.NodeList && !NodeList.prototype.forEach) {
  NodeList.prototype.forEach = Array.prototype.forEach;
}
```

**Comment by miguelcobain** [comment]
@panthony @m3l1x I created [ember-cli-polyfill-importer](https://github.com/miguelcobain/ember-cli-polyfill-importer) and used it to import our polyfills, including nodelist foreach that this issue is about.

Could you please test your apps with master to confirm that the polyfill is being added?

Please make sure that IE or FF 50 (or any other version that doesn't have nodelist forEach) are included in your `config/targets.js` file.

**Comment by panthony** [comment]
@miguelcobain (Un)fortunately I'm not equipped to test something on IE11.

What about this issue? Shall I close it?

I'm afraid others might be surprised by this issue too because it means that OOTB ember-paper is not compatible with IE11, unless you add this polyfill addon.

**Comment by m3l1x** [comment]
@miguelcobain @panthony I gonna test it on monday and report.

**Comment by miguelcobain** [comment]
It is working for me on IE11!

Please reopen if issue persists.

**Comment by kumaresan-subramani** [comment]
> @m3l1x I added the suggered polyfill to fix the issue:
> 
> ```js
> // missing forEach on NodeList for IE11
> if (window.NodeList && !NodeList.prototype.forEach) {
>   NodeList.prototype.forEach = Array.prototype.forEach;
> }
> ```

@m3l1x , can you share polyfills link?
