### ISSUE TITLE
sidenav no longer automatically closes

### ISSUE THREAD

**Issue by larryh** [miguelcobain/ember-paper#1060]
I just upgraded from beta.20 to beta.22. My paper-sidenav always used to close automatically whenever I selected an item, now it does not; it stays open (in both Chrome and FireFox).

I notice that beta.21 contained a change to _fix paper-menu not closing when backdrop is clicked_. Maybe that is what caused the problem?
https://github.com/miguelcobain/ember-paper/commit/01229aec64dce6a9d2859e39a0d0402a974408ba

Here is how I fire up the sidenav (which hasn't changed in months):
`
{{#paper-sidenav
    name="main"
    open=mainOpen
    closeOnClick=true
    lockedOpen=false
    position="left"
    onToggle=(action (mut mainOpen))}}
`

**Comment by larryh** [comment]
Okay, I looked into this a litter further, mostly because I didn't see how something like this could be missed by the ember-paper contributors. (Please take that as a compliment, as that is how it was meant. :-)

The fact that a change related to _menus not closing_ was made in a release sandwiched between my versions turned out _**not**_ to be the problem. (Man, talk about a red herring.)

The problem stems from a related addon (ember-cli-document-title) not being compatible with Ember 3.7
[https://github.com/kimroen/ember-cli-document-title/issues/83]

And it was that addon's "issues" with the new version of Ember that was causing the paper-sidnav hiccups.

Hope no one wasted any time on this. And thanks for the amazing ember-paper addon!

**Comment by miguelcobain** [comment]
Glad to hear you got it working.
