### ISSUE TITLE
paper-tabs: arrows to scroll on overflowing tabs are always disabled

### ISSUE THREAD

**Issue by bjornharrtell** [miguelcobain/ember-paper#1063]
Bisected to https://github.com/miguelcobain/ember-paper/commit/23073e806cb50391cae55b8cf36853cfeed292b0

**Comment by saivarunr** [comment]
Same issue unable to scroll left or right.

**Comment by pauln** [comment]
Changing tab seems to trigger something which enables the arrow buttons, as they start to work once you've changed to a different tab.

**Comment by pauln** [comment]
Correction/update: Simply being on any tab that's not the first is sufficient to activate the buttons.  If `selected` is set to a tab other than the first, even as its initial state, the arrow buttons seem to work fine.

**Comment by pauln** [comment]
It turned out to be a bit more complex than that, though the fix seems to be pretty simple.  See PR #1068 for more detail.

**Comment by panthony** [comment]
@bjornharrtell Do you still reproduce this issue with the latest release?

**Comment by bjornharrtell** [comment]
@panthony looks like it works great now, at least what I can see in limited testing. Much appreciated, thanks!

**Comment by miguelcobain** [comment]
Thanks!
