### ISSUE TITLE
paper-select click outside not closing dropdown menu

### ISSUE THREAD

**Issue by edgarravenhorst** [miguelcobain/ember-paper#1067]
Clicking outside the select box doesn't close the dropdown menu. 

**Environment** 
- Device: Mac
- Browser: Chrome
- Ember-CLI: Latest

**Steps to reproduce:** 
1. Run ember init
2. Run ember install ember-paper
3. Add select from example to the application hbs
4. Optional: define options for select. This isn't required because it will show results not found in the menu. 
5. Click on the option box. 
6. Click somewhere else on the page.

Am i missing something here?

**Comment by schekin** [comment]
and if your used select in modal dialog, then select dont close when ESC key closed modal.

**Comment by jmsalmeida** [comment]
I'm having the same problem, someone found an alternative to solve?

When the selector is showing, while the user does not select any option the application stay impossibility to do any action

**Comment by jmsalmeida** [comment]
Or just update ember-paper to [1.0.0-beta.24](https://github.com/miguelcobain/ember-paper/tree/v1.0.0-beta.24) :grin:
