### ISSUE TITLE
Build fails with a clean install on a brand new app

### ISSUE THREAD

**Issue by mansona** [miguelcobain/ember-paper#1069]
Morning folks 👋 

I've just done a clean install on a brand new app with the following steps: 

```bash
npm init ember-app new-app
cd new-app
ember install ember-paper
npm start
```

And I get the following error: 

```
ENOENT: no such file or directory, lstat '/Users/mansona/git/projects/new-app/node_modules/angular-material-source/src/core/services/layout/layout.scss'
```

Having a look at the folder `node_modules/angular-material-source/src` it looks like it is missing the `core` folder altogether 🤔 Maybe this is as a result of version drift of that dependency?

**Comment by miguelcobain** [comment]
Hi @mansona 👋 

I just did

```
ember new paper-test
cd paper-test
ember install ember-paper
ember s
```

and all went smoothly here.

Not sure what happened during your angular-material-source installation, but it definitely should have the needed files in there!

**Comment by mansona** [comment]
I don't know what to tell you 😂 I just ran the exact same steps and it failed again! 

Here are my versions: 

```
➜  temp ember -v
ember-cli: 3.7.1
node: 10.12.0
os: darwin x64
➜  temp npm -v
6.8.0
```

and here is the output of those exact commands with no gaps between: 

```
➜  temp ember new paper-test
installing app
  create .editorconfig
  create .ember-cli
  create .eslintignore
  create .eslintrc.js
  create .template-lintrc.js
  create .travis.yml
  create .watchmanconfig
  create README.md
  create app/app.js
  create app/components/.gitkeep
  create app/controllers/.gitkeep
  create app/helpers/.gitkeep
  create app/index.html
  create app/models/.gitkeep
  create app/resolver.js
  create app/router.js
  create app/routes/.gitkeep
  create app/styles/app.css
  create app/templates/application.hbs
  create app/templates/components/.gitkeep
  create config/environment.js
  create config/optional-features.json
  create config/targets.js
  create ember-cli-build.js
  create .gitignore
  create package.json
  create public/robots.txt
  create testem.js
  create tests/helpers/.gitkeep
  create tests/index.html
  create tests/integration/.gitkeep
  create tests/test-helper.js
  create tests/unit/.gitkeep
  create vendor/.gitkeep
npm: Installed dependencies
Successfully initialized git.
➜  temp cd paper-test
➜  paper-test git:(master) ember install ember-paper
npm: Installed ember-paper
installing ember-paper
  create app/styles/app.scss
  install addon ember-cli-sass
npm: Installed ember-cli-sass
installing ember-cli-sass
  install package sass
npm: Installed sass
Installed addon package.
Installed addon package.
➜  paper-test git:(master) ✗ ember s
Build Error (Funnel)

ENOENT: no such file or directory, lstat '/Users/mansona/temp/paper-test/node_modules/angular-material-source/src/core/services/layout/layout.scss'


Stack Trace and Error Report: /var/folders/r5/bw5frvnn5k794hk62w3vp7km0000gn/T/error.dump.53d0f85e1cc8372088e09e85a28459ac.log
```

maybe you can share your versions and I can see if it's something specific to my environment 🤔

**Comment by panthony** [comment]
@miguelcobain Weird, I have an automatic deployment that started failing with the exact same error.

And I'm using my fork of ember-paper  from beta.20

**Comment by panthony** [comment]
@mansona @miguelcobain Probably a cache related issue of some sort.

Doing `npm install --cache /tmp/empty-cache` fixed it for me.

**Comment by mansona** [comment]
hmm 🤔 that's interesting @panthony I tried to clear my cache and try again but it didn't work. I also tried your method of `npm install --cache /tmp/empty-cache` and it also didn't work.

I tried it really quick with yarn and it seems to be working 😫 I wonder if we're in a bit of a grey area because we're really heavily depending on a git dependency and not using what's actually packaged in the registry?

**Comment by panthony** [comment]
I actually did `npm ci --cache /tmp/empty-cache`, in case it works better with `ci` but I would not see why.

I also looked for an `.npmignore` but could not find any..

**Comment by mansona** [comment]
@panthony yea I was thinking that it was something to do with a `.npmignore` file or maybe a `files: []` definition in the package.json but I couldn't find anything that might be causing this 🤔

**Comment by panthony** [comment]
@mansona Got the same error on a different machine and directly did `
npm ci --cache /tmp/empty-cache` but this time it didn't work.

It must have been the combinaison of different attempts at fixing it.

Weird.

**Comment by panthony** [comment]
Fun fact, if I execute `npm prune`, a single package gets removed, `angular-material-source`, ...

**Comment by panthony** [comment]
@miguelcobain Just so you know, on the machines where I have the issue, this:

``` 
ember new paper-test
cd paper-test
ember install ember-paper
ember s
```

does not work.

Whereas until a few days ago everything was working.

I did not change my package.json nor node or npm ...

Can't figure out what is happening.

**Comment by miguelcobain** [comment]
A git dependency is definitely not the best.

Seems like angular material folks won't publish the source files to npm: https://github.com/angular/material/issues/10762

Can someone do that? Or is there a better option? git submodules? Copy pasting? :/

**Comment by mansona** [comment]
@miguelcobain if they won't publish it then I don't see what is wrong with us publishing it 🤔 

it will essentially be a "soft fork" that literally only changes the name 😂 I'm alright with doing the work if I can help 😄

**Comment by panthony** [comment]
@miguelcobain FYI this morning I had no issue when I deployed...

This is a true cosmic ray issue.

I'm sure someone somewhere broke something impacting random people around the world and silently fixed it without saying anything.

Wouldn't be the first time actually.

**Comment by abobwhite** [comment]
I started having this problem 2 days ago and I have done every trick in the book to get this to work with removing node_modules/tmp several times, trying to reinstall the ember-paper addon, etc. I didn't change my dependencies at all. The error only shows up with `ember serve`, `ember build` has no error

**Comment by mansona** [comment]
@panthony I think the fact that we are working with GitHub dependencies means that we are **always** going to be susceptible to "changing implementations" in every aspect of this 🙈 

The only real way to fix this is to **actually deploy** the material-source to npm because we pack things into a tar file and that tar is what is on npm 👍 

Like I said I'm happy to help with that @miguelcobain if it's something you're ok with us doing

**Comment by abobwhite** [comment]
Does anyone have a workaround? I can't do any work right now :/

**Comment by miguelcobain** [comment]
Can you guys try 1.0.0-beta.24?
This should be fixed.

Ember-paper now depends on `angular-material-styles` npm package. This package only contains scss styles.

**Comment by abobwhite** [comment]
Hey @miguelcobain thanks for tackling that change so quickly! I just tried 1.0.0-beta24 it and it seems to work well :)

**Comment by mansona** [comment]
Thanks a million @miguelcobain 🎉 I've gone through my steps to reproduce and the issue is gone! 😍
