### ISSUE TITLE
Slack channel on ember community

### ISSUE THREAD

**Issue by QuantumInformation** [miguelcobain/ember-paper#107]
Hi, can we get a Slack channel on ember community for this project?

![image](https://cloud.githubusercontent.com/assets/216566/8316162/148e3422-19ed-11e5-9a54-f9d051f31945.png)

**Comment by benedikt-d** [comment]
How about a #tag in the main ember slack chat?

**Comment by QuantumInformation** [comment]
thats what I meant :)

**Comment by benedikt-d** [comment]
I don't have rights for that but probably we could just ask someone who does.

**Comment by QuantumInformation** [comment]
I asked the owner:)

**Comment by miguelcobain** [comment]
Please let me know if I can help.

**Comment by QuantumInformation** [comment]
Its in the mixer!

**Comment by brandonjmckay** [comment]
Nice.

**Comment by brandonjmckay** [comment]
It exists now! `#ember-paper` in the Ember Slack group!
