### ISSUE TITLE
paper-autocomplete selected item not highlighted any more

### ISSUE THREAD

**Issue by pauln** [miguelcobain/ember-paper#1073]
As a result of updating to the angular-material styles to v1.1.13 (as part of the move to `angular-material-styles`, the selected item in `paper-autocomplete` suggestion lists is no longer visibly highlighted.  The [angular-material commit which caused this](https://github.com/angular/material/commit/320511c97ffc1a0a268d97d8aef434cb8fb6980d#diff-37ca33a4bdb605ef905c5a4709405724) appears to be trying to fix a bug where the wrong suggestion was sometimes highlighted, but means that the styles are now out of sync with the HTML we're generating:

```diff
-    &.selected {
+    &#selected_option {
```

**Comment by miguelcobain** [comment]
Fixed on https://github.com/miguelcobain/ember-paper/commit/864a7f8ea7f0270f0f635dc8998da70833cc6dfa
