### ISSUE TITLE
Action on paper-button does not bubble

### ISSUE THREAD

**Issue by charlesfries** [miguelcobain/ember-paper#1079]
Even with the `bubbles=true` attribute, actions on paper-button are not passed upwards from the local controller.

`{{#paper-button bubbles=true raised=true primary=true onClick=(action "testAction")}}Test{{/paper-button}}`

Having `testAction() { return true; }` in the controller and `testAction() { console.log("Called"); }` in the route will not call the action in the route.

**Comment by charlesfries** [comment]
'templates/application'

```
{{#paper-button bubbles=true raised=true primary=true onClick=(action "myAction")}}My Action{{/paper-button}}
{{outlet}}
```

'controllers/application'

```
import Controller from '@ember/controller';
export default Controller.extend({
	actions: {
		myAction() {
			return true;
		}
	}
});
```

'routes/application'

```
import Route from '@ember/routing/route';
export default Route.extend({
	actions: {
		myAction() {
			console.log('Success!');
		}
	}
});
```

**Comment by conormag** [comment]
closure actions don't bubble
