### ISSUE TITLE
Update angular-material-styles to 1.1.18

### ISSUE THREAD

**Issue by Subtletree** [miguelcobain/ember-paper#1082]
We're currently on `angular-material-styles` 1.1.13.

There's only one style change from 1.1.13 -> 1.1.18:
https://github.com/angular/material/pull/11674/files.

@miguelcobain Where is `angular-material-styles` coming from? Just pushing to npm from a local repo?

**Comment by miguelcobain** [comment]
Yes. It's basically a copy of https://github.com/angular/material published to a different npm package.

I can update it.

**Comment by Subtletree** [comment]
Thanks Miguel 😀 . I'm hitting that placeholder issue on ie 11

**Comment by miguelcobain** [comment]
@Subtletree can you try master and see if it fixes it for you? I updated it.

**Comment by Subtletree** [comment]
Thanks, works perfectly. Found that we're not handling the `md-input-has-placeholder` class so added it in #1083
