### ISSUE TITLE
Build Error (broccoli-persistent-filter:Babel > [Babel: Modules for Templates]) in ember-paper/templates/components/paper-chips.js

### ISSUE THREAD

**Issue by fortunee** [miguelcobain/ember-paper#1094]
Hey there, 

I just recently upgraded the current version of my ember project and I'm getting this 👇 

#### ENOMEM: not enough memory, read

Any ideas on how to resolve this, would be greatly appreciated?

**Comment by miguelcobain** [comment]
Shouldn't happen anymore. Please reopen if issue persists.

**Comment by fortunee** [comment]
> Shouldn't happen anymore. Please reopen if issue persists.

Oh! What a trip down memory lane. I've moved on from this project. Bye ember :joy: :v:
