### ISSUE TITLE
Icons offset when using them with md-fab buttons

### ISSUE THREAD

**Issue by mansona** [miguelcobain/ember-paper#110]
I'm trying to create an "add" button for the bottom right of my UI and I tried to use a paper-button with the md-fab class and a paper-icon inside it. Here is the code: 

```
{{#paper-button classNames="md-fab md-primary"}} {{paper-icon icon="add" size=2 c}} {{/paper-button}}
```

This didn't work and as it showed the icon off centre: https://cloudup.com/cpoDYshSTTk . I actually thing this issue is related to https://github.com/miguelcobain/ember-paper/issues/87 because it seems like the top left corner of the icon is in the right place, and adding rotat-plus does this: https://cloudup.com/c_-zKRl4ptT

To get this to a place where it would work for me i put this class on the icon: 
```
.patch-size-2 {
  width: 32px;
  height: 32px;
  vertical-align: inherit;
}
```
I don't really know how to proceed because I'm more of a Javascript guy than a CSS guy. if you want me to do/try anything just let me know

**Comment by benedikt-d** [comment]
I think the fab button as well as the icon button are supposed to be a new separate component which is not ready yet. https://material.angularjs.org/latest/#/demo/material.components.button
Would love to have those too!

**Comment by miguelcobain** [comment]
Yes, fab buttons aren't implemented.

**Comment by mansona** [comment]
Ah right, I was intending to implement a first pass on the fab buttons and saw that in the link you shared @benedikt-d the button type was determined by a class md-fab. I tried that on the button and it "just worked" 

When you say they are "supposed to be a new separate component" i assume you are talking about maybe `{{paper-fab-button}}` with an Icon parameter or something? If someone could spec out the API that they would like to see I might be able to have a crack at it.

**Comment by miguelcobain** [comment]
Fab buttons aren't implemented, so this is still a non issue.
Should be really easy to make them, though. The styles are there!

**Comment by mansona** [comment]
@miguelcobain did you see my comment about the API you want for this? If people want to have a fab button do you want them to use something like `{{paper-fab-button}}`?

**Comment by miguelcobain** [comment]
@mansona I'd rather just use a class on paper-button, just like angular material does. They're buttons after all.
