### ISSUE TITLE
Cannot user paper with fresh install of ember-cli

### ISSUE THREAD

**Issue by skeough** [miguelcobain/ember-paper#1119]
I am receiving the following problem even on a freshly created server:

`[Babel: ember-inflector > applyPatches]'@ember-data/model/-private' is imported by -private\index.js, but could not be resolved – treating it as an external dependency
(node:33908) UnhandledPromiseRejectionWarning: Error: Error: $string: rgba(0, 0, 0, 0.38) is not a string.
   ╷
35 │       color: unquote($color);
   │              ^^^^^^^^^^^^^^^
   ╵
~\Temp\broccoli-33908ODcfd9W6jKDi\out-290-broccoli_merge_trees_full_application\app\styles\angular-material\core\style\mixins.scss 35:14             input-placeholder-color()
  ~\Temp\broccoli-33908ODcfd9W6jKDi\out-290-broccoli_merge_trees_full_application\app\styles\angular-material\components\chips\chips-theme.scss 19:11  @import
 ~\Temp\broccoli-33908ODcfd9W6jKDi\out-290-broccoli_merge_trees_full_application\app\styles\ember-paper-components.scss 23:9                          @import
 ~\Temp\broccoli-33908ODcfd9W6jKDi\out-290-broccoli_merge_trees_full_application\app\styles\ember-paper.scss 67:9                                     @import
  ~\Temp\broccoli-33908ODcfd9W6jKDi\out-290-broccoli_merge_trees_full_application\app\styles\app.scss 1:9                                              root stylesheet
    at Object._newRenderError (C:\git\ember-paper-test\node_modules\sass\sass.dart.js:10877:19)
    at Object._wrapException (C:\git\ember-paper-test\node_modules\sass\sass.dart.js:10727:16)
    at _render_closure1.call$2 (C:\git\ember-paper-test\node_modules\sass\sass.dart.js:33888:21)
    at _RootZone.runBinary$3$3 (C:\git\ember-paper-test\node_modules\sass\sass.dart.js:19912:18)
    at _RootZone.runBinary$3 (C:\git\ember-paper-test\node_modules\sass\sass.dart.js:19916:19)
    at _FutureListener.handleError$1 (C:\git\ember-paper-test\node_modules\sass\sass.dart.js:18381:19)
    at _Future__propagateToListeners_handleError.call$0 (C:\git\ember-paper-test\node_modules\sass\sass.dart.js:18669:40)
    at Object._Future__propagateToListeners (C:\git\ember-paper-test\node_modules\sass\sass.dart.js:3495:88)
    at _Future._completeError$2 (C:\git\ember-paper-test\node_modules\sass\sass.dart.js:18505:9)
    at _AsyncAwaitCompleter.completeError$2 (C:\git\ember-paper-test\node_modules\sass\sass.dart.js:17904:12)
(node:33908) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 4)
(node:33908) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.`

ember-cli: 3.15.1
node: 12.14.0
os: win32 x64

I get this after creating a new server, then running `ember i ember-paper`, then `ember s`

Not sure what I should do to resolve this.

**Comment by miguelcobain** [comment]
The problem is that it is picking up a new version of `angular-material-styles`. Sorry about this. :(

For a quick fix, if you're using yarn, you can add
```json
"resolutions": {
  "angular-material-styles": "1.1.18"
}
```
in your `package.json`.

Will release a new ember-paper version asap.

**Comment by skeough** [comment]
Unfortunately I don't use yarn on my windows computer.

I noticed that there was an commit pushed regarding this.  Is there something I need to do to use this latest commit?

**Comment by miguelcobain** [comment]
@skeough you can try using `"ember-paper": "miguelcobain/ember-paper#master"` while a new release isn't out.
Sorry to everyone about this. I didn't see this coming. Promise a new release will be out soon and will update here.

**Comment by skeough** [comment]
Yep!  changed it to your git, regenerated, and it works now.

As an FYI, they are pushing the <> notation rather than {{ }} with 3.15, you may want to ready Templating on the github.io site for that.

**Comment by FilipeVeber** [comment]
> @skeough you can try using `"ember-paper": "miguelcobain/ember-paper#master"` while a new release isn't out.
> Sorry to everyone about this. I didn't see this coming. Promise a new release will be out soon and will update here.

I also installed and ran `ember serve` then I changed as you asked to but didn't work here.


My error message is a little bit different: 

`Error: $string: rgba(0, 0, 0, 0.38) is not a string.
   ╷
35 │       color: unquote($color);
   │              ^^^^^^^^^^^^^^^
   ╵
  C:\Users\filipe.veber\AppData\Local\Temp\broccoli-19320HrRLk3NGz1EO\out-290-broccoli_merge_trees_full_application\app\styles\angular-material\core\style\mixins.scss 35:14             input-placeholder-color()
  C:\Users\filipe.veber\AppData\Local\Temp\broccoli-19320HrRLk3NGz1EO\out-290-broccoli_merge_trees_full_application\app\styles\angular-material\components\chips\chips-theme.scss 19:11  @import
  C:\Users\filipe.veber\AppData\Local\Temp\broccoli-19320HrRLk3NGz1EO\out-290-broccoli_merge_trees_full_application\app\styles\ember-paper-components.scss 23:9                          @import
  C:\Users\filipe.veber\AppData\Local\Temp\broccoli-19320HrRLk3NGz1EO\out-290-broccoli_merge_trees_full_application\app\styles\ember-paper.scss 67:9                                     @import
  C:\Users\filipe.veber\AppData\Local\Temp\broccoli-19320HrRLk3NGz1EO\out-290-broccoli_merge_trees_full_application\app\styles\app.scss 1:9                                              root stylesheet`

**Comment by skeough** [comment]
If you install via git, or changed to the git afterwards, you need to run `ember g ember-paper`

**Comment by FilipeVeber** [comment]
Now it's working!

Thanks @skeough

**Comment by cmoihub** [comment]
still getting this issue on trying to update ember-paper

**Comment by tycoles** [comment]
Where are you guys changing this dependency to the master branch?

**Comment by jasonworden** [comment]
I also ran into this issue but sidestepped it by putting `"ember-paper": "miguelcobain/ember-paper#master"` in by `package.json` (via https://github.com/miguelcobain/ember-paper/issues/1119#issuecomment-571192235).

**Comment by miguelcobain** [comment]
Released `1.0.0-beta.27` which should fix this issue, among other things.
Please check the changelog: https://github.com/miguelcobain/ember-paper/blob/master/CHANGELOG.md
