### ISSUE TITLE
1.0.0-beta.27 was breaking my build due to tests dont pass

### ISSUE THREAD

**Issue by AndresCL** [miguelcobain/ember-paper#1122]
![image](https://user-images.githubusercontent.com/1790792/74060989-dcce8e80-49c9-11ea-8475-6c88045cc94c.png)

**I had to revert to 1.0.0-beta.26 to make it build again.** as current version tests are failing.

Im using
"ember-cli": "3.11.0"
"ember-source": "3.4.0"

I hope this helps someone.

**Comment by betocantu93** [comment]
@AndresCL `1.0.0-beta.27` requires ember >= 3.11 

Check out the changelog: https://github.com/miguelcobain/ember-paper/blob/master/CHANGELOG.md#100-beta27

**Comment by AndresCL** [comment]
Yeah, Im using 3.11.0

**Comment by miguelcobain** [comment]
@AndresCL in the original post you said you were using ember 3.4.

**Comment by AndresCL** [comment]
Right, my mistake.
