### ISSUE TITLE
#parentComponent computed property was just overriden.

### ISSUE THREAD

**Issue by wukongrita** [miguelcobain/ember-paper#1146]
Hi @miguelcobain ,

I try to migrate from Ember 3.8 to Ember 3.16 by creating clean project with a simple form in the templates:

application.hbs
```
<PaperForm as |Form|>
  <Form.input
    @label="E-mail"
    @value={{this.value}}
    @onChange={{action (mut this.value)}}/>
</PaperForm>
```

run the `ember s` and I got deprecation like below:

```
#parentComponent computed property was just overriden. This removes the computed property and replaces it with a plain value, and has been deprecated. If you want this behavior, consider defining a setter which does it manually.
```

Is there anything wrong with my simple code? and how should I fix it?

---
```
ember -v
ember-cli: 3.16.1
node: 12.16.1
os: linux x64


Ember | 3.16.8
Ember Data | 3.16.5
Ember Paper | 1.0.0-beta.29
```

**Comment by miguelcobain** [comment]
Can you test on beta 30? It should be fixed.

**Comment by wukongrita** [comment]
Hi @miguelcobain ,  I've tried .30 few days ago and seems already works fine..

I will report if there are any other warning / deprecation, since I'm implementing a real app with this Ember-Paper; hope you don't mind if I got a little bothering you...

Thank you...
