### ISSUE TITLE
PaperMenu flies into screen from left side on firefox

### ISSUE THREAD

**Issue by lucasmerat** [miguelcobain/ember-paper#1160]
Recently while testing our app in FireFox, we noticed that the paper menu component has an odd animation issue. The menu will fly in from the top left side of the screen. I tested this in multiple contexts and different usages of the paper menu component. 

Note that this is an intermittent issue and happens most, but not all of the time.

Here is a link to a screen cap of the interation: https://drive.google.com/file/d/11hpsmaBOl2Pq45hA7OhrQuVAjIa7inrY/view?usp=sharing

**Comment by hergaiety** [comment]
I see this happening consistently on https://miguelcobain.github.io/ember-paper/#/components/menu

**Firefox 79.0 on Ubuntu**

![Peek 2020-08-18 09-23](https://user-images.githubusercontent.com/1664093/90525228-a5892900-e134-11ea-85e8-acb3696b4cd0.gif)

**Comment by pax7** [comment]
I have a similar (if not the same) issue where basically the @position is only honored the first time and then it flies in from the left.

**Comment by CodingItWrong** [comment]
There are some notes in #1151 related to a suggested fix for this

**Comment by pax7** [comment]
I can confirm that this fixes flying from the left issue and the !paperElement issue:
```
if (!parentElement) {
      parentElement = document.getElementById('ember-basic-dropdown-wormhole');
    }
```

while this:
`if (!parentElement) return;`

only fixes the !paperElement issue.

**Comment by miguelcobain** [comment]
I released this fix on `1.0.0-beta.33`. Can you please try if it works now and reopen if there is any further related problems?

Also, @hergaiety, the can you please retry the website on Ubuntu and see if it is fixed now?

**Comment by hergaiety** [comment]
@miguelcobain thanks for your attempts at resolving this! Alas I'm still seeing the same on the website and within our app when bumping to `1.0.0-beta.33`.

@lucasmerat would you check on your end as well and reopen this if needed?

**Comment by lucasmerat** [comment]
@hergaiety @miguelcobain Can confirm that I'm still seeing the issue on FireFox on the Ember Paper website and our app.

**Comment by CodingItWrong** [comment]
@lucasmerat Can you mark the GH issue as open for tracking?

Previously I saw this issue not only on Firefox but also Chrome and Safari iOS. With beta 33 I see Chrome and Safari iOS fixed, but not Firefox. Chrome:

![chrome-works](https://user-images.githubusercontent.com/15832198/93484763-4d2e7e00-f8d0-11ea-8352-e9629d1f8eed.gif)

Firefox:

![firefox-does-not-work](https://user-images.githubusercontent.com/15832198/93484776-515a9b80-f8d0-11ea-883a-2dda4423b462.gif)

**Comment by lucasmerat** [comment]
@CodingItWrong I'm not sure I know how to reopen the issue. Looking for that feature but can't seem to find it.

**Comment by CodingItWrong** [comment]
@lucasmerat I googled around and every time someone asks _how_ to reopen a GitHub issue, the responses are always _whether_ they can, but they don't say how 😂 😭  - So I guess our comments on the thread should be enough 👍
