### ISSUE TITLE
Deprecations when upgrading to Ember >= v3.20.x, {{-in-element}}

### ISSUE THREAD

**Issue by hergaiety** [miguelcobain/ember-paper#1165]
A few components in `ember-paper` rely on the private Ember API of `{{-in-element}}`, everything after Ember v3.20.x has deprecated that private API in favor of the now public `{{in-element}}`. https://github.com/emberjs/ember.js/releases/tag/v3.20.0

[RFC for this change in Ember](https://github.com/emberjs/rfcs/blob/master/text/0287-promote-in-element-to-public-api.md)

Example: https://github.com/miguelcobain/ember-paper/blob/master/addon/templates/components/paper-tooltip.hbs

**Comment by mohitsud** [comment]
same issue- would love to see this resolved.
