### ISSUE TITLE
paper-menu.item.shouldRenderButton doesn't handle the case when click handler is installed differently

### ISSUE THREAD

**Issue by 0x0badc0de** [miguelcobain/ember-paper#1172]
Template Linter is not happy with `<content.menu-item @onClick={{action this.someAction}}>` so I changed it to `<content.menu-item {{on "click" this.someAction}}>` as a result menu item is rendered without button wrapper. As a workaround I can set `shouldRenderButton` explicitly but wonder if there is a better solution or menu-item can catch the case with 'on click'?

**Comment by miguelcobain** [comment]
Why isn't the linter happy with `<content.menu-item @onClick={{action this.someAction}}>`?
Could it be because of the action helper?
`<content.menu-item @onClick={{this.someAction}}>` should work as well.

**Comment by 0x0badc0de** [comment]
Oh, you are right, that's the way. Sorry for bothering. Thanks!
