### ISSUE TITLE
error when building app with ember-paper

### ISSUE THREAD

**Issue by Talwynox** [miguelcobain/ember-paper#1180]
Hi, 
I run into this issue as soon as I add ember-paper to any project:

    Template Compiler Error (broccoli-persistent-filter:TemplateCompiler) in ember-basic-dropdown/templates/components/basic-dropdown-content.hbs
    
    Cannot read property 'type' of undefined

I am using Ember 3.25.0 and ember-paper 1.0.0-beta.35.

**Comment by omar-zakaria** [comment]
I have the exact same issue, using Ember 3.25.2 and ember-paper 1.0.0-beta.35.

**Comment by hsduiii** [comment]
x3

**Comment by ratelutz** [comment]
same issue here using ember-cli 3.25.2 and ember-paper 1.0.0-beta.25

**Comment by ratelutz** [comment]
this more investigation. all above ember-cli@3.8.1 failes for me.

**Comment by oakho** [comment]
fwiw, there is an open issue in the ember-basic-dropdown repository (see https://github.com/cibernox/ember-basic-dropdown/issues/586)

ember-paper is also the culprit in my case and adding resolutions to my package.json didn't work, currently don't have much time to investigate this issue but, as a workaround, downgrading ember-cli to 3.24 solve this issue temporarily.

anyway, ember-paper uses an old versions (2.x) of ember-basic-dropdown and ember-maybe-in-element so it doesn't help

**Comment by ratelutz** [comment]
> fwiw, there is an open issue in the ember-basic-dropdown repository (see [cibernox/ember-basic-dropdown#586](https://github.com/cibernox/ember-basic-dropdown/issues/586))
> 
> ember-paper is also the culprit in my case and adding resolutions to my package.json didn't work, currently don't have much time to investigate this issue but, as a workaround, downgrading ember-cli to 3.24 solve this issue temporarily.
> 
> anyway, ember-paper uses an old versions (2.x) of ember-basic-dropdown and ember-maybe-in-element so it doesn't help

ember-cli@3.24. does not work for me. i failes with another compile error
Template Compiler Error (broccoli-persistent-filter:TemplateCompiler) in ember-paper/components/paper-autocomplete/options/template.hbs

**Comment by icheered** [comment]
Still an issue. Has anyone found a workaround?

**Comment by mohitsud** [comment]
I chased this down quite a bit. Sadly the best solution for me was to simply migrate away from ember-paper. A true shame since it was such a great addon.
