### ISSUE TITLE
Could we keep a changelog?

### ISSUE THREAD

**Issue by kitsunde** [miguelcobain/ember-paper#121]
It took me a while to realize that `paper-tile-left` was removed and wasn't just my app acting up:

https://github.com/miguelcobain/ember-paper/commit/47fe537018979b78a12df4ebb6de1b14ed939958

**Comment by SirZach** [comment]
@kitsunde do you know what replaces <code>paper-tile-left</code>? I was using that guy as well.

**Comment by kitsunde** [comment]
@SirZach Just basic css-classes. There's an updated example at: https://miguelcobain.github.io/ember-paper/#/list

**Comment by SirZach** [comment]
<code>paper-tile-content</code> is also gone in case anyone searches the issues.

**Comment by SirZach** [comment]
a migration guide would also be appreciated.

**Comment by SirZach** [comment]
i cannot reproduce <code><md-list-item id="ember4391" class="ember-view md-3-line" role="listitem" tabindex="-1"></code> specifically around the <code>md-3-line</code> class. When I use a <code>{{paper-item}}</code> it doesn't produce this class and when searching the ember-paper 0.2.2 directory, I cannot find this class.

**Comment by kitsunde** [comment]
@SirZach Are you trying to imitate this: https://miguelcobain.github.io/ember-paper/#/list-controls? There's a bug in the documentation. It should be `classNames` not `class`.

```handlebars
{{#paper-item classNames="md-3-line"}}
  testfoo
{{/paper-item}}
```

The class is definitely in the project. It's here: https://github.com/miguelcobain/ember-paper/blob/47fe537018979b78a12df4ebb6de1b14ed939958/app/styles/paper-list.scss#L166 and I have it locally on my end.

**Comment by SirZach** [comment]
Thanks!
