### ISSUE TITLE
Quest: Ember 4 + Octane

### ISSUE THREAD

**Issue by Subtletree** [miguelcobain/ember-paper#1213]
This is intended as a naive list of work needed to bring ember-paper up to Ember 4 and octane standards. Potentially some codemod work could help before handling items indivudually.

Work could posssibly proceed in this order:

1. Completion/feedback of this list.
2. Fix existing flaky tests.
3. Codemods or other horizontally applied updates across the codebase.
4. Individuals pick off parts to complete.
5. Release 1.0.0 😮

- [ ] Fix existing flaky tests

**Ember 4 removed APIs**  (https://blog.emberjs.com/ember-4-0-released)
- [ ] Remove `willTransition`
- [ ] Remove jQuery

**Mixins** ([some guidance](https://github.com/miguelcobain/ember-paper/issues/1117#issuecomment-571193886))
- [ ] Child / Parent
- [ ] Color
- [ ] Events
- [ ] Focusable
- [ ] Proxiable
- [x] Ripple (@miguelcobain https://github.com/miguelcobain/ember-paper/commit/7cdcabc03c97d97e756393b45c51fb81da092af1)
- [x] Transition (@Subtletree https://github.com/miguelcobain/ember-paper/pull/1201)
- [ ] Translate3D
- [ ] Validation

**Native class syntax**
- [ ] Components  ([helpful conversion cheat sheet](https://ember-learn.github.io/ember-octane-vs-classic-cheat-sheet/#component-properties))

    - [x] Autocomplete (@miguelcobain https://github.com/miguelcobain/ember-paper/commit/fac7fc6e707791484938de35293c639855cdbfc0)
    - [ ] Button
    - [ ] Card
    - [ ] Checkbox
    - [x] Chips (@miguelcobain https://github.com/miguelcobain/ember-paper/commit/beac87fd6f96b1b391e646d792858cfaffbba710)
    - [x] Contact chips (@miguelcobain https://github.com/miguelcobain/ember-paper/commit/beac87fd6f96b1b391e646d792858cfaffbba710)
    - [ ] Dialog
    - [ ] Grid list
    - [ ] Icons
    - [ ] Input
    - [ ] List and List controls
    - [x] Menu (@miguelcobain https://github.com/miguelcobain/ember-paper/commit/fac7fc6e707791484938de35293c639855cdbfc0)
    - [ ] Progress circular
    - [ ] Progress linear
    - [ ] Radio and radio group
    - [x] Select (@miguelcobain https://github.com/miguelcobain/ember-paper/commit/fac7fc6e707791484938de35293c639855cdbfc0)
    - [ ] Sidenav
    - [ ] Slider
    - [ ] Switch
    - [ ] Tabs
    - [ ] Toast
    - [ ] Toolbar
    - [ ] Tooltip
    - [ ] ...

**Documentation**

- [ ] Merge https://github.com/miguelcobain/ember-paper/pull/1152 before other documentation work possibly
- [x] Angle bracket components (@gabrielcsapo https://github.com/miguelcobain/ember-paper/pull/1148)
- [ ] New action / modifier syntax
- [ ] Non ambiguous references e.g `{{this.post}}` or `{{@post}}` over `{{post}}`

**Comment by mansona** [comment]
hey @Subtletree 👋 I've been doing a lot of work recently to try to upgrade things for Ember 4, I'm mostly tackling some very specific deprecation warnings and then I'm going to be using [the Lint to the Future dashboard](https://miguelcobain.github.io/ember-paper/lint-to-the-future/) to track the rest of the work needed. 

I'm only slowly getting up to speed with the currently in progress tasks and issues so I haven' thad a chance to look at this Quest yet (or the previous Octane quest). Are you sure you want to close it?

**Comment by mansona** [comment]
We are now tracking work to convert support Ember 4.x and Octane conversion over in https://github.com/orgs/adopted-ember-addons/projects/6/views/1 👍
