### ISSUE TITLE
tabindex on paper-text causes the focus to be invalid

### ISSUE THREAD

**Issue by kitsunde** [miguelcobain/ember-paper#122]
Go here: https://miguelcobain.github.io/ember-paper/#/textfield focus on the first element. Tab through the input fields.

The first focus lands on the `md-input-group` which has a tabindex specified. You can't type on it. The second tab lands on the `input` where you can type. Effectively you have to double-tab to move between elements.

**Comment by miguelcobain** [comment]
@DanMonroe, please consider this. #120

**Comment by DanMonroe** [comment]
OK, I've got it fixed.  I'll include it in my next push.
