### ISSUE TITLE
changing primary color with 0.2.1

### ISSUE THREAD

**Issue by SirZach** [miguelcobain/ember-paper#123]
In <code>0.1.0</code> I could change the primary color by doing <code>$primary-color-palette: $color-orange;</code>. This doesn't seem to be working with <code>0.2.1</code>.

**Comment by miguelcobain** [comment]
We're now more aligned with angular material styles. Please use `$primary`.

[default-theme.scss](https://github.com/miguelcobain/ember-paper/blob/master/app/styles/default-theme.scss) is a good place to check theme variables. 

Sorry for this. These changes should have been documented somewhere. 
However, I believe that the recent changes placed us a step ahead.
