### ISSUE TITLE
Example for paper-item uses class instead of classNames

### ISSUE THREAD

**Issue by kitsunde** [miguelcobain/ember-paper#127]
This doesn't add the `md-3-line` class because the parameter should be `classNames`

```handlebars
{{#paper-item class="md-3-line" param=item action="goToPerson"}}
  <img src={{item.face}} alt={{item.who}} class="md-avatar">
  <div class="md-list-item-text">
    <h3>{{item.what}}</h3>
    <h4>{{item.who}}</h4>
    <p>{{item.notes}}</p>
  </div>
{{/paper-item}}
```

Problem is on this page: https://miguelcobain.github.io/ember-paper/#/list-controls (and maybe others). How are the docs being generated? I would submit a pull request but it's not clear to be what the source of gh-pages is.

**Comment by miguelcobain** [comment]
The source is in master. It's the dummy app!

**Comment by kitsunde** [comment]
@miguelcobain Ah cool. I'll fix this in a sec then.

**Comment by SirZach** [comment]
@kitsunde also found that the List docs don't include the <code>md-3-line</code> class. If you're in the docs, can you add that as well? I can get to it tonight if not.

**Comment by kitsunde** [comment]
@SirZach I've updated the example code with https://github.com/miguelcobain/ember-paper/pull/128. I was wrong that you must use `classNames` over `class`, I tested it on my end, but it seems like either is actually fine. Sorry for the confusion.
