### ISSUE TITLE
npm releases for ember paper

### ISSUE THREAD

**Issue by benedikt-d** [miguelcobain/ember-paper#129]
I can't install the latest version with npm:

Appears to be a git repo or submodule.
npm ERR! git    /node_modules/ember-paper
npm ERR! git Refusing to remove it. Update manually,

**Comment by miguelcobain** [comment]
Just did:
```bash
$ mkdir papertest
$ cd mkdir
$ npm install ember-paper
```

Got ember-paper installed inside a `node_modules` directory. Maybe it was fixed with the latest publish.
Reopen if you find any issues.
