### ISSUE TITLE
When Button wrapped in link to helper css gets messed up

### ISSUE THREAD

**Issue by benedikt-d** [miguelcobain/ember-paper#130]
When I wrap an icon button in a link to helper the CSS gets messed up. The padding seems to be different than without the link to helper.

**Comment by miguelcobain** [comment]
We need to find a way to provide the `link-to` functionality to `paper-button`.

**Comment by benedikt-d** [comment]
In md-toolbars the problem for the a tag not to work is that the css targets the last child or the first child which does not work if the button is wrapped in an a tag.
.md-toolbar-tools > .md-button:last-child {.md-toolbar-tools > .md-button:last-child}

How is this solved in angular material?

**Comment by H3Chief** [comment]
This is a bigger issue than just when `link-to` is used.  I broke a toolbar element out into it's own component (separate from the `paper-nav-element`), and the extra children break all the css (the toolbar no longer stretches across the entire width of the window.

**Comment by n1ru4l** [comment]
I use [ember-paper-link](https://github.com/Subtletree/ember-paper-link) for handling this.

I created an issue for moving those components to this addon since, they seem essential to me (https://github.com/Subtletree/ember-paper-link/issues/4)

**Comment by miguelcobain** [comment]
This is my recommended approach for this: https://github.com/miguelcobain/ember-paper/issues/203#issuecomment-317150800
