### ISSUE TITLE
Tests failing on ember-beta

### ISSUE THREAD

**Issue by miguelcobain** [miguelcobain/ember-paper#137]
Does anybody know why the tests are failing with ember beta channel?

https://travis-ci.org/miguelcobain/ember-paper/jobs/71699058

**Comment by peec** [comment]
Might be related to some of the changes in new beta released 19th of July:
https://github.com/emberjs/ember.js/blob/v2.0.0-beta.3/CHANGELOG.md

**Comment by miguelcobain** [comment]
The error is `TypeError: 'undefined' is not an object (evaluating 'Ember.View.extend')`.
The changelog states that `Ember.View` was removed, but I don't see where we're using Ember.View in our codebase. :/

**Comment by hhff** [comment]
might just be the log lookups in the test config @miguelcobain 

https://github.com/miguelcobain/ember-paper/blob/47fe537018979b78a12df4ebb6de1b14ed939958/tests/dummy/config/environment.js#L37

**Comment by hhff** [comment]
ahh thats dev..
