### ISSUE TITLE
disabled property on paper-button

### ISSUE THREAD

**Issue by kennethkalmer** [miguelcobain/ember-paper#142]
I'm trying to get a paper-button to have its `disabled` property set, but it seems the `disabled` property sits on the inner `span` tag. I had a quick glance through the history, and I'm not sure if this was intended or not, but it seems that when the `span` got introduced in bca53d8fa189b the properties were never moved up to `attributeBindings` in the component.

Was this intended or can I submit a PR?

At the moment I'm just re-exporting the component with `attributeBindings: ['disabled']` to get the intended behaviour.

**Comment by miguelcobain** [comment]
paper-button extends `BaseFocusable` which has a disabled attributeBinding. Also, there's a demo with disabled buttons. They seem to be working properly. What's your issue?

**Comment by kennethkalmer** [comment]
Not sure, I struggled with this strange behaviour for a bit, but now I nuked my custom button and my tests are all still passing... Apologies for the false alarm.

**Comment by miguelcobain** [comment]
No problem, mate. :+1:
