### ISSUE TITLE
material-design-icons dependency - increases page reload/rebuild times.

### ISSUE THREAD

**Issue by vmotsak** [miguelcobain/ember-paper#147]
Adding `material-design-icons` dependency to project looks like pulling whole icons plus sources,  adding near 40 megs to project and dramatically increasing page reload times I now have up to 20 seconds on almost empty project. May be some more light weight solution can be used like `ember-cli-material-design-icons`?

**Comment by peec** [comment]
ember-paper adds this to your app's `bower.json` file. This is currently a problem with `broccoli` and how it handles the dependency. What you can do as a temporary solution is to remove `material-design-icons` from your `bower.json` file. Icons will not work, but those load times will disappear. You might also just include the css file in your index.html as of now (this will make icons work).

**Comment by miguelcobain** [comment]
@vmotsak What ember-cli version are you using?
1.13.8 should have improvements on that.

Regarding the dependency, I also don't feel particularly happy to have to download a bunch of uneeded files, but I see an obvious advantage in using official icons. Right?

**Comment by vmotsak** [comment]
@miguelcobain thanks for the tip, it's much better on 1.13.8. 
As for dependency on `material-design-icons` maybe web font should be default way of connecting icon font http://google.github.io/material-design-icons/#icon-font-for-the-web  `Setup Method 1. Using via Google Web Fonts`. Roboto is added as web font why not use same approach for Icons?

**Comment by mnutt** [comment]
Currently it looks like ember-paper uses a material design font referenced from google's CDN anyway, so it doesn't look like the icons from `bower_components` are even referenced:

https://github.com/miguelcobain/ember-paper/blob/0a506c00af77d3235fc068262552a1b4f3d7c492/app/styles/ember-paper.scss#L30
