### ISSUE TITLE
Is the demo source code available?

### ISSUE THREAD

**Issue by jorgelainfiesta** [miguelcobain/ember-paper#159]
Hi,

I've read all the documentation and checked the individual components on this repo, but I still have doubts about how some elements are used in the demo page. It would be really helpful to have access to the demo source code, so I wonder if it is available. 

Thanks,
Jorge L

**Comment by elliot** [comment]
The demo is located in the test folder [here](https://github.com/miguelcobain/ember-paper/tree/master/tests/dummy/app)

**Comment by jorgelainfiesta** [comment]
Thanks!
