### ISSUE TITLE
Recommended way to theme?

### ISSUE THREAD

**Issue by jamesdixon** [miguelcobain/ember-paper#160]
Hi,

Is there a recommended way to apply a custom color scheme? I tried overriding variables, such as `$primary`, but ran into errors. I did see that there is a `default-theme.scss`, but I wasn't able to override the existing styles.

Thanks!
James

**Comment by mike1o1** [comment]
The order of importing your .scss files is important first.

In SASS, if a variable is defined and has `!default` on the suffix, it means that if this variable is already defined it won't overwrite it. You can see examples of this with the `default-theme.scss` file.

In my projects, I create a `variables.scss` file, and have my overwrites there.

```sass
$primary: "blue";
$accent: "indigo";

$base-background-color: #EDECEC;
```

Then, in my `app.scss`, I have to make sure to import `variables.scss` before importing `ember-paper.scss`.

My `app.scss` usually starts out like this:

```sass
//
// Modules: Mixins, variables and utilities
// ------------------------------------
@import "modules/variables";

//
// Libraries
// ------------------------------------
@import "ember-paper";

//
// Patterns
// ------------------------------------
@import "modules/global";
@import "modules/utility";
```

Hope this helps, if you're still having issues please let us know.

**Comment by jamesdixon** [comment]
Thanks, @mike1o1. I did exactly that, but I'm still not seeing a change in any of the colors. My order of imports is as follows:

```css
@import "_variables.scss";
@import "_mixins.scss";
@import "_fonts.scss";
@import 'ember-paper';
```
and my `_variables.scss` file contains the following:

```css
 $primary: "green";
 $accent: "teal";
```

I was expecting to see the button on the screen change from the default blue to green.

**Comment by mike1o1** [comment]
What does your button code look like?

**Comment by jamesdixon** [comment]
```handlebars
{{#paper-button raised=true primary=true class=text-uppercase action='nextStep'}}{{buttonTitle}}{{/paper-button}}
```

I also have a progress bar on the same page that is still defaulting to the red accent color rather than teal:

```handlebars
{{paper-progress-linear accent=true mode=mode value=progressPercent}}
```

**Comment by mike1o1** [comment]
Try adding `class="md-primary"` to your button and `paper-progress-linear` component. Otherwise your components and they default to the current color.

**Comment by jamesdixon** [comment]
Before I did that, I switched to the master branch rather than my fork and things started working. Very strange considering that I was only toying with the `paper-input` component. Sorry about that.

One other question regarding the theming: I noticed that these the colors are actually an array of different shades of a color. Do the components default to a specific shade of color?

**Comment by mike1o1** [comment]
It depends on the component, but typically it defaults to the primary color, #500. The [color page](http://www.google.com/design/spec/style/color.html) from the material design spec has a visual of all the colors.

The theming is definitely lacking documentation, but if you want to look at the styles for a particular component you have a question on, all the theming specific code is at the end of the .scss file.

**Comment by jamesdixon** [comment]
Great. Thanks a ton, Mike. Really appreciate it!

**Comment by ssirowy** [comment]
Any suggestions for trying to incorporate your own themed color?  I'm building an app that uses a different palette of blues,  and would love to mix that color in as if if was already there. 

Unfortunately I am not having much luck doing so.  I've tried various orderings, and even assigned `primary` directly to my new blue color as it appears the `color` function defined handles the case where the color isn't in the library defined `colors` map:

```
$primary: $color-myblue
```

but that spits out an error indicating the value isn't a valid CSS value.  Any help?  (Apologies if this is reading more like an SO post... this issue seemed relevant)

**Comment by mike1o1** [comment]
It's possible, but it's currently not documented. As I mentioned above, you'll need to define your `$primary` and/or `$accent` variable above, BEFORE you import the `ember-paper` scss file in your main `app.scss`.

To define your own custom palette, just create a [scss map](http://sass-lang.com/documentation/file.SASS_REFERENCE.html#maps) of your colors. You'll need to define each color that the addon is expecting, so just copy an existing one by looking at the [`color-palette`](https://github.com/miguelcobain/ember-paper/blob/373762ec0b384dc02819a6cd31422c062ec607f6/app/styles/color-palette.scss#L129), such as blue.

Define this map in a file, or before you define your `$primary` variable, then set the `$primary` value to be your color palette map.

As an example, I've created `custom-blue.scss`, with the following mapping:

```sass
$custom-blue: (
  '50': #DCEFFF,
  '100': #AAD1F9,
  '200': #7BB8F5,
  '300': #4C9EF1,
  '400': #1C85ED,
  '500': #106CC8,
  '600': #0159A2,
  '700': #025EE9,
  '800': #014AB6,
  '900': #013583,
  'A100': #82b1ff,
  'A200': #448aff,
  'A400': #2979ff,
  'A700': #2962ff,
  'contrast': rgba(255, 255, 255, 0.87)
);
```

In my `variables.scss` file, I have the following section defined:

```sass
$primary: $custom-blue;
$accent: "light-green";
```

Note that I'm referencing the the map variable directly, as this is a custom theme. `light-green` above is a predefined color palette, and can be referred to either as the string or the map variable directly. The color lookup method handles both scenarios for predefined palettes, but only accepts a map for custom palettes.

Now, in my `app.scss`, I just need to make sure that my ordering is correct. I want to import my custom theme, then my variables, then I can finally import `ember-paper`. See example below:

```sass
//
// Modules: Mixins, variables and utilities
// ------------------------------------
@import "modules/blue-theme";
@import "modules/variables";
//
// Libraries
// ------------------------------------
@import "ember-paper";
```

Hope this helps! Please create a new issue if you still have problems or questions.

**Comment by ssirowy** [comment]
@mike1o1  thanks for the info.  This is what I had been doing, but I keep getting an error at the terminal from the SASS compiler that looks like this:

```  javascript
("50": #DCEFFF, "100": #AAD1F9, "200": #7BB8F5, "300": #4C9EF1, "400": #1C85ED, "500": #106CC8, "600": #0159A2, "700": #025EE9, "800": #014AB6, "900": #013583, "A100": #82b1ff, "A200": #448aff, "A400": #2979ff, "A700": #2962ff, "contrast": rgba(255, 255, 255, 0.87)) isn't a valid CSS value.
Error: ("50": #DCEFFF, "100": #AAD1F9, "200": #7BB8F5, "300": #4C9EF1, "400": #1C85ED, "500": #106CC8, "600": #0159A2, "700": #025EE9, "800": #014AB6, "900": #013583, "A100": #82b1ff, "A200": #448aff, "A400": #2979ff, "A700": #2962ff, "contrast": rgba(255, 255, 255, 0.87)) isn't a valid CSS value.
```

Perhaps I am not understanding something in SASS, or have a different version than you?  The version of SASS in my `package.json` is 5.1.0

**Comment by mike1o1** [comment]
Can you post an example of how you're using it? I tried with the example above and everything worked fine for me. Can you post the full error and where you're using it that's throwing the error?

I tested using 5.0.1, though I don't think that's causing it. You're likely trying to access the $custom-color variable directly, instead of going through the `color` method. A full example could help us figure this out.

**Comment by ssirowy** [comment]
Sure.  I had actually done what you suggested,  but also just repeated in a vanilla Ember CLI + Ember Paper project.

I threw the project [into this repo. Here is all the styling I have in here](https://github.com/ssirowy/ember-paper-custom-palette/tree/master/app/styles)

I get the same error.  Here it is in full. 
``` javascript
File: ~/Documents/Ember/test-ember-paper/tmp/sass_compiler-input_base_path-mzxpk1hc.tmp/0/app/styles/my-colors.scss (2)
("50": #DCEFFF, "100": #AAD1F9, "200": #7BB8F5, "300": #4C9EF1, "400": #1C85ED, "500": #106CC8, "600": #0159A2, "700": #025EE9, "800": #014AB6, "900": #013583, "A100": #82b1ff, "A200": #448aff, "A400": #2979ff, "A700": #2962ff, "contrast": rgba(255, 255, 255, 0.87)) isn't a valid CSS value.
at options.error (~/Documents/Ember/test-ember-paper/node_modules/ember-cli-sass/node_modules/broccoli-sass-source-maps/node_modules/node-sass/lib/index.js:277:32)

```
I am not sure how to interpret that error.

**Comment by mike1o1** [comment]
@ssirowy: Looks like I found the issue, which we wouldn't have found without you trying to do a custom theme. The issue is with [`paper-select.scss`](https://github.com/miguelcobain/ember-paper/blob/373762ec0b384dc02819a6cd31422c062ec607f6/app/styles/paper-select.scss#L230) using the $primary value directly. When it's set to a map, it fails to build. 

Very weird that it works for me, but I believe I might be using a slightly older version of node-sass on my project.

I'll submit a pull request to fix, but if you'd like to patch it yourself for now, change the line above from `border-bottom-color: $primary` to `border-bottom-color: color($primary)`;

**Comment by ssirowy** [comment]
@mike1o1 great thanks for the help. That worked for now.  I'll watch for the PR so I can remove my local patch.
