### ISSUE TITLE
paper-button loses effects when used to transition

### ISSUE THREAD

**Issue by jamesdixon** [miguelcobain/ember-paper#164]
Hi,

I'm using `paper-button` in a component that when clicked, transitions to the next step in a flow. Unfortunately, it seems the effects disappear when transitioning. Even if I do a `setTimeout` before the transition, they still do not display. Because of the way the component functions, I've had to include the button in the component itself and therefore, every time I move to a new step in the flow, it is re-rendered. I realize that this may be due to the way in which I've set things up, but wanted to see if anyone had any thoughts or input.

Thanks!
James

**Comment by DanChadwick** [comment]
I know this is an old issue. If it is still an issue, maybe a fiddle would help us see what you want to accomplish? Please re-open if so!
