### ISSUE TITLE
Behavior of maxlength property/HTML property passthrough

### ISSUE THREAD

**Issue by jamesdixon** [miguelcobain/ember-paper#167]
I normally would have separated this into two issues, but they were very closely related, so my apologies ahead of time.

I added the `maxlength` property to `paper-input` anticipating that it would limit the number of characters I was able to enter in the field. Instead, this initializes the character counter, which counts the characters as the user types and shows the max amount of characters allowed, but it does not limit the number of characters able to be entered into the field.

I realize that the Angular Material spec does exactly this and it uses the `maxlength` property, but maybe it would be better to rename that functionality something else, such as `charCount`. That said, it seems that we should be able to pass through HTML properties even if they aren't enacted on in the component. 

I can think of a number of a couple of use cases off the top of my head:

- Allow the default HTML `maxlength` property to limit the number of characters entered into the field
- Allow for `data-*` properties to be passed through. For example, this would be helpful when using a plugin such as jquery.inputmask to add input masks to fields in a more declarative fashion.

Any thoughts on this? Disadvantages to allowing a pass-through?

**Comment by cah-danmonroe** [comment]
I've submitted a pull request (170) for pass-through attributes.  I'm not sure how we can pass through data-* properties though.  I heard "they" are working on a "splat" type that may work for us.  Wait and see I guess.

**Comment by peec** [comment]
Closed as of #170 is now in master.
Regarding `data-` attributes, lets wait for [Splat operator](https://github.com/wycats/handlebars.js/issues/1050) so we can easily pass-through data attributes.
