### ISSUE TITLE
Add other maintainers?

### ISSUE THREAD

**Issue by jamesdixon** [miguelcobain/ember-paper#174]
Hi,

First off, thanks for the great project. It's really fantastic.

I just wanted to echo @peec's previous comment about adding other maintainers. There a ton of pull requests waiting for review and it's been nearly a month since anything has been updated. I **completely** understand that it's a lot of work maintaining an open source project of this size and scope. That said, it would be great to add a couple of other core contributors that are both able and willing to help keep the project moving along. I'm not asking to be one of those individuals as I'm probably not qualified, but I'm more than willing to help where I can. I'm currently using library in my project, but unfortunately, without key pull requests being implemented for things such as select menus, I may be forced to abandon it.

Again, this is not any sort of criticism toward the creator or the project; it's just one of those hard realities when your project becomes so popular that it's tough to keep up and have a normal life!

Thanks and please let me know if there's anything I can do to assist.

Best,
James

**Comment by hhff** [comment]
:+1: there's now 4 maintainers on Ember Infinity, it's been so great for the library

**Comment by mhretab** [comment]
:+1:

**Comment by miguelcobain** [comment]
> I just wanted to echo @peec's previous comment about adding other maintainers.

I think I missed this!

@jamesdixon I feel totally fine with that.

@peec and @mike1o1 I can give you commit access to the project. Maybe that could speed things up. What do you think about it?

**Comment by peec** [comment]
Yea, I think such a large project should have more maintainers,

@miguelcobain That would be great from my perspective, I am using ember-paper on a new project at work so I have a need for the missing components.

**Comment by miguelcobain** [comment]
@peec you're now a collaborator! :shipit:

**Comment by mike1o1** [comment]
I'm happy to help with whatever i can!

**Comment by miguelcobain** [comment]
Done. :100:

**Comment by jamesdixon** [comment]
Thanks, @miguelcobain!
