### ISSUE TITLE
Disabled paper-* components can still be used through the {{#paper-item}} helper

### ISSUE THREAD

**Issue by hoboman313** [miguelcobain/ember-paper#175]
Consider the following code which is :
  {{#paper-item}}
    {{paper-icon icon="power-settings-new"}}
    <p>Lights</p>
    {{#paper-switch checked=true disabled=true}}On{{/paper-switch}}
  {{/paper-item}}

While the switch cannot be directly manipulated by clicking on it since it's disabled, it can still be checked/unchecked if the user clicks on the <md-list-item> element area from the {{paper-item}}.

**Comment by mike1o1** [comment]
Looks like a duplicate of #153.

**Comment by hoboman313** [comment]
Right you are.
