### ISSUE TITLE
Uncaught Error: Nothing handled the action 'toggleMenu'.

### ISSUE THREAD

**Issue by JKGisMe** [miguelcobain/ember-paper#177]
I just started a new project 2 days ago and haven't used ember-paper before. I pretty much just copied the sidenav code from the demo page (http://miguelcobain.github.io/ember-paper/#/sidenav). It seems ok when I view on a normal laptop screen but in a small mobile display when the side nav is hidden, if I tap/click on the menu button I get this error:

`Uncaught Error: Nothing handled the action 'toggleMenu'.`

I'm so confused about what's going on. When I search the ember-paper repo for `toggleMenu` I get results like this https://github.com/miguelcobain/ember-paper/blob/b52f5fd861b09a4fb138087f29d22cd310c1a340/addon/components/paper-sidenav-toggle.js but when I search my `node_modules/ember-paper` I get zero results. I just installed for the first time a couple days ago so I think what's in my project is current.

**Comment by peec** [comment]
It seems to me that you are using v0.2.7 of ember-paper. 0.2.8 was just released so  update the ember-paper package and you should be good

**Comment by JKGisMe** [comment]
Ahh ok, I thought it might be something like that. I guess I have to just build the dummy app locally ... or wait for 0.2.8 :smiley:

**Comment by peec** [comment]
You should be able to upgrade now:
https://github.com/miguelcobain/ember-paper/tree/v0.2.8

**Comment by JKGisMe** [comment]
Ooh, perfect! Thanks so much for the info!
