### ISSUE TITLE
paper-item: ripple-mixin causes ugly jumping-effect on list-controls on ipad when scrolled

### ISSUE THREAD

**Issue by damianthepichler** [miguelcobain/ember-paper#183]
If you scroll a page with list-controls on ipad, you get an ugly effect: The page scrolls very unsmooth and jumps around. It seems that the ripple-mixin is causing this bug. If you unbind the ripple-mixin on the list -component the problem disappears. You can see that on [ember-paper: list controlls](http://miguelcobain.github.io/ember-paper/#/list-controls). On the angular-page that issue does not appear.

**Comment by miguelcobain** [comment]
Thanks for the report. 

Can you please test if it happens with angular material as well?

**Comment by damianthepichler** [comment]
On the material-page it does not happen: [Angular Material](https://material.angularjs.org/latest/#/demo/material.components.list)

**Comment by DanChadwick** [comment]
Needs re-testing with current master.

**Comment by miguelcobain** [comment]
A lot of these components were refactored. I didn't heard or seems any complains like this.
Closing this. Please reopen if issue still present on latest versions.
