### ISSUE TITLE
Paper Button not preventing default behavior on click

### ISSUE THREAD

**Issue by JakeDluhy** [miguelcobain/ember-paper#19]
I was using the paper-button for a form, and the button was firing action and then submitting the form. I was able to fix it by changing

```javascript
click:function(){
   this.sendAction();
}
```
to
```javascript
click:function(){
  this.sendAction();
  return false;
}
```

**Comment by miguelcobain** [comment]
Please try the attribute `bubbles=false` on your paper-button component.

Check http://miguelcobain.github.io/ember-paper/#/button for an example.
