### ISSUE TITLE
enable slider labels to be always on

### ISSUE THREAD

**Issue by SirZach** [miguelcobain/ember-paper#190]
I have a use case where I want the labels for the value of the sliders to always be present, regardless of user interaction. Not sure if this is is already possible but I didn't see a public api for it. Thanks!

**Comment by miguelcobain** [comment]
Currently that label shows up when `md-slider` is focused. That means the show/hide logic is entirely within css.

I'm afraid the only way to accomplish what you're looking for is to override the styles to also apply when not in focus.

**Comment by SirZach** [comment]
Since it's very specific to one page that should be manageable. Thanks!
