### ISSUE TITLE
Action bar support?

### ISSUE THREAD

**Issue by christopherdumas** [miguelcobain/ember-paper#195]
I was just curious to see if you guys had any plans for adding support for even just putting `paper-input`s in a toolbar? It just seems like that is a very prominent feature in Android and Material Design.

Awesome library though. Great work!

**Comment by ssirowy** [comment]
:+1:  to this one.  A toolbar textfield akin to Inbox's search bar would be a fantastic addition (with configurable locations).

![screen shot 2015-11-09 at 4 01 26 pm](https://cloud.githubusercontent.com/assets/191263/11050521/9e37cbfe-86fb-11e5-91a1-e2f8589a58be.png)

**Comment by joukevandermaas** [comment]
I too would love this feature. Most controls appear to work already, their styling is just off.

**Comment by mellatone** [comment]
+1

**Comment by miguelcobain** [comment]
This is out of scope for ember-paper at the moment.
We now fully reuse angular material styles and this isn't present there.

As such this would maybe fit an ember-paper-* addon.
It isn't hard to do this yourself, though. It's just an input.
