### ISSUE TITLE
Would love to help with documentation, but website isn't public?

### ISSUE THREAD

**Issue by mansona** [miguelcobain/ember-paper#20]
Howdy, 

I've been meaning to try out your project for while but i haven't quite gotten around to it until now. I was hoping to follow a "getting started" section or something but I didn't see any on the website http://miguelcobain.github.io/ember-paper/#/ 

Is this a private github repo? I'd love to write some documentation as I go and maybe submit it as a PR

**Comment by fouad** [comment]
It's under the [`gh-pages` branch ](https://github.com/miguelcobain/ember-paper/tree/gh-pages). You can  switch to it using

```bash
git fetch origin
git checkout -b gh-pages origin/gh-pages
```

**Comment by mansona** [comment]
@fouad I knew there was something silly I was missing, thanks!

**Comment by mansona** [comment]
And i've just discovered that the website is in fact the dummy app in the test folder :joy:
