### ISSUE TITLE
Ripple container stays gray

### ISSUE THREAD

**Issue by jhr007** [miguelcobain/ember-paper#200]
https://miguelcobain.github.io/ember-paper/
If I click a link on the left nav, and then **quickly** click another link, the first link stays gray. 

The `div.md-ripple-container`, added to the dom on click, still has a style attribute of: `background-color: rgba(0, 0, 0, 0.1);` 

It seems like the second ripple stops the clean up on the first?

**Comment by DanChadwick** [comment]
I can't reproduce this on the `0.2` branch, as used on github.io. I suspect it's been fixed. If you can still reproduce it, please provide more details for how I can reproduce it.
