### ISSUE TITLE
Tab component

### ISSUE THREAD

**Issue by chrisitananese** [miguelcobain/ember-paper#201]
Before developing my own, I was just wondering if anybody is working on a tab component?
Any suggestion/comments appreciated

**Comment by miguelcobain** [comment]
@chrisitananese This would be great to have!

We need some discussion first, though.

As a reference, consider @mike1o1's implementation: http://mike1234.com/ember-material-design/#/tabs
Though, I think that @mike1o1 said he didn't like the implementation that much.

In Ember, a tabs ui can be implemented in many ways. But the most common are:
 1. using different routes and `{{outlet}}`ing in each tab content
 2. using query params (or other conditional flag) + `{{#if`s to render the content.

That the current way tabs work (even on @mike1o1's demo) is basically rendering all the tabs at once, and just hiding inactive ones. And I also think this is incompatible of the two tab implementation methods mentioned above. This is a "kind-of" anti-pattern as the hidden tabs may be unnecessarily expensive to render.
I assume that @mike1o1 implemented them this way to preserve the animations. Route transitioning, etc, + animations can be difficult in Ember. Maybe @peec can jump in and evaluate if our new animations mixin can makes this any easier.
At lease with route changes, that will be very difficult. Maybe @ef4 can jump in and briefly tell us how we should proceed. This would be so easy with liquid-fire...

/cc @mike1o1 @peec

**Comment by joukevandermaas** [comment]
Have you considered taking a dependency on liquid fire for ember paper? It might we worth it to help with animations going forward (think e.g. dialog boxes). You're already depending on ember-cli-sass so it's not a completely novel idea.

**Comment by miguelcobain** [comment]
@joukevandermaas using liquid-fire in an addon isn't very straighforward: https://github.com/ef4/liquid-fire/issues/195

**Comment by mike1o1** [comment]
I have a local branch with the tabs from Ember Material Design ported over, but I'm not 100% happy with it and it's a few months old. I think a lot the code can be cleaned up thanks to some new API's with recent versions of Ember. It's also a bit behind the Angular implementation.

For my implementation, as well as the Angular implementation, we do render all the tabs and use CSS transforms to animate between them. This has the benefit of the tabs being easy to setup and animate, but they don't respond to routes. There is binding available for the currently selected tab, so I suppose those can be bound to a query parameter in the URL.

**Comment by miguelcobain** [comment]
> There is binding available for the currently selected tab, so I suppose those can be bound to a query parameter in the URL.

It may be possible to bind the param, but the idea was to `{{#if` on the param to avoid rendering hidden tabs.

Maybe we can `{{#if` internally and render the destination tab before animating.

**Comment by bf4** [comment]
ref: https://github.com/miguelcobain/ember-paper/pull/212

**Comment by bf4** [comment]
@chrisitananese I can give you write to my fork if you want to collaborate there

**Comment by DanChadwick** [comment]
Closing in favor of PR #312, a nearly-complete implemenation of `paper-tabs`, which needs to be re-based against master.
