### ISSUE TITLE
paper-autocomplete: Initial state is not set with async data

### ISSUE THREAD

**Issue by estshy** [miguelcobain/ember-paper#202]
I have `countries` property which is fulfilled asynchronously. Unfourtunately in initial state I can not see selected country by default.

```
{{paper-autocomplete floating=true placeholder=(t 'label.country') source=countries lookupKey="name" required=true model=address.country}}
```

I've found workaround for that using conditional

```
{{#if countries.length}}
    {{paper-autocomplete floating=true placeholder=(t 'label.country') source=countries lookupKey="name" required=true model=address.country}}
{{else}}
    {{paper-autocomplete floating=true placeholder=(t 'label.country') source=countries lookupKey="name" required=true model=address.country}}
{{/if}}
```

I think that there should be an observer on `source`, which would cause to refresh `model` binding.

**Comment by miguelcobain** [comment]
@estshy Could #178 solve this?

**Comment by estshy** [comment]
Not sure. Instead of listening to `model` changes it should listen to `source` changes and then set again selected item as equal to `model`.

**Comment by xomaczar** [comment]
Close - fixed in paper-menu branch

**Comment by estshy** [comment]
Great

**Comment by cs3b** [comment]
@xomaczar this ticket should be closed?

**Comment by estshy** [comment]
@cs3b Correct

**Comment by xomaczar** [comment]
@cs3b this was fixed ~ 4 month ago

**Comment by cs3b** [comment]
@miguelcobain  please close this ticket - it will help to navigate through issues. thx :-)

**Comment by miguelcobain** [comment]
Thanks!
