### ISSUE TITLE
paper-button and link-to / routing

### ISSUE THREAD

**Issue by ycanales** [miguelcobain/ember-paper#203]
Hi there,

Awesome work you've done on ember-paper.
I'm just getting started on emberjs (with background in Angular and React) and I can't get to make the paper-button redirect to a view. Should I embed inside a link-to component?

Showing an example of paper-button and routing in the documentation would be super useful.

Thanks again for the awesome work.

**Comment by joukevandermaas** [comment]
In your controller you can do:

```js
actions: {
  transition() {
    this.transitionToRoute(...arguments);
  }
}
```

Then in your template:

```hbs
{{#paper-button action=(action "transition" "index")}}Go to index{{/paper-button}}
```

**Comment by ycanales** [comment]
Thanks a lot!!

**Comment by avdmatamoros** [comment]
Wouldn't it be better to have a way to indicate it is a simple redirect with params (ar a sort of sugar coated link-to) instead of having to define a controller with actions just for a link?

**Comment by mellatone** [comment]
Thoughts on a `{{paper-link}}` component that extends `{{link-to}}`?

**Comment by miguelcobain** [comment]
@mellatone we're using this addon: https://github.com/peec/ember-route-action

It isn't enough, right? E.g cmd + click

**Comment by mellatone** [comment]
I think there was talk of needing a proper anchor for accessibility and SEO: #207

**Comment by nucleartide** [comment]
A `{{paper-link}}` sounds good, I also like the fact that `{{link-to}}` automatically has an `active` class depending on whether the href matches the current route.

**Comment by taras** [comment]
[`ember-reactive-helpers`](https://github.com/EmberSherpa/ember-reactive-helpers) has [`(transition-to routeName)`](https://github.com/EmberSherpa/ember-reactive-helpers#transition-to-destination-model-query-params-foobar) helper.

You can use it like this: 
```hbs
{{#paper-button onClick=(action (transition-to "index"))}}
    {{route.title}}
{{/paper-button}}
```

It also supports query params.

**Comment by miguelcobain** [comment]
A better way to do this (renders a more semantic markup) is:

```
{{#paper-button href=(href-to "index")}}
    {{route.title}}
{{/paper-button}}
```

`paper-item` also supports this:
```
{{#paper-item href=(href-to "index")}}
    {{route.title}}
{{/paper-item}}
```

`href-to` helper is provided by `ember-href-to` addon.

**Comment by n1ru4l** [comment]
@miguelcobain I think this should be covered by the docs. If you like I could make a PR for this.

**Comment by miguelcobain** [comment]
@n1ru4l maybe on the button and list docs, yes.
Would love such a PR!

**Comment by RedTn** [comment]
@miguelcobain I tried the href for paper-item as you mentioned
`{{#paper-item href=(href-to "index")}}
  {{route.title}}
{{/paper-item}}`
but it doesn't work.
I think you need to add the href property on line 2 [here](https://github.com/miguelcobain/ember-paper/blob/master/addon/templates/components/paper-menu-item.hbs)?

**Comment by Subtletree** [comment]
@RedTn Did you install https://github.com/intercom/ember-href-to?

**Comment by RedTn** [comment]
@Subtletree Yes, sorry I just noticed that paper-item is not the same as paper-menu-item so technically it is working as intended, perhaps this is something that can be added as a feature request? Shall I create a PR?
