### ISSUE TITLE
Sidenav immediately closes upon any click - user unable to interact

### ISSUE THREAD

**Issue by mike1o1** [miguelcobain/ember-paper#204]
If a user opens the `{{paper-sidenav` component and performs any kind of click then it immediately gets closed, even if that click is on a non-link, such a toggle for a second level menu item. It appears that there is a `click` action handler that toggles the menu closed.

I don't think this is ideal, but I can see how it's needed to close the menu on route change. One option is to require the user to handle the `didTransition` event in their application route, to toggle the `sidebarVisible` property of the sidebar element to false.

This can be made a non-breaking, opt-in change by adding a new `closeOnClick` property with a default value of true. If this isn't set, then don't close on click. This way users can opt-in by explicitly setting this property to false.

**Comment by knownasilya** [comment]
I totally need this. I put forms in my sidebar, and if the window is small it always closes when interacting with the form.
