### ISSUE TITLE
documentation: describe flex and layout capabilities

### ISSUE THREAD

**Issue by EricSchank** [miguelcobain/ember-paper#206]
`ember-paper` has a great yet undocumented `flex` capability.

Documenting this will make it easier for people using `ember-paper`, and will likely improve the usability of their products.

**Comment by EricSchank** [comment]
Would love some feedback on this WIP.
Is this approach in line with how it's done on this project?
Thanks!

**Comment by joukevandermaas** [comment]
I've been using [the angular docs](https://material.angularjs.org/latest/layout/container) as documentation, and most (all?) of that seems to work. Maybe adding a link to those could help new users out though, I agree.

**Comment by DanChadwick** [comment]
Closing in favor of PR #380, which may have been based on this. not sure.
