### ISSUE TITLE
paper-item: Integrate link-to similar behaviour into paper-item and similar components

### ISSUE THREAD

**Issue by brisc** [miguelcobain/ember-paper#207]
Now, although we can use a transition action to simulate the link-to helper on some components (eg: paper-item) it's not the same as a link-to. It's important that the component should generate a <a> tag with href, so that link can be opened in a new page. It's also important for accessibility and SEO.
A sidenav that uses a paper-list with paper-items should have real href links.
Maybe add a link-to attribute on paper-item and a special handling like how it was done for action?

**Comment by avdmatamoros** [comment]
Agreed, it would be best to have something similar to a link and not need to rely on a custom action call for a simple redirect.

https://github.com/miguelcobain/ember-paper/issues/203#issuecomment-156232272

**Comment by Subtletree** [comment]
Made a first run at a `paper-link` addon. Extends `link-to` for `paper-button` and 'paper-item`

https://github.com/Subtletree/ember-paper-link

**Comment by miguelcobain** [comment]
Please see my comment at https://github.com/miguelcobain/ember-paper/issues/203#issuecomment-317150800
