### ISSUE TITLE
Side nav darkens and not clickable

### ISSUE THREAD

**Issue by ssirowy** [miguelcobain/ember-paper#208]
I just pulled Ember paper into a project for evaluation purposes, and I am noticing an issue where the side navigation element actually darkens and none of the sub-elements are clickable.  What is being darkened is actually the opposite of the expected (and what is shown on the demo page).

I just copied the template [from this page](http://miguelcobain.github.io/ember-paper/#/sidenav) into my application template (with a couple of small edits)

Here is a screenshot of what I am experiencing:

<img width="1002" alt="screen shot 2015-11-07 at 1 41 35 pm" src="https://cloud.githubusercontent.com/assets/191263/11016621/def91e24-8555-11e5-99b2-269d71af7ddf.png">

There is an error in the console indicating ember wormhole failed to render. Perhaps it has something to do with that?

**Comment by mike1o1** [comment]
The example code on the sidenav page doesn't include the paper-wormhole element that is required.

If you look at the code for the dummy app, specifically [application.hbs](https://github.com/miguelcobain/ember-paper/blob/373762ec0b384dc02819a6cd31422c062ec607f6/tests/dummy/app/templates/application.hbs) you'll see that you need to add an empty div for the ember-wormhole addon.

**Comment by ssirowy** [comment]
Completely missed that. Works like a charm.  Thanks @mike1o1

**Comment by miguelcobain** [comment]
We should use ember-cli's `contentFor` hooks to add this element automatically.
