### ISSUE TITLE
Add note about Wormhole

### ISSUE THREAD

**Issue by alexlafroscia** [miguelcobain/ember-paper#214]
Using Ember Paper for the first time in a while, it seems like it's improved a ton! One thing I noticed though; you need to add the Wormhole outlet to your `application.hbs` file, as such:

```hbs
<div id="paper-wormhole"></div>
```

However, this doesn't seem to be mentioned anywhere.  If it's not, could this be added to the Readme?

**Comment by miguelcobain** [comment]
@alexlafroscia That is correct.

I'd rather make the addon add that automatically using the contentFor hooks.
Similar to this: https://github.com/cibernox/ember-basic-dropdown/blob/master/index.js#L8

**Comment by alexlafroscia** [comment]
Oh, does that work? I'd be happy to make a PR to add that in; I absolutely agree that that's a better approach.

**Comment by miguelcobain** [comment]
I'd be very happy to accept such a PR. :)

**Comment by alexlafroscia** [comment]
Sweet, I'll put something together tonight/tomorrow.

**Comment by ssirowy** [comment]
:+1:
