### ISSUE TITLE
Ember Validations

### ISSUE THREAD

**Issue by avdmatamoros** [miguelcobain/ember-paper#216]
I see inputs have error handling which is great, but is it possible to integrate with ember validations? https://github.com/dockyard/ember-validations
At the moment I don't quite see a way to integrate server side validation error messages into the paper inputs.

**Comment by mike1o1** [comment]
Here is how I'm currently handling server side validations. In my controller/component, I have two computed properties to determine whether the field is valid, and another computed property which parses through my errors and returns a single error entry. I believe the material spec says to only display a single validation message at a time, so I'm ok with this.
  
Here is a code snippet of these two properties:
  
```javascript
propertyTypeIsInvalid: Ember.computed.notEmpty('propertyTypeErrorText'),
propertyTypeErrorText: Ember.computed('propertyType', '_validationErrors', function() {

  const propertyTypeErrors = this._collectValidationErrors('property-type', 'propertyType');

  return Ember.A(propertyTypeErrors).slice(0, 1);

}),
```
  
The `_validationErrors` is another property that is my server side error object. I  parse it to find errors related to this specific field, so I can display them. That is what `propertyTypeErrors` method above does.

In my template, I then set `isInvalid` and `errortext` to my computed properties above. I think the only issue here is that this will overwrite the built-in validations, or at least displaying those built-in validations on blur.
  
```hbs  
{{paper-input flex=true value=bufferedPropertyType label="Property Type" disabled=editDisabled
	isInvalid=propertyTypeIsInvalid
	errortext=propertyTypeErrorText
}}
```

**Comment by chbonser** [comment]
@avdmatamoros @mike1o1 I submitted a PR (#232) to add an `errors` attribute to paper-input.  With that change you can assign the errors property (a DS.Errors object) of an Ember Data model to the `errors` attribute of paper-input and it will display server side errors just like it displays its own native validation errors. So for example...
`{{paper-input label="Name" value=model.name errors=model.name.errors}}`

**Comment by VadimZhiltsov** [comment]
I had an issue with ember-paper and ember-validations too,
Problem was solved it as @chbonser said, but with little addition. 
I tried to validate value in controller, but name.errors had nothing. So I used controller's propery errors in such way:
```
{{paper-input label="Name" type="text" value=name errors=errors.name}}
```
errors.name - is strings array with validation messages.
I had to override method _setAppliedError, because it expects array with objects, which contains property message.
```
     this.set('errortext', errors.map( (item) => { return item.message; }).join(', ') );
```
So I just have added type comparison:
```
import PaperInput from 'ember-paper/components/paper-input';

PaperInput.reopen({
	_setAppliedError: Ember.on('init', Ember.observer('hasAppliedErrors', function() {
	    let errors = this.get('errors');
	    if(this.get('hasAppliedErrors')) {
	    	this.set('errortext', errors.map( (item) => { return typeof item === 'string' ? item : item.message; }).join(', ') );
	    }
	}))
});
```

**Comment by erzzo** [comment]
+1 need that too

**Comment by DanChadwick** [comment]
This will (shortly) be incorporated into `ember-paper`, which accepts an error message, and array of error messages, internal built-in validations, or internal validations defined by a custom function(s) you write.

This API should be extended to other elements, such as radio boxes, checkboxes, and select's.

**Comment by DanChadwick** [comment]
Please see the latest paper-input. Validation was changed extensively to support ember-data errors and external validation. The dummy app has some details and examples. Please reopen if you find it inadequate. Look in branch wip/v1.0.0, soon to become master.

**Comment by NullVoxPopuli** [comment]
How do I get this working?
I have:
```
    {{paper-input
      type='text'
      label='Last Name'
      required=true
      errors=(errors-for-input attendance 'attendeeLastName')
      value=(readonly attendance.attendeeLastName)
      onChange=(action (mut attendance.attendeeLastName))
    }}
```
the helper is:
```
import Ember from 'ember';

export function errorsForInput(params/* , hash*/) {
  const [model, field] = params;
  const modelErrors = model.get(`errors.${field}`) || [];

  return modelErrors.map(errors => errors.message);
}

export default Ember.Helper.helper(errorsForInput);
```

along with these other variations:

`errors=attendance.errors.attendeeLastName`  
`errors=attendance.attendeeLastName.errors`

And nothing shows the errors when I get errors back from the backend.

What am I doing wrong?

**Comment by miguelcobain** [comment]
@NullVoxPopuli paper-input only shows errors after the input has been "touched". You can force that with `isTouched=true`. We thought it was a good thing to have because. Imagine a required field. It feel strange to display "This field is required" before the user even had the chance to fill it.

**Comment by NullVoxPopuli** [comment]
It's true that I hadn't touched my inputs when I was testing -- but I removed required, and added isTouched -- but when I receive errors back, they seem to not be added to the input

**Comment by NullVoxPopuli** [comment]
actually, just checked ember inspector... errors aren't getting set on the model. great.
