### ISSUE TITLE
paper-item + paper-buttom + paper-icon: Tab key

### ISSUE THREAD

**Issue by m-hafi** [miguelcobain/ember-paper#220]
Pressing the Tab key on a page that lists paper items with paper button and have paper icon or paper menu icon, will change the position of that icon.

**Comment by joukevandermaas** [comment]
So I investigated it a little, and it turns out it's this line from `didInsertElement` in the `paper-item` component:

```js
this.$('.md-icon-button').addClass('md-secondary-container');
```

This makes the alignment happen, but apparently when a button gets focus it sets the `classNames` property again, causing Ember to overwrite all existing classes.

**Comment by joukevandermaas** [comment]
Note that this also happens if you change the button's class for other reasons. Example:

```hbs
{{#paper-item}}
    {{#paper-button icon-button=true class=(if buttonActive 'active')}}
{{/paper-item}}
```

**Comment by alexlafroscia** [comment]
Can you link to a page where this happens?

**Comment by joukevandermaas** [comment]
http://miguelcobain.github.io/ember-paper/#/list-controls

It only happens for buttons and it's the most obvious for the three line list item examples, so you have to press tab until you focus those.

**Comment by alexlafroscia** [comment]
Oh, interesting; I wasn't hitting tab enough to trigger it before.  I'll take a look and see if I can figure out how to prevent that.

**Comment by joukevandermaas** [comment]
For people who might run into this problem in the meantime, the obvious workaround is to add that class to the button yourself:

```hbs
{{#paper-item}}
  {{#paper-button icon-button=true class=(concat "md-secondary-container" (if buttonActive " active"))}}
{{/paper-item}}
```

**Comment by DanChadwick** [comment]
Does this still happen in `wip/v1.0.0`? If so, let's fix it. If not, well, um, let's just close this issue and back away quietly. :)

**Comment by joukevandermaas** [comment]
@DanChadwick list controls have not been updated for 1.0 yet. Let's make sure that the new implementation does not use JQuery to update classes on child elements (as to prevent this issue).
