### ISSUE TITLE
Inject script tag for buttons.js

### ISSUE THREAD

**Issue by alexlafroscia** [miguelcobain/ember-paper#221]
I just noticed that there seems to be another change that's necessary to make as part of the `index.html` when using Ember Paper, specifically [adding a `<script>` tag for `buttons.js`](https://github.com/miguelcobain/ember-paper/blob/master/tests/dummy/app/index.html#L27-L28).  Could we use the `contentFor` hook in the addon to add this, like we did with #219?

**Comment by miguelcobain** [comment]
@alexlafroscia that is the javascript for github buttons.

We only want that in the demo app, not on all of our users apps.

**Comment by alexlafroscia** [comment]
Ohh, I see. Didn't realize that.
