### ISSUE TITLE
paper-autocomplete: unable to scroll in Safari

### ISSUE THREAD

**Issue by Glennvd** [miguelcobain/ember-paper#225]
In other browsers, scrolling while having an autocomplete selectbox open freezes the ability to scroll in the page. In safari however, scrolling is possible and the options scroll with the page. See example: http://glennvandam.me/upload/Screen-Recording-2015-11-16-09-24-50-0RyjSqv7Ee.gif

**Comment by miguelcobain** [comment]
I think we should use an approach similar to what ember-power-select and ember-basic-dropdown uses.
Basically it recalculates the dropdown position when the page scrolls or resizes.
Never really like the idea of freezing the scrolling.

@peec @mike1o1 @Glennvd what are your thoughts about this?

Demo: http://www.ember-power-select.com/docs/how-to-use-it
(Open a dropdown and scroll the page).

**Comment by Glennvd** [comment]
I don't know where the original idea of freezing the scrolling came from, but it is indeed not a very user friendly solution. If it were up to me I would go for the ember-power-select approach, which seems much more intuitive to me.

**Comment by mike1o1** [comment]
The freezing of the scrolling comes from the angular implementation, however I've noticed that material-design-lite doesn't lock scrolling, so I suppose we can go either way. Personally I'm a fan of it, as the select menu itself will scroll properly when there are too many elements. The bug with Safari should be fixed, though.

**Comment by xomaczar** [comment]
Fixed. Can be closed
