### ISSUE TITLE
paper-input: allow access to validation state.

### ISSUE THREAD

**Issue by ssirowy** [miguelcobain/ember-paper#226]
This is more of a question and not so much an issue.

I'm taking advantage of quite a few of the paper input fields in a rather lengthy form,  and I was curious as to what best practices exists as it relates to *aggregating* all of the local validations occurring at each input field into a global `canSubmit` property that I could enable/disable a general button.

**Comment by ssirowy** [comment]
On another related note, is there a way to force a validator to run for a particular input programmatically?  I'm updating a value bound to a input with a validator programmatically and the validator does not fire.

**Comment by miguelcobain** [comment]
Maybe @DanMonroe can answer this.

**Comment by nucleartide** [comment]
I'm also interested in this. Maybe `{{paper-input}}` could be extended and validation could come from [ember-cp-validations][1]?

[1]: https://github.com/offirgolan/ember-cp-validations

**Comment by msounthar** [comment]
An example explaining the best way to do this will be great guys, @miguelcobain @DanMonroe Thanks!

**Comment by DanChadwick** [comment]
@nucleartide's solution should work well. If you use a validation package like `ember-cp-validations`, I sure you can do something similar.

Currently `{{paper-input}}` exposes `isInvalid`. An issue is that we don't consider an element invalid until the user has had a chance to edit (aka "touch") it. This prevents seens a fresh blank form filled with "This is required." messages. I do think we should expose something like `isReallyInvalid`, which can be or'd together to create an invalid function for disabling submit.

Let's close this, but I'm happy to re-open if there is further discussion or if I've missed something.

**Comment by msounthar** [comment]
@DanChadwick  
This is a basic requirement in any input form where we have to validate all inputs on submit. Angular material has a good implementation of this using ng-submit which can be seen in this fiddle,

https://jsfiddle.net/Styxiak/00eb8z09/

Same implementation of this, here in ember paper will be great.

Almost all validations are already implemented in ember paper elements except on submit, so do you think we have to use another package like ember-cp-validation just to handle this onsubmit scenario?

Any example of this implemented in a form with ember paper elements will be of great help. Thanks.

**Comment by DanChadwick** [comment]
I haven't tried this sort of form-type validation with the new `{{paper-input}}`, but I can see two parts that might be missing or troublesome. 

1. As mentioned, the component doesn't consider itself invalid until it has been "touched". I think it would help if `{{paper-input}}` exposed something like `isReallyInvalid` which represents the state of validation without regard to `istouched`. This would be a trivial enhancement.

2. I would be helpful for the form or dialog to tell the component that it should act touched. This could be accomplished by something like a `forceErrorDisplay` property. (Surely there has to be a better name.)

I think this could be related to a desire to display non-error help text where the error would go. I believe angular can do this, but I haven't looked at the details. For example, your `phone` field might display (not in red) "Best number to reach you." and then when needed "This is required." (in red). I hope these two features are independent. I mention it to ensure we don't do anything for one that might make the other harder.

I would support a PR for this sort of thing, absent criticism from other contributors.

**Comment by DanChadwick** [comment]
A further thought: reporting the invalidity with a data binding would be "data up". We could create a `onInvalidityChange` action, which reports `untouched`, `valid`, or `invalid`, where `untouched` implies invalid. This would mean that a form with 50 items would immediately trigger 50 actions as soon as the elements receive their attributes. Hmmmm.

**Comment by DanChadwick** [comment]
This has been implemented in the current `master` branch. That said, I'm totally in love with the values involved, and am open to discussion of them. 

`{{ember-paper}}` has an action `onInvalid` which sends these values:
- `false` - The value passes validation, or the component is about to be no longer rendered (i.e. it returns to a valid state upon being destroyed.
- `null` - The value is invalid, but no message is being displayed because the user hasn't touched the compoennt yet.
-  `true` - the valid is invalid and validation message(s) are displayed.

By tracking these actions (looking for `!== false`), one can aggregate them with a computed `or` property in order to disable the form submission button.

I'm open to discussion on these values.

**Comment by DanChadwick** [comment]
Closing for lack of further comment on the current implementation.
