### ISSUE TITLE
Paper button inside a paper item won't work in Firefox

### ISSUE THREAD

**Issue by m-hafi** [miguelcobain/ember-paper#228]
- @miguelcobain  http://miguelcobain.github.io/ember-paper/#/list-controls
 * In the Avatar with Secondary Action Icon section, try to click on the Phone Icon: not responsive

**Comment by jhr007** [comment]
I can confirm, but can't add anything else. 

In the last list, clicking on the phone icon pops up the wrong message. I can tab to the button and get the secondary button message but clicking it doesn't work.

**Comment by DanChadwick** [comment]
Currently works in 0.2. Also works in master. I presume something was fixed.

**Comment by DanChadwick** [comment]
Please re-open if this is still an issue.
