### ISSUE TITLE
paper-autocomplete: disableBodyScroll iOS

### ISSUE THREAD

**Issue by pomm0** [miguelcobain/ember-paper#231]
Hello,

i just integrated the paper-autocomplete component into my site and saw that it jumps around like hell.

I figured out that the disableBodyScroll-function may calc the top-value wrong if the keyboard is open in ios:

![img_1393](https://cloud.githubusercontent.com/assets/6084030/11497612/6162a0d4-981a-11e5-9036-34932ee1964c.PNG)

How to reproduce the bug (on iPhone):

1) open the ember-paper demo site and go to the autocomplete section (http://miguelcobain.github.io/ember-paper/#/autocomplete)
2) scroll down to "Floating Label" and write a country (play a bit, delete country - rewrite country ....) then you should see it does strange jumps and sometime it happens like the image above. If it doesn't occur please reload site and play a bit.

Actually it does not occur every time, i can't figure out whats the exact problem. With the OSX-Safari dev tools (connected with the iPhone) I saw that the top-value of the calculated position: fixed; on the body-tag has -290px (on iPhone 6) while on chrome-mobile emulator it always has top: 0; Maybe thats the problem?

Angular material does have some strange behaviors too, but not exact what i described above.

I have seen the issue on android one, two times as well but could not reproduce it on android.

Hope I described it well.
Thanks!

**Comment by miguelcobain** [comment]
We now use ember-power-select to implement our paper-autocomplete. If this problem persists, please reopen issue.
