### ISSUE TITLE
Paper-list slow to render with large lists

### ISSUE THREAD

**Issue by ssirowy** [miguelcobain/ember-paper#233]
It would be great if there was a way to provide functionality so paper list did not render all its items, especially when they are off screen.    Large lists can take a while to render, and this is only for a few hundred elements.
 
[Ember list view](https://github.com/emberjs/list-view) might be of help here for rendering list elements on demand.

**Comment by miguelcobain** [comment]
ember list view is unmaintained.
We should use ember-collection https://github.com/emberjs/ember-collection

**Comment by jhr007** [comment]
I heard about Smoke and Mirrors from the Ember Weekend podcast... https://emberweekend.com/episodes/whacked-out-hegemony-part-1

https://github.com/runspired/smoke-and-mirrors

**Comment by DanChadwick** [comment]
I'm not sure it's the job of a set of material design UI components to implement lazy rendering. If there is a nice implementation with `smoke-and-mirrors` or `ember-collection`, we could consider it, or it could be part of `ember-paper-cuts`, perhaps? Let's close this unless someone disagrees -- in which case let's open it up and discuss what we want to do.
