### ISSUE TITLE
Search and multiple selection functionality

### ISSUE THREAD

**Issue by avdmatamoros** [miguelcobain/ember-paper#234]
Would it be possible to have ember paper select component get a search / autocomplete tagging / multiple select feature similar to selectize, select2 and other jquery tools (except that it would have the material design look and feel).

https://github.com/miguelcobain/ember-cli-selectize/issues/129

something similar to (but :
https://material.angularjs.org/latest/demo/chips

**Comment by miguelcobain** [comment]
There is an (incomplete) implementation by @mansona here: https://github.com/miguelcobain/ember-paper/pull/115

**Comment by mansona** [comment]
Just updated that PR and added the contact chips. more detail on #115

**Comment by DanChadwick** [comment]
Closing in favor of #267. That issue is currently close only because the wip branch was merged into master. The PR needs rebasing against master.

**Comment by sergafts** [comment]
I kinda got lost following the PRs so I was wondering, is this perhaps implemented somewhere?
