### ISSUE TITLE
paper-select: not disabled properly

### ISSUE THREAD

**Issue by mike1o1** [miguelcobain/ember-paper#236]
If a user uses a `{{paper-select disabled=true}}` component with a disabled property, the disabled property does not get applied correctly to the `paper-select-core` component. The component is unable to be activated, which is the correct behavior, but since the `md-select` element does not have the `[disabled]` attribute, the CSS styling is incorrect.

**Comment by miguelcobain** [comment]
This should work correctly in the new paper-select.
