### ISSUE TITLE
paper-sidenav: cmd+click is not opening in new tab

### ISSUE THREAD

**Issue by Turbo87** [miguelcobain/ember-paper#240]
the title pretty much says it all: when I cmd+click on a link in the sidenav I would expect the link to open in a new browser tab, but unfortunately that doesn't seem to work and it just loads the page in the same tab.

**Comment by joukevandermaas** [comment]
That is because the list items use `paper-button` internally instead of `link-to`. You can't cmd+click buttons. See #207 and [#203](https://github.com/miguelcobain/ember-paper/issues/203#issuecomment-156232272).

**Comment by DanChadwick** [comment]
This seems to be a support issue, which has been answered. Please feel free to re-open with further discussion as needed.
