### ISSUE TITLE
Ember Paper Website Typography page does not scroll on mobile

### ISSUE THREAD

**Issue by FrancoB411** [miguelcobain/ember-paper#244]
Chrome Browser, Nexus 5x, Android 6.01
Scroll fine on chrome desktop. Does not scroll on Chrome mobile with above configuration.
http://miguelcobain.github.io/ember-paper/#/typography

**Comment by DanChadwick** [comment]
Is this still true on the current dummy app?
http://miguelcobain.github.io/ember-paper/release-1/#/typography

**Comment by FrancoB411** [comment]
Portrait mode:
After transitioning to checkbox page via the sidebar menu, the checkboxes do not work, and the hamburger menu stops working as well. (menu does not reappear).
On refresh, the checkboxes work, and the hamburger menu works once, but becomes unresponsive  after transition to another page. 

Landscape mode:
Side menu is visible. Clicking on checkbox link loads checkbox page, and retracts side menu.
Checkboxes work but the hamburger menu work.
Upon refresh, same behavior.

Nexus 5X running latest Android (M)

**Comment by DanChadwick** [comment]
Sounds like a javascript error is preventing further script execution. Can you use remote debugging to see if there are messages in the javascript browser console?

**Comment by DanChadwick** [comment]
Let's close this then, pending further data. The dummy app was updated yesterday with the latest sidenav from version 1.
