### ISSUE TITLE
paper-sidenav: Ember Paper Website, Side Nav Hamburger Menu does not trigger after a few taps

### ISSUE THREAD

**Issue by FrancoB411** [miguelcobain/ember-paper#245]
Nexus 5x, Chrome mobile, Android 6.01
After navigation several pages with the side menu, the hamburger menu stops triggering the side menu. 
Does not respond to touch inputs
Reloading the page make the hamburger menu respond to touch again. 
To recreate, load page, click hamburger, click introduction, click hamburger, click autocomplete. 
Click hamburger again, and it stop responding to touch input. No ink either.

**Comment by SirZach** [comment]
I've had experience with this on Android 6.0.0 Chrome Nexus 6 in my own app. Paper items become unresponsive and I have to do a page refresh.

**Comment by mival** [comment]
I have also this issue. I find out that sometimes after few open/close of hamburger menu there remain <md-backdrop> in div#paper-wormhole, which overlay whole page and does not accept touch/click events and page looks like not responding.

**Comment by vvsalmin** [comment]
+1

**Comment by miguelcobain** [comment]
This was fixed.
