### ISSUE TITLE
name-space scss files

### ISSUE THREAD

**Issue by SirZach** [miguelcobain/ember-paper#247]
I had declared my own <code>variables.scss</code> in my styles folder and as a result, it overrode ember-paper's <code>variables.scss</code> file. If all the <code>.scss</code> files brought in by ember-paper were namespaced the likelihood of collision would reduce.

**Comment by miguelcobain** [comment]
#249 will fix this.
Meanwhile, I can accept a PR that renames `variables.scss` (or others) with `paper-` prefix, for example.

**Comment by SirZach** [comment]
I'm not sure that it would be a good idea to only rename the one file as that will break most people's projects unless you did a bump to 0.3.x.

**Comment by miguelcobain** [comment]
Why would it break? People are `@import`ing files like `variables.scss`?

**Comment by SirZach** [comment]
True, I'm not importing `variables.scss` but I am importing `color-palette.scss` everywhere. In any case, it would still be a breaking change if someone is (perhaps to get a hold of the ember-paper's shadow styles?)

**Comment by bgohsman** [comment]
We also ran into this issue as well as conflicts with root-level variable names such as `$font-family`, `$font-size` and `$primary`. Prefixing names like these as well as things like `$colors`, `$default-color`, `$link`, `$foreground`, etc. may be a good idea at some point.

**Comment by DanChadwick** [comment]
Since the styles come directly from Angular Material, I don't think we can do much about this. I see the pain tho. Please reopen if you have other ideas.

**Comment by miguelcobain** [comment]
@DanChadwick I'm fairly positive that this problem does not happen in `wip/1.0.0` branch.

**Comment by miguelcobain** [comment]
well, it would happen with the scss files we have there: `color-palette` and `default-theme`.
