### ISSUE TITLE
Menu doesn't work in sidenav

### ISSUE THREAD

**Issue by knownasilya** [miguelcobain/ember-paper#254]
Getting something along these lines:

![screen shot 2015-12-31 at 2 48 10 pm](https://cloud.githubusercontent.com/assets/34726/12067761/8f44d394-afcd-11e5-9fb4-e9e7d93b4879.png)

Notice the big white block on the right, that's the menu.

**Comment by knownasilya** [comment]
Ah, I think it was some styling I had.. testing.

**Comment by knownasilya** [comment]
So that's fixed, but now the menu doesn't close when clicking the sidebar (outside the menu).

**Comment by knownasilya** [comment]
Looks like `body > div.ember-view:not(.md-default-theme)` is needed to prevent the menu from stretching. OR using legacy views and setting a class on the main `.ember-view` div.

**Comment by knownasilya** [comment]
So yeah, it doesn't disappear when clicking anything to do with the sidenav, either the nav or the overlay (in collapsed+open mode).

**Comment by knownasilya** [comment]
Ok, so z-index solves it, but the menu backdrop needs a class, e.g. `.md-menu-backdrop`

**Comment by miguelcobain** [comment]
Does #255 close this?

**Comment by miguelcobain** [comment]
Need a changelog on this. I'll just reopen this so I don't forget.
