### ISSUE TITLE
input masking

### ISSUE THREAD

**Issue by jamesdixon** [miguelcobain/ember-paper#258]
Any thoughts on supporting input masking in the future? I constantly come across the need to mask a phone number, SSN, etc. All of the current Ember solutions rely on their own custom input component, which obviously do not flow with the Ember Paper style. It would be great if there was a general approach that could wrap any input component, regardless of library, but not sure if that would be viable. Thoughts?

**Comment by TNAJanssen** [comment]
+1

**Comment by DanChadwick** [comment]
I would suggest that you subclass `{{paper-input}}`. The ember-paper team is focused on delivering a version 1.0, which will be functionally very similar to Angular Material 1.0.6. The sort of enhancement would probably be welcomed at `ember-paper-cuts`, which is a collection of useful ember-paper related add-ons that aren't part of Angular Material. If other collaborators disagree, please reopen and continue the discussion.
