### ISSUE TITLE
New install - Autocomplete Issues and one Question

### ISSUE THREAD

**Issue by brendanoh** [miguelcobain/ember-paper#259]
Uncaught TypeError: Cannot read property 'length' of undefined

```
  isMinLengthMet: Ember.computed('searchText', 'minLength', function() {
   return this.get('searchText').length >= this.get('minLength');
  }),
```

I have been doing this to avoid:

```
  isMinLengthMet: Ember.computed('searchText', 'minLength', function() {
   return isString(this.get('searchText')) ? this.get('searchText').length >= this.get('minLength') : false;
  }),
```

Also, this happens unless I comment it out.
```
Uncaught TypeError: this.get(...).disableScrollAround is not a function 
paper-autocomplete-list.js:105 

Uncaught TypeError: this.get(...).enableScrolling is not a function paper-autocomplete-list.js:111 
```

My HBS code:

```
      {{paper-autocomplete minLength=2
                           floating=true 
                           placeholder="Add a Language ..." 
                           source=allLanguages 
                           lookupKey="name" 
                           model=newlanguage}}
```

My versions:

ember-paper 0.2.10
Ember 1.13.11
Ember Data 1.13.15
Ember Inspector 1.9.4
Firebase 2.3.2
EmberFire 1.5.0
jQuery 1.11.3

Anyone else having this problem with a new project?
Any thoughts @miguelcobain or @mike1o1?

My question:

I know it is called an autocomplete control but why not add an ```isSearch``` or similar property and do this in the autocomplete filterArray method:
  ```    
return isSearch ? search.indexOf(searchText) !== -1 : search.indexOf(searchText) === 0; 
```

That way it can be used for a full text search instead of just autocomplete.

**Comment by canufeel** [comment]
Hi! can you please have a look if all this issues have been addressed here #199 ?

**Comment by brendanoh** [comment]
Thanks @canufeel - I like your idea behind your PR and I will test it locally. However, I would still add a param to allow a full text search or just a default autocomplete functionality. That way the behavior wouldn't change for anyone already using it.

Hopefully, someone else has seen the scrolling and minLength issues above.

**Comment by brendanoh** [comment]
Hmm it looks like I may have caused the other issues I described above... :frowning: 

Will close this once I confirm and will make comments on your PR @canufeel
