### ISSUE TITLE
ember-cli-uploader click not working with ember-paper

### ISSUE THREAD

**Issue by talhaobject90** [miguelcobain/ember-paper#262]
I am using 'ember-cli-uploader' addon with ember-paper's paper-card component. 
the uploader component was supposed to open a file upload dialog box. but it's not opening the dialog box. 

``` 
 {{#paper-card}}
 {{#paper-card-content}}
 {{#paper-list}}
 {{#paper-item}}   
{{file-upload item=item siteimages=item.siteimages    on-upload=(action "uploadSiteimage")  }}
{{/paper-item}}
{{/paper-list}}
{{/paper-card-content}}
{{/paper-card}}
```
is there any way to handle the on-click event? or any else way to fix it?
Thanks

**Comment by talhaobject90** [comment]
I just discovered that not even an href click is not working on paper-card. Wonder what went wrong!

**Comment by DanChadwick** [comment]
Sounds like this is not an issue with ember-paper. Please reopen if that's not the case.
