### ISSUE TITLE
paper-select: item-label-callback can't handle async data

### ISSUE THREAD

**Issue by sir-dunxalot** [miguelcobain/ember-paper#265]
First off, thanks for the great library! I'm hoping to contribute once I get my head around the setup.

If you use a paper select and there is already a value for the select, `item-label-callback` often gets fired before the model rendering the `{{paper-select}}` is resolved. This results in no selected value being shown in the dropdown.

Here is a simple example.

In the below code, a user has previously saved `model.color` so when they come back to the form they would expect to see the previously-chosen value there.

``` hbs
{{!-- components/color-form.hbs --}}

{{#paper-select
  model=model.color
  placeholder='Color'
  item-label-callback=selectColor
}}
    {{#each model.colors as |color|}}
      {{#paper-option value=color class='color-option'}}
        {{color.name}}
      {{/paper-option}}
  {{/each}}
{{/paper-select}}
```

``` js
// components/color-form.js

selectColor(color) {
  // This line is hit before model.colors has resolved and, thus, color.get('isFulfilled') returns false
  return color.get('name');
}
```

This happens regardless of whether model.colors is a relationship on the model or if the `colors` array is loaded using the `on-open` callback.

Perhaps `item-label-callback` could be delayed until the `{{paper-option}}`s have all been rendered?

**Comment by sir-dunxalot** [comment]
I also tried returning a promise in the item label callback, but that did not work as the promise object was set as the item label:

```js
selectColor(color) { // Is a callback use in different scope (paper-select)
  return new RSVP.Promise((resolve, reject) => {
    if (color.then) {
      color.then((resolvedColor) => {
        resolve(resovledColor.get('name'));
      }, reject);
    } else {
      resolve(color.get('name')));
    }
  });
},
```

Maybe allowing one to return a promise in the `item-label-callback` might be a solution. This would also be in line with the `on-open` spec.

**Comment by sir-dunxalot** [comment]
I can also confirm that the select populates with a preselected value when the value of model passed to the select component (e.g. `{{#paper-select model=model.color}}`) is not a promise.

**Comment by miguelcobain** [comment]
This bug was resolved when we used ember-power-select for our paper-select.
