### ISSUE TITLE
event-enter on paper-input sends action to component => error

### ISSUE THREAD

**Issue by JakeDluhy** [miguelcobain/ember-paper#266]
I tried to add an `event-enter` attribute on my `paper-input` component and ran into an issue where the `{{input}}` helper tries to send the action to the paper-input component, which doesn't handle it. Therefore I get the error
`Uncaught Error: <ember-boilerplate@component:paper-input::ember572> had no action handler for: actionName`
I was wondering if there is a way around this? Maybe there needs to be a passthrough action on the paper-input component?

**Comment by mike1o1** [comment]
I'm not sure I follow. Can you post a code snippet? I just tried this and it works for me, unless I'm misunderstanding what you're trying to do.

```hbs
{{paper-input type="text" event-enter=(action "test") label="Test"}}
```

Then, in my controller:

```js
  actions: {
    test() {
      console.log('on enter');
    }
  }
```

**Comment by JakeDluhy** [comment]
Oh, it seems the closure actions did it... I was doing 
```
//user-login.hbs (component)
{{paper-input label="Email"
              type="email"
              value=emailValue
              required=true
              customValidation=emailValidation
              class="spec-email-input"
              event-enter="loginSubmit"}}
```
where "loginSubmit" is an action on the component. And I was getting the errors. But when I switched to 
```
// user-login.hbs
...
event-enter=(action "loginSubmit")}}
```
it worked. Thanks!
