### ISSUE TITLE
Question:  Using Ember paper in an addon

### ISSUE THREAD

**Issue by ssirowy** [miguelcobain/ember-paper#269]
Are there any best practices for using/setting up Ember paper to be used in an addon?

Im building a number of common components for several apps we build into an addon that make use of Ember paper, and I'm having a bit of trouble in setting up the proper connections to make it work.

In my addon I can set up Ember paper just fine,  but then my "app" layer that makes use of the addon I'm getting errors of the nature:

`Assertion Failed: A helper named 'paper-nav-container' could not be found`

which indicates to me I'm not properly including it in my addon.

Any help would be appreciated.

**Comment by miguelcobain** [comment]
@ssirowy try to include ember-paper in `dependencies` and not `devDependencies` in package.json.

**Comment by ssirowy** [comment]
I gave that a shot, and in my app layer I get the following error right when I try `ember server`, I get the following errors:

<img width="1041" alt="screen shot 2016-01-25 at 10 40 11 am" src="https://cloud.githubusercontent.com/assets/191263/12560531/2ade9b88-c350-11e5-92de-191e0b6272ef.png">

... the only change being moving `"ember-paper": "0.2.10"` to dependencies from devDependencies.

I recognize I probably shouldnt be using this repo issue as a forum for debugging,  but any insights here?

**Comment by miguelcobain** [comment]
@ssirowy rerun `npm install`, please

**Comment by ssirowy** [comment]
No dice.  Im assuming there is nothing that should prevent this type of workflow right?

**Comment by miguelcobain** [comment]
Well, ember-cli isn't particularly streamlined for this.

I guess that you need to install ember-paper addon in the consuming app in the afterInstall hook of your addon.
Sort of like how this addon installs ember-cli-sass.

I'll close this as this isn't related with ember-paper.
However, please show up at Ember's slack at #ember-paper channel, or even at #needhelp, #general or #ember-cli.
People are always incredibly supportive in the ember community.

See you there.

**Comment by ssirowy** [comment]
Thanks for the help @miguelcobain . Much appreciated.
