### ISSUE TITLE
Installation: SASS file not finding ember-paper

### ISSUE THREAD

**Issue by ddoria921** [miguelcobain/ember-paper#272]
I'm trying to use ember-paper on a new ember project I just started. After running the `ember install ember-paper` command it all finished without any errors. 

After trying to load the project locally the build fails. It gives me the error `error app/styles/app.scss (Line 1: File to import not found or unreadable: ember-paper.`

I tried to search for this error but couldn't find any similar issues. Not sure if this is specific to my project. 

package.json shows "ember-cli-sass": "5.2.1"

**Comment by DanChadwick** [comment]
OP: did you resolve this?  It sounds like an installation issue.

**Comment by DanChadwick** [comment]
Please reopen if you need help.
