### ISSUE TITLE
Combine efforts with ember-cli-materialize

### ISSUE THREAD

**Issue by BryanHunt** [miguelcobain/ember-paper#28]
There is a [parallel effort](https://github.com/sgasser/ember-cli-materialize) to bring Material to ember, and I think it would be awesome if you and @sgasser could join forces and provide a single addon to the Ember community.  Thanks for this awesome work!

**Comment by stefanpenner** [comment]
Yes please :)

**Comment by miguelcobain** [comment]
Yes, I even made a contribution there. That thought already crossed my mind, but got a bit confused.

Please provide your inputs at #17.
