### ISSUE TITLE
paper-input converting number to string on cursor move

### ISSUE THREAD

**Issue by BryanHunt** [miguelcobain/ember-paper#282]
I have a paper-input with an initial value of say 500.  If I click the mouse in the input field and then use the left or right arrow keys, the paper-input value will trigger a change and the new value will be "500" instead of 500.

**Comment by miguelcobain** [comment]
@BryanHunt I think this happens with normal inputs. Can you test this with a regular `{{input`?
Suggestion: use ember-twiddle.com

**Comment by SaladFork** [comment]
Confirmed this is the behavior with a regular input: https://ember-twiddle.com/3e0c3231eed51d570cbb

Maybe we can consider special-casing the situation of `type="number"` to always return a number? Seems like the sort of thing that should be upstream in `{{input`, though.

**Comment by miguelcobain** [comment]
I see two things here:
1. changing typing/deleting a character changes type
2. moving the cursor changes the type **without typing**

Using the approach
```hbs
<input type="text" oninput={{action (mut value) value="target.value"}} value={{value}}/>
```

we apparently can get rid of 2.

**Comment by miguelcobain** [comment]
I'd also like to point out that this may be related with field validation.
e.g typing an `a` in a `type="number"` input.

**Comment by DanChadwick** [comment]
paper-input is now one-way, but the value returned from `onChange` will be a string. It is the `value` of the underlying `<input>`. See branch wip/v1.0.0, soon to become master.
