### ISSUE TITLE
Add support for switch dragging

### ISSUE THREAD

**Issue by miguelcobain** [miguelcobain/ember-paper#29]
Reference: https://github.com/angular/material/blob/master/src/components/switch/switch.js

**Comment by alexlafroscia** [comment]
Just as a heads up, I'm working on this one :)

**Comment by miguelcobain** [comment]
Awesome!

A sex, 6/03/2015, 00:11, Alex LaFroscia <notifications@github.com> escreveu:

**Comment by miguelcobain** [comment]
Using hammer.js?

A sex, 6/03/2015, 00:14, Miguel Andrade <jmandrade0@gmail.com> escreveu:

**Comment by miguelcobain** [comment]
Since we already include that dependency.

**Comment by alexlafroscia** [comment]
No, it doesn't use Hammer.js.  I will take a look at that and tweak what I did.  I got it worked, but had to deviate from the way that Angular does it because I couldn't get detecting the drag events to work right.  It also is less responsive than Angular's implementation, but I'm not sure why.
