### ISSUE TITLE
documenation: describe the flex layout options

### ISSUE THREAD

**Issue by mike1o1** [miguelcobain/ember-paper#297]
We should add documentation for all the flex layout options, and example pages/snippets.

**Comment by mellatone** [comment]
Agreed. I feel it would be worthwhile to add these examples as they stand today (using attributes in some places) so that new adopters will be able to start using `ember-paper` right away. We can prepare revisions to the documentation that are released once `1.0.0` lands.

**Comment by mellatone** [comment]
Real-world usage examples of `{{paper-grid-list}}` would also be helpful so that it's not confused with higher level flex layout stuff.

**Comment by DanChadwick** [comment]
Thanks to the work of @joukevandermaas, this has been done and is now deployed on the dummy/documentation app on github.io.
