### ISSUE TITLE
Theming

### ISSUE THREAD

**Issue by mellatone** [miguelcobain/ember-paper#298]
It'd be nice to provide an "API" spec of what can be safely overridden to theme `ember-paper`. It would also be good to note that Angular Material's style injection is not currently supported while @mike1o1's "hack" for name-spacing themes is a possible work-around.

**Comment by mellatone** [comment]
In fact it won't be too crazy to develop an interactive theme generator.

**Comment by miguelcobain** [comment]
Closing this in favor of https://github.com/miguelcobain/ember-paper/issues/360
