### ISSUE TITLE
Flexbox layout discussion

### ISSUE THREAD

**Issue by miguelcobain** [miguelcobain/ember-paper#30]
I'd like to raise a discussion for angular material layout capabilities: https://material.angularjs.org/#/layout/container

It's based on flexbox. How do you feel about it?
Should we go ahead and bring it to ember-paper right away?
Browser compatibility issues?

**Comment by rsaccon** [comment]
yes, I think this is the right way to go, in my opinion this is a better fit for ember than for example the boostrap-like CSS grid approach used by materialize-CSS (which has been discussed here a few times)

**Comment by miguelcobain** [comment]
For reference: http://caniuse.com/#feat=flexbox

**Comment by green-arrow** [comment]
I didn't look at the actual CSS, but I think as long as they include the 2012 syntax for IE 10 support, this is the way to go.

Even if IE 10 isn't supported, I still think it's a good idea. IE 10 support would just make it that much better.

**Comment by miguelcobain** [comment]
This is now on master.
Need mention this in the docs.
