### ISSUE TITLE
Effects not working in safari

### ISSUE THREAD

**Issue by miguelcobain** [miguelcobain/ember-paper#31]
> @miguelcobain When I click a button, I see the background color change within a rounded rect and no animation.

@BryanHunt do you see any difference between http://miguelcobain.github.io/ember-paper/#/button and https://material.angularjs.org/#/demo/material.components.button ?

**Comment by altrim** [comment]
I think @BryanHunt is using Safari. On the latest safari I am checking the effects are not working on buttons and same for switches, checkboxes and radio buttons are broken.

**Comment by miguelcobain** [comment]
Ember-paper or angular material or both?

**Comment by altrim** [comment]
Ember-paper, angular material works fine on safari

**Comment by miguelcobain** [comment]
Ok, thanks.

Don't have my mac around right now. Will try to have a look when i do.

**Comment by BryanHunt** [comment]
Yep, I'm on a Mac using Safari :) Yep, effects seem to be broken.  I see the effects on the Angular button but not the paper button.  IMHO, the wave effect on the materialize site is better than the Angular one.

**Comment by miguelcobain** [comment]
Ok, thanks. Don't know what may be happening. :confused: 
Side note: the discussion should be which effect is closer to specs (I don't know that answer).

**Comment by BryanHunt** [comment]
Just to close out the side note.  The Angular version seems to match the spec.  I'm all for going with the spec.

**Comment by btecu** [comment]
Not just the effects but most of the things seem broken in Safari:

![screen shot 2015-02-10 at 7 23 35 pm](https://cloud.githubusercontent.com/assets/7517745/6139484/60a5c34e-b15a-11e4-8f4f-32def8c6d353.png)

![screen shot 2015-02-10 at 7 23 48 pm](https://cloud.githubusercontent.com/assets/7517745/6139485/66e68d7e-b15a-11e4-86d0-84e06ec8a26d.png)

**Comment by BryanHunt** [comment]
I think the problem is more fundamental than effects.  It looks like the CSS is very broken in general on Safari - there are no headers on the sample application at all.  Looks great under Chrome.

**Comment by miguelcobain** [comment]
I could use some help in finding this bug. What kind of headers are missing?

**Comment by BryanHunt** [comment]
Here is a screenshot of what I get when I open http://miguelcobain.github.io/ember-paper/

![ember-paper_-_the_ember_approach_to_material_design_](https://cloud.githubusercontent.com/assets/504299/6181652/cacba160-b2fb-11e4-841c-ed1e23da0893.png)

**Comment by BryanHunt** [comment]
And here is the computed style for md-nav-container as an example.

![ember-paper_-_the_ember_approach_to_material_design_](https://cloud.githubusercontent.com/assets/504299/6181672/269995d8-b2fc-11e4-841a-62d6f96e2518.png)

**Comment by green-arrow** [comment]
@BryanHunt @miguelcobain looks like the root problem is Safari not understanding `display: flex`. By adding `display: -webkit-flex`, things start looking better. Looks like we need to just add in the `-webkit` prefix for flexbox layouts in order for this to work in Safari.

I think pulling in Autoprefixer and running that against our CSS would solve the issue nicely.

**Comment by miguelcobain** [comment]
What about this https://github.com/kimroen/ember-cli-autoprefixer ?

**Comment by green-arrow** [comment]
I'd have to read up on how to inject properties into `EmberApp`. I've never used an addon within an addon before :stuck_out_tongue: 

For this pass I just wanted to follow the patten you were already using in `postinstall.sh`.

**Comment by miguelcobain** [comment]
Let's stick with this for now.
I'm hoping to have a better sass build approach when this is solved: https://github.com/ember-cli/ember-cli/issues/2905

**Comment by green-arrow** [comment]
Sounds like a plan.

**Comment by BryanHunt** [comment]
AwesomeSauce!!
