### ISSUE TITLE
Deprecation: you modified ... twice in a single render

### ISSUE THREAD

**Issue by lolmaus** [miguelcobain/ember-paper#317]
> DEPRECATION: You modified (-join-classes "md-3-line" "ember-view" (-normalize-class "shouldBeClickable" shouldBeClickable activeClass="md-clickable" inactiveClass=undefined) (-normalize-class "hasProxiedComponent" hasProxiedComponent activeClass="md-proxy-focus" inactiveClass=undefined)) twice in a single render. This was unreliable in Ember 1.x and will be removed in Ember 3.0 [deprecation id: ember-views.render-double-modify]

This happened when added a checkbox to my list items.

**Comment by DanChadwick** [comment]
What branch/version are you using? If it's happening in `wip/v1.0.0` we certainly want to fix it.

**Comment by lolmaus** [comment]
Nope, that was on `0.2.12`.

**Comment by DanChadwick** [comment]
Cool. Well, development on that is, uh, `kaput`. :) We're focusing on getting the `wip/v1.0.0` branch. Let's close this unless there's reason to believe it happens in `wip/v1.0.0`. Thanks.
