### ISSUE TITLE
Source code for Documentation Site?

### ISSUE THREAD

**Issue by bytheway875** [miguelcobain/ember-paper#318]
Hello! I'd love to take a look at the source code of the documentation site so that I can see how exactly everything is formatted and works as a whole. Can you provide a link to it? 

Thanks!

**Comment by DanChadwick** [comment]
The documentation site is nothing more than installing `ember-paper` as if it were an application, in its own directory, and then running it like any other ember app by starting the server with `ember s` and directing your browser at `localhost:4200`. If you install ember-paper with git, you can switch branches and try both the master branch and the new wip/v1.0.0, which is where current development is happening.

**Comment by mellatone** [comment]
@bytheway875, thanks for reaching out! The documentation is an Ember app as @DanChadwick mentioned. If you'd like to take a look at the source code for the docs site specifically, you can browse that right here from GitHub: https://github.com/miguelcobain/ember-paper/tree/master/tests/dummy

**Comment by bytheway875** [comment]
@mellatone thanks! thats exactly what i was looking for.
