### ISSUE TITLE
TextArea doesn't shrink if underlying model is cleared

### ISSUE THREAD

**Issue by blimmer** [miguelcobain/ember-paper#329]
The textarea `paper-input` grows as the user enters text, but it doesn't respond when the bound value changes.

For instance, take this situation:
```javascript
// app/components/foo.js
message: null,

reset() {
  this.set('message', null);
}

actions: {
  submit() {
    ... save something .then() ...
    this.reset();
  }
}
```

```handlebars
// app/templates/components/foo.hbs

{{paper-input textarea=true value=message}}
```

If the user makes the textarea grow with a long message, when the value is set to null, the textarea doesn't shrink back down to its original size.

I think the root of the problem is that the `growTextArea` function is bound to keyboard input, which doesn't occur when the underlying value is reset. If you trigger a keyboard event in this situation, the paper-input returns to its normal size. ([src](https://github.com/miguelcobain/ember-paper/blob/8af553cb98b64d5ab908597d79fdecded0449643/addon/components/paper-input.js#L44-L46))

**Comment by blimmer** [comment]
For those of you experiencing this problem, and need a workaround, you can use this:

```javascript
// alongside your reset logic

run.scheduleOnce('afterRender', this, () => {
  this.$('textarea').first().keydown();
});
```

**Comment by DanChadwick** [comment]
In the `wip/v1.0.0` branch, soon to become master, this should be addressed. The textarea is resized after every render. Please re-open if you find this isn't the case.
