### ISSUE TITLE
Allow {{paper-input}} to set invalid from outside the component

### ISSUE THREAD

**Issue by craghavendra21** [miguelcobain/ember-paper#335]
Hi,

My scenario is 
I have a reset password page where I am using three text box 
1) **old_password**
2) **new_password_1**
3) **new_password_2**

Here my variables **new_password_1** and **new_password_2** both should not be empty and both should be same string.

For this I need to put a computed property **new_password_2_validated** for validating **new_password_2** which will observe the **new_password_1** and **new_password_2**, even any one of password value is changed it should check whether both password string is same or not.

So is that possible to achieve from existing validation? If yes please help me on this how to achieve this.
Else is that possible to make **isInvalid** variable as Boolean in **paper-input.js** and create another observer where this **isInvalid** should be set by observing the value.
So that I can change the is Invalid from outside from custom validation with multiple values observing.

There are some other pages in my project which is having many variables which is dependent on one another. This example just one of them.

Please help me on this ASAP.

**Comment by miguelcobain** [comment]
@craghavendra21 did you try `{{paper-input isInvalid=true`?

**Comment by craghavendra21** [comment]
yes, I tried to set but its firing both the code mine and {{paper-input}} validation function

**Comment by DanChadwick** [comment]
Closed in preference to discussion in  #336 on the same general topic.
