### ISSUE TITLE
recommendation: observer -> cp

### ISSUE THREAD

**Issue by stefanpenner** [miguelcobain/ember-paper#34]
https://github.com/miguelcobain/ember-paper/blob/master/addon/components/paper-button.js#L26-L37

rather then an observer the explicitly sets `z` let me recommend `z` becomes a computed property, that has the same dependentKeys are the observer does today.

* this is a more natural way to allow data to flow their the app
* only computed if someone consumes after dirtying
* most commonly will only result in 1 compute, regardless of the number of its DK's that change.

**Comment by miguelcobain** [comment]
That was actually still a frankenstein from the time I was porting from Polymer.
I refactored the whole thing, anyway. `z` and `ShadowMixin` are not need for now.
Thanks for pointing this out.

**Comment by stefanpenner** [comment]
:+1:
