### ISSUE TITLE
Button KeyPress Event

### ISSUE THREAD

**Issue by ajainvivek** [miguelcobain/ember-paper#340]
How can we add key press event in paper-button. I have tried quite few options no luck.

`{{#paper-button raised=true action=(action "signin" on="keyPress") class="btn-width"}}Log In{{/paper-button}}`

**Comment by DanChadwick** [comment]
`{{paper-button}}` should handle a keydown event with the enter key by itself. If you want to handle other keyboard events, I suggest you override `paper-input.js` and create your subclass. Or maybe I've misunderstood your need?

**Comment by ajainvivek** [comment]
I have two buttons on the screen one for login and other for register. When user inputs the value and user should be able to press enter key or click on login button. I am unable to bind enter keypress event. 

`<button {{action "signin" on="keyPress"}}>Login</button>`

What is the equivalent in ember paper button

**Comment by DanChadwick** [comment]
In your use case the button doesn't have focus so it doesn't get the keyboard events. But your handler on the paper-input component. I'm not sure if the new one generates enter events. Check latest in repo.

**Comment by miguelcobain** [comment]
@ajainvivek I believe what you need is to use a `<form onsubmit={{action "submitAction"`.

Please let us know if that did work for you and if it didn't, please show us a twiddle that illustrates the problem. This isn't ember-paper related.

**Comment by ajainvivek** [comment]
I was wrong with keyPress event assumption as it works only with input fields. I got it working by wrapping in form and having submit action

```
//hbs
<form class="" onsubmit={{action "signin"}}>
  {{#paper-button raised=true type="submit" class="btn-width"}}Log In{{/paper-button}}
</form>
```

```
//controller
actions: {
  signin(e) {
     e.preventDefault();
     //logic goes here
  }
}
```     
@miguelcobain @DanChadwick Thanks
