### ISSUE TITLE
Spinner Broken on First Spin

### ISSUE THREAD

**Issue by nahtnam** [miguelcobain/ember-paper#345]
Hey!

The spinner is broken during the first spin. As you can see in this [video](https://streamable.com/7e28), the spinner is fragmented at first, and then fixes itself during the next spin.

Thanks.

**Comment by DanChadwick** [comment]
I think this is a frame-rate-related browser issue. I don't see it on my system. (I used FireFox Windows on a moderate-speed laptop). Can you try it elsewhere or with other browsers? Also, making the window narrow so that fewer spinners are visible may make them run smoother.

**Comment by miguelcobain** [comment]
Does this also happen in angular material?

**Comment by nahtnam** [comment]
@DanChadwick You're right. This issue only shows up on Chrome, works fine in Firefox. Making the window smaller on Chrome doesn't help. I'm on a pretty beefy laptop so I don't think its an issue with lack of resources.

@miguelcobain This issue doesn't show up on Angular Material's page.

**Comment by DanChadwick** [comment]
I do not see this on Windows with Chrome. I'm wondering if its a GPU issue? Maybe try turning off "Use hardware acceleration when available"?

**Comment by nahtnam** [comment]
@DanChadwick I already have hardware acceleration disabled.

**Comment by DanChadwick** [comment]
I spent some time looking at this. First, I see some defects in the Angular demo that I also see in ember-paper. In the dummy app, the large deterministic circular spinners is slightly clipped on the left. It also shows a 1 pixel remnant at 6 o'clock after the first spin. ember-paper shows this even on the first spin.

In looking at the code, it is not clear to me that even the angular code is working as indented. In the current head, they have abandoned the idea of spinning a half-circle and directly animate an svg.

I don't think there is much return on trying to fix this in ember-paper. At some point, we might port the new Angular implementation.

Angular does not seem to be animating the "gap" as their code implies. I don't see it in the debugger in any case, whereas I do see the left and right halves being animated.

With your consent, I'd like to close this issue with the "won't fix" tag -- meaning that is broken but not worth addressing. Of course, if someone feels differently and wants to tackle this, please do open a PR with a solution! Or reopen this issue to continue the discussion.

**Comment by miguelcobain** [comment]
Agreed. They're using SVG in the recent versions. It probably isn't worth to try to fix a thing that won't be used at some point.
