### ISSUE TITLE
Drawer doesn't close

### ISSUE THREAD

**Issue by nightexcessive** [miguelcobain/ember-paper#35]
On mobile, the navigation drawer doesn't close itself when a link is clicked.

This can be observed by going to the demo site on a mobile device (or using Chrome's device emulation) and opening the drawer and selecting one of the nav options.

**Comment by miguelcobain** [comment]
Correct. I'm refectoring sidenav.
Hope it will land on master along with the flex grid.

**Comment by miguelcobain** [comment]
Well, after the sidenav refactoring, this still isn't a problem.

Any ideas to fix this?
We can't just close the sidenav on any click, right?
What would be a good *rationale* for the sidenav closing? A manual call? Route change?

**Comment by jerel** [comment]
Personally I think animating out at the beginning of a route change would be a good default but in some situations (can't think of any) the drawer might need to stay open until closed manually. I don't see that the spec gives any direction on it unfortunately...

**Comment by miguelcobain** [comment]
This why I love Ember.
So much beauty in this solution.

When you think that components/views just need to represent the state of a controller, everything is easier.

**Comment by rsaccon** [comment]
l have a use case where you don't want to close the drawer at all: when an item it not a link but contains sub items, and a click on it is to expand / collapse the sub items. But I think with this approach (or at worst with a slight modification - I have not tried), it is also possible to keep the drawer open if the route does not change

**Comment by miguelcobain** [comment]
This approach basically delegates the drawer closing to the application. Just ser open to false or true, whenever you need it.
In the demo app I used The willTransition hook. You don't need to do it in your use case.
I find this very flexible. Very elegant. Very Ember.
