### ISSUE TITLE
thoughts on using ember-power-select

### ISSUE THREAD

**Issue by jamesdixon** [miguelcobain/ember-paper#351]
Just throwing out the idea of utilizing [ember-power-select](http://www.ember-power-select.com/) as the default select component for EP. 

Given the amount of effort that it takes to develop a cross-platform select component as evidenced by @cibernox's work, I wonder if it would be prudent to not re-invent the wheel and see if it's feasible to extend EPS to make it "material-compatible." 

Pros:

- Many more features than paper-select, which undoubtedly will come in handy
- Benefit from the crazy amount of work/testing/feedback that is going on with EPS
- Avoids re-inventing the wheel for one of the more complex components that need to be dealt with

Cons:
- Another external dependency
- Not integrated directly into EPS
- Making it "material" may be more difficult than I'm aware of

Obviously, this list isn't exhaustive, but figured it would be good to open up the discussion.

**Comment by DanChadwick** [comment]
I've been wondering about this myself. The challenge is making the markup match Angular. It would seem that maybe we won't know if it is a good idea until someone tries it.

**Comment by jamesdixon** [comment]
I agree. I wonder if @cibernox might be able to chime in on the theming aspect. I realize with material there's a lot going on with animation, etc. Admittedly, I don't know the internals well enough to speculate.

**Comment by jamesdixon** [comment]
Looks like experimental CSS animation support was added fairly recently: http://www.ember-power-select.com/cookbook/css-animations, which may make things easier.

**Comment by cibernox** [comment]
I will give some insight about styling.

Changing the markup of the component would be relatively complex. Not sure that markup changes would be requires. 
Style the component using just CSS or SASS should be pretty easy.

**Comment by DanChadwick** [comment]
The `ember-paper` constraint is that we use the Angular Material stylesheets directly, without modification. This implies that we match the angular markup, at least in so far as it relates to CSS.

**Comment by cah-danmonroe** [comment]
Just want to add a thumbs up vote for trying to implement EPS.

**Comment by cibernox** [comment]
@DanChadwick The markup of EPS can be customized almost entirely, since all components can be replaced. But sounds involved.

Where can I see the markup expected by angular's stylesheets?

**Comment by DanChadwick** [comment]
There is an existing implementation of `{{paper-select}}`, which probably needs some work to bring it up to date: http://miguelcobain.github.io/ember-paper/master/#/select

And here's a link to the source Angular Material demo: https://material.angularjs.org/latest/demo/select

And the AM API reference: https://material.angularjs.org/latest/api/directive/mdSelect

**Comment by cibernox** [comment]
I'll be out on holidays until then 3rd of April, but I'll investigate after 👍

**Comment by DanChadwick** [comment]
11+ month vacation!! Congratulations! :stuck_out_tongue_winking_eye:

**Comment by cibernox** [comment]
lolololol I wish!

**Comment by Luiz-N** [comment]
I believe this has been merged in (#431) into the latest branch however the ember paper demo page for it does not seem to work as smoothly as the [e-p-s one](http://www.ember-power-select.com/cookbook/material-theme). Is the ember paper demo site using it?

**Comment by miguelcobain** [comment]
It is using it now.
Keep and mind that it is using ember-power-select *not* ember-power-select's material theme.
We're using material styles from angular material.

Do you see any noticeable difference between angular material and ember-paper?
Also, what do you mean by "it does not seem to work as smoothly as the e-p-s one"?

**Comment by Luiz-N** [comment]
well the biggest issue I see is the select search example on paper does not seem to work when a vegetable is clicked. Also, this might be more of a stylistic thing but the dropdowns on the official [eps site](http://www.ember-power-select.com/cookbook/material-theme) stay below the selected area when clicked while the paper examples cover it up.

**Comment by miguelcobain** [comment]
> well the biggest issue I see is the select search example on paper does not seem to work when a vegetable is clicked.

You're correct. That's a bug in the documentation. Angular Material 1.0.6 styles doesn't support multiple selects.
Those could be backported and fixed.

> Also, this might be more of a stylistic thing but the dropdowns on the official eps site stay below the selected area when clicked while the paper examples cover it up.

The reason is that e-p-s material thing doesn't follow the material design spec.
The spec requires the menu to be placed above the trigger and if selected, the selected option must be centered. So, we could say that e-p-s theme is "material inspired", but not theoretically "material".

The best way to detect a bug would be to compare this with the Angular Material versions of the components.

I'm closing this for now, but feel free to comment.
