### ISSUE TITLE
md-accent color doesn't work

### ISSUE THREAD

**Issue by mellatone** [miguelcobain/ember-paper#352]
See http://stackoverflow.com/questions/27856849/missing-md-accent-css-class-in-angular-material-design-css-file

**Comment by DanChadwick** [comment]
So confuzzled. Since we are using AM 1.0.6, how does this relate to us and what needs doing?

**Comment by mellatone** [comment]
So only the `AM 0.6` release has this issue. I feel like the resolution would be to bump the `AM` version that we're supporting, unless a fix was back ported? I don't have enough information yet. I just know that `md-accent` is not working properly:

![image](https://cloud.githubusercontent.com/assets/3988782/14923407/fdd497ae-0df1-11e6-8cc8-776a1a696bc7.png)

**Comment by DanChadwick** [comment]
@mellatone The bug is in 0.0.6. We are using 1.0.6. Off by 1.0.0 error. :)

**Comment by mellatone** [comment]
Updated the title. ^ That is still _a_ bug that we're experiencing. Has anyone else run into this?

**Comment by gnazarkin** [comment]
@mellatone having this problem

**Comment by miguelcobain** [comment]
This should be fixed since we're on the latest Angular Material version styles now.
