### ISSUE TITLE
Slack mentions get lost in the history

### ISSUE THREAD

**Issue by mellatone** [miguelcobain/ember-paper#355]
I feel like we should all start opening GitHub issues if something isn't sufficiently addressed by a Slack conversation so we can make sure improvements and ideas don't slip through the cracks. Perhaps an RFC prefix could help.

**Comment by DanChadwick** [comment]
Good idea. Now when exactly do we close this issue?

Seriously tho. :+1: . Sometimes slack discussions don't reach a conclusion and an issue keep us from forgetting tasks.
