### ISSUE TITLE
How do I use the new icons on the current master?

### ISSUE THREAD

**Issue by lefteyecc-pu** [miguelcobain/ember-paper#356]
Hello Everyone,

I've been using ember-paper for my project and am happy to see the switch to follow Angular Material.

I have one question, how do I use the new icons. Do i need to import extra CSS in app.scss? Currently my icons are not showing up, only the name of the icons are.

**Comment by DanChadwick** [comment]
This happens when your browser can't load the google font containing the icons. Could be a connection issue, CSP issue, or some other issue. Check your browser's error log. Please re-open or  if you need more help. Also, join us on slack `#e-paper` if you'd like!

**Comment by lefteyecc-pu** [comment]
Hello Dan,

I don't see any CSP errors. What are the URLs that need to be enabled in CSP policy in ember-cli for this to work properly?

**Comment by DanChadwick** [comment]
The readme.md has the CSP, but if CSP is the problem, I would expect an error. Otherwise, I'm guessing some other connectivity error.

If you are using the slack app, there is a "Quick Switcher" which has a icon that looks like a magnifying glass in from of a menu. Search for #e-paper`. Once you are in the channel, you can star it for future access convenience.

**Comment by lefteyecc-pu** [comment]
Ok thank you very much,.

**Comment by lefteyecc-pu** [comment]
Hmm. Must be me but I have the CSP values in my environment.js file. I don't see any requests to google font APIs.

Do I need to do any imports in app.scss?

**Comment by DanChadwick** [comment]
No. It's added in index.js (using master branch):
```
  contentFor: function(type) {
    if (type === 'head') {
      return '<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700,400italic">' +
        '<link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">';
    }
  },
```

**Comment by lefteyecc-pu** [comment]
Hi Dan

Thank you. That solves my problem. I'm serving the application in a
different manner from how the standard app is built. As such inhave to
manually update such additions to the custom index HTML file I'm using. I'm
building with watch and outputting to a different directory. I'll have to
fix that.

Thank you very much for the patience and responses!
