### ISSUE TITLE
How pass two arguments to an action of paper-button?

### ISSUE THREAD

**Issue by villander** [miguelcobain/ember-paper#357]
Its not working for me

`{{#paper-button raised=true primary=true (action "goToEditAnimal" 'animals.index' animal)}}Edit{{/paper-button}}`

**Comment by DanChadwick** [comment]
I'm assuming you're using master? The action isn't a positional parameter. You need `onClick=(action "goToPlatypus" ...)`. Plus unless you mean to pass the string `"animals.index"`, you need to omit the quotes.

**Comment by villander** [comment]
You not solved my problem, how pass two parameters to a action in `paper-button`?

**Comment by DanChadwick** [comment]
Using the latest master branch, not the release `0.2.x` version, use:
`{{#paper-button raised=true primary=true onClick=(action "goToEditAnimal" 'animals.index' animal)}}Edit{{/paper-button}}`

This will pass to action `goToEditAnimal`, a parameter of a string `"animals.index"` and a bound variable `animal`.

**Comment by bgohsman** [comment]
I was not able to get `onClick` to work with `0.2.x` (specifically `0.2.14`). However, this did:
`{{#paper-button action=(action "itemSelected" "item name")}}`

**Comment by miguelcobain** [comment]
@bgohsman that's correct. `action` was the name in 0.2.x.
Action names were renamed to make APIs more similar.
