### ISSUE TITLE
components should live under app instead of addon

### ISSUE THREAD

**Issue by SirZach** [miguelcobain/ember-paper#36]
I wanted to add some actions to the paper-item component. I first tried <code>{{#paper-item action="someAction"}}</code> but quickly realized this wasn't going to work since I need that action to pass some parameters as well. (BTW, if there's a better way to set up action handlers on components, I would love to know). I went to extend the <code>paper-item</code> component but the components live under <code>ember-paper/addon</code> instead of <code>ember-paper/app</code>. This prevents people from being able to import the ember-paper components in their own app and extend them.

**Comment by miguelcobain** [comment]
All the components on this addon are also under `app/`.
Are you sure about this?

**Comment by green-arrow** [comment]
@miguelcobain is correct. I can see the `paper-item` component under the `app/components` directory.

Additionally, @SirZach, you can also import components / helpers / etc from an ember addon by importing using the addon's full namespace. For example, in your app you could do:

`app/components/custom-ember-paper`:

```javascript
import PaperItem from 'ember-paper/components/paper-item';

export default PaperItem.extend({
  // Custom component additions
});
```

**Comment by SirZach** [comment]
@miguelcobain I'm sorry you are correct. 

I was an idiot and started the component with {{#paper-item-card}} and tried to close it with {{/paper-item}}. I'll stop submitting bugs until I try the next day with a fresh set of eyes. Thanks and thank you @green-arrow

**Comment by miguelcobain** [comment]
Don't worry. Glad you solved this. :)
If you fins aomething

**Comment by miguelcobain** [comment]
@SirZach 

After thinking a bit about this, I think `paper-item` should handle clicks.
Since 0635b757534278c2344ec66fede5a4f94102efac you can now do things like:

```handlebars
{{#paper-item action="someAction" param=item}}
  {{item.name}}
{{/paper-item}}
```

Clicking this will trigger an action named `someAction` with `item` as a parameter.

**Comment by SirZach** [comment]
@miguelcobain 

That's the exact functionality I added to my extended version of <code>paper-item</code> so I'm happy to see that be part of the component. Thanks!
