### ISSUE TITLE
Allow kebab-cased icons (1.0)

### ISSUE THREAD

**Issue by joukevandermaas** [miguelcobain/ember-paper#369]
Currently the master/1.0 branch only allows underscored icon names:

```hbs
{{paper-icon 'all_out'}}
```

However, in released (0.2) ember paper, people are used to kebab cased/dasherized icon names:

```hbs
{{paper-icon 'all-out'}}
```

I propose the master/1.0 version also supports dashes, and just converts them to underscores using [Ember's `underscore` function](http://emberjs.com/api/classes/Ember.String.html#method_underscore). We should keep the benefits of ligatures, while allowing an easier upgrade path.

To be clear, this means underscore (`all_out`), spaces (`all out`), dashes (`all-out`) and even camel cased (`allOut`) will all render the ligature `all_out`. This should be a completely backwards compatible change.

**Comment by DanChadwick** [comment]
this is going to be a pretty small portion of the upgrade work and it seems a shame to add complexity when a global find would let a developer convert a typical app in a few minutes. How about an assert instead?

**Comment by joukevandermaas** [comment]
IMO making the migration easier and friendlier should be an important goal. It feels like the change from dashes to underscores is arbitrary (even if it isn't). Maybe a find-all will indicate all the occurrences, but there are few developers (in my experience) who could actually write the global find/replace regex to fix them all.

Besides, there is a very low cost (or complexity) to supporting both, because Ember already provides a function for converting the strings. I think the benefits more than outweigh the (tiny) costs.

**Comment by miguelcobain** [comment]
@DanChadwick I'd also like to support dasherized names. It aligns better with everything else (we don't have underscores anywhere).

Also, I **hope** they'll make this change on material icons upstream. Makes so much sense to use the same name as in the classes.
Also, please +1 this issue: https://github.com/google/material-design-icons/issues/184
:P

**Comment by miguelcobain** [comment]
From slack:
This should be implemented as an `underscore` helper, so that the value is cached and we don't incur in a big performance penalty.
