### ISSUE TITLE
change prefix to md-

### ISSUE THREAD

**Issue by miguelcobain** [miguelcobain/ember-paper#37]
@fouad 
> This is just nitpicking, but thoughts on changing prefix to md- like {{md-button}} so that it's more like http://material.angularjs.org. Also it's faster to type.

The `paper-` prefix idea came from polymer. I'm open to change to a more "standardish" `md-` prefix.
Also, would play along better with our current classes and tagnames.

Nevertheless, I would like to hear users' input on this.

**Comment by green-arrow** [comment]
+1 for a `md-` prefix.

**Comment by fouad** [comment]
I think it'd also make sense to rename repo/bower package to `ember-material` for compatibility.

**Comment by chenxsan** [comment]
I would prefer the `paper-` prefix, guess `md` stands for **material design** and is used as a namespace, but sometimes you would find usages like `col-md-10` in Bootstrap grid, it means `medium`. It would cause a little confuse using `md-` as a prefix, at least the first time i saw `md`, i took it for granted as a abbr of `medium`.

**Comment by miguelcobain** [comment]
Interesting point.

**Comment by green-arrow** [comment]
I didn't even think of the Bootstrap grid thing. Even if it's not `md-` for the prefix, I would prefer something shorter than `paper-`.

**Comment by miguelcobain** [comment]
Maybe this is crazy, but what if we have a default component prefix but allow that to be customizable?
Perhaps not easy to accomplish, but certainly desirable.

How difficult could this be to implement? @stefanpenner

**Comment by fouad** [comment]
I like the flexibility, but I think convention over customization is the way to go. Most of the other frameworks' implementations are "material" (e.g. [react](https://github.com/callemall/material-ui) or [angular](https://github.com/angular/material)).

**Comment by miguelcobain** [comment]
@fouad Is the name of the project that important?
I was talking just about the prefix of the components.

**Comment by stefanpenner** [comment]
> How difficult could this be to implement? @stefanpenner

A user can subclass the resolver and have it re-write `paper-` -> `md-`. We do not currently expose this easily to plugin authors, but maybe some future `alias` feature would be nice.

**Comment by hhff** [comment]
perhaps with @lukemelia's component helper Ember PR we could do this

**Comment by hhff** [comment]
FWIW i think it would be detrimental to have the prefix be dynamic...

I think it should be standard, as it means if people write plugins or sass themes for Ember Paper, they are drop-in-able rather than drop-in-able-and-find-all-and-replace-able

**Comment by stefanpenner** [comment]
> FWIW i think it would be detrimental to have the prefix be dynamic...

Yes, agreed. Pick one name `md` and mitigate the confusion of two.

**Comment by miguelcobain** [comment]
That makes sense.
So `paper-`, `material-` or `md-`?

`md` feels more "standard" than `paper` and not so long as `material`.

**Comment by stefanpenner** [comment]
I like paper but md is shorter. Ultimately I use auto complete so both are likely the same keystrokes for me :p
