### ISSUE TITLE
add link buttons

### ISSUE THREAD

**Issue by miguelcobain** [miguelcobain/ember-paper#371]
It should be trivial to add link support to buttons right now.

Example: https://ember-twiddle.com/#/6265da0fd9a1252423b383d3e33ddaf3?openFiles=components.my-component.js%2Ctemplates.components.my-component.hbs

**Comment by joukevandermaas** [comment]
Also see #207 for a somewhat related discussion.

**Comment by miguelcobain** [comment]
To cover link-to functionality we're using https://github.com/peec/ember-transition-helper
Is that acceptable for the recommended solution?

**Comment by DanChadwick** [comment]
I'm confused. Your button-turned-into-an-a-link component looks like an `a` link. I was under the impression that the only way to make a browser actually process an href was inside an `a` link, and with AM CSS, a links don't look anything like buttons. Are you suggesting that we add a bunch of e-p specific CSS to accomplish this?

**Comment by miguelcobain** [comment]
@DanChadwick AM does have link buttons (buttons with an anchor tag): https://material.angularjs.org/1.0.6/demo/button

Turns out the styles are also appliead to `a` tags.

**Comment by DanChadwick** [comment]
Closed in favor of discussion in PR #372
