### ISSUE TITLE
buggy progress linear - buffer and query mode

### ISSUE THREAD

**Issue by miguelcobain** [miguelcobain/ember-paper#377]
something is wrong on buffer and query mode progress linears:
http://miguelcobain.github.io/ember-paper/release-1/#/demo/progress-linear
vs
https://material.angularjs.org/1.0.6/demo/progressLinear

query mode eventually stops moving.
- [x] fix query mode
- [ ] fix buffer mode

**Comment by patrickberkeley** [comment]
@miguelcobain I've looked into the query mode progress bar issue a bit. Here's a PR to fix it:

https://github.com/miguelcobain/ember-paper/pull/391

**Comment by miguelcobain** [comment]
@patrickberkeley Thanks a lot! Nice find.

Buffer mode is still crazy.
