### ISSUE TITLE
CustomValidations with i18n translations

### ISSUE THREAD

**Issue by szsoppa** [miguelcobain/ember-paper#383]
Is there any way to connect translations with input `customValidations` in v1.0.0 ?

**Comment by miguelcobain** [comment]
@szsoppa I don't know which i18n library you're using, but I assume you can do that easily.

Here is an example of customizing the message using custom validations: https://github.com/miguelcobain/ember-paper/blob/master/tests/integration/components/paper-input-test.js#L307-L325

**Comment by szsoppa** [comment]
Thanks, I think it might help ;)
