### ISSUE TITLE
Cannot install alpha 1.0 version via cli.

### ISSUE THREAD

**Issue by v3ss0n** [miguelcobain/ember-paper#385]
```ember install ember-paper@1.0.0-alpha.1```
version not found: ember-paper@1.0.0-alpha.1

**Comment by v3ss0n** [comment]
npm ERR! Valid install targets:
npm ERR! 0.2.14, 0.2.13, 0.2.12, 0.2.11, 0.2.10, 0.2.9, 0.2.8, 0.2.7, 0.2.6, 0.2.5, 0.2.4, 0.2.3, 0.2.2, 0.2.1, 0.2.0, 0.1.3, 0.1.2, 0.1.1, 0.1.0, 0.0.21, 0.0.20, 0.0.19, 0.0.18, 0.0.17, 0.0.16, 0.0.15, 0.0.13, 0.0.12, 0.0.11, 0.0.10, 0.0.9, 0.0.8, 0.0.7, 0.0.6, 0.0.5, 0.0.4, 0.0.3, 0.0.2

**Comment by v3ss0n** [comment]
how to install lastest master?

**Comment by miguelcobain** [comment]
@v3ss0n `ember install miguelcobain/ember-paper`

**Comment by v3ss0n** [comment]
installing and testing now.

**Comment by DanChadwick** [comment]
The alpha version(s) have not been pushed to npm, hence the need to install them from github. See http://miguelcobain.github.io/ember-paper

Please re-open if you have further installation trouble.
