### ISSUE TITLE
paper-select and paper-menu leave html comment debris upon each use

### ISSUE THREAD

**Issue by DanChadwick** [miguelcobain/ember-paper#387]
Each time the select or menu is closed, another `<!---->` left behind in the DOM. Tested in 1.0.0-alpha.1.

**Comment by joukevandermaas** [comment]
Isn't this just Ember's rendering engine? I'm pretty sure this also happens with e.g. `{{#if`.

**Comment by miguelcobain** [comment]
@joukevandermaas the problem here is that every time a select is opened or closed a new `<!-- -->` is added.

**Comment by miguelcobain** [comment]
Don't know exactly why, but this doesn't happen anymore on master.
