### ISSUE TITLE
paper-autocomplete suggestion list is not visible

### ISSUE THREAD

**Issue by szsoppa** [miguelcobain/ember-paper#388]
After switching stable release to newest 1.0.0-alpha.1 my autocomplete suggestion list appends and show itself at the end of body tag which makes it totally unuseful.

**Comment by DanChadwick** [comment]
Can you elaborate about why this would is an issue for your use case?

The autocomplete component is "scheduled" to be refactored using paper-wormhole, which would effectively do the same thing. In what way is the location of the list in the DOM "unuseful"? Locating elements which need to be on top of everything else at the root of the DOM avoid issues where the parent's styling can interfere with the topmost element. This is how menus and dialogs work.

See paper-autocomplete-list.js:didInsertElement() for the relevant code.

Note that there is a partially-complete PR for porting this component to v1.0.

**Comment by szsoppa** [comment]
I think I defined my problem in wrong way. The problem is that autocomplete suggestion list positions itself at the bottom of page. Under my autocomplete input there are some category cards. Suggestion list should be attached to the bottom of autocomplete input but it appears under category cards instead. Because of that user is not able to see suggestion list until he scrolls page down. This is why it's unuseful.

**Comment by DanChadwick** [comment]
Ah, I understand now. Yes, it seems that the pop-up list in v1.0.0-alpha.1 is broken. I suspect the problem is that the styling that was relying on isn't present because we are now using the angular material styles. There is a PR to port autocomplete. You could try that as a starting point or contribute by porting autocomplete yourself to 1.0.

**Comment by brendanoh** [comment]
I am migrating an app to v1 alpha 3. Am I to understand that Autocomplete is totally unusable in the current state?

Because currently none of the autocompletes work in my app and in fact the demo page autocompletes dont seem to work. At least not the way the old versions worked.

Or am I missing something?

**Comment by brendanoh** [comment]
OK I am now looking at https://github.com/miguelcobain/ember-paper/pull/395 so I think I understand.

**Comment by xomaczar** [comment]
Paper-menu branch fixes all the issues mentioned here. Please close

**Comment by xomaczar** [comment]
Can this issue be closed?

**Comment by PriyangaSG** [comment]
This issue still exists in version 1.0.0-beta.3

**Comment by UserXXXX** [comment]
This issue still exists in version 1.0.0-beta.3

**Comment by xomaczar** [comment]
Can you elaborate?

**Comment by UserXXXX** [comment]
The suggestion list position (md-virtual-repeat-container) is not fixed to the bottom of the autocomplete input, as I continued to use paper-autocomplete multiple times down the page. you can see the behaviour in the below gif. 

![auto complete issue](https://user-images.githubusercontent.com/32663196/31429786-952adcc6-ae8c-11e7-8b3c-b502624622e1.gif)

**Comment by xomaczar** [comment]
Thanks - looks definitely like a bug. Can you create a github repo where we could reproduce this bug?

**Comment by UserXXXX** [comment]
Sure and thank you for your quick response.

**Comment by xomaczar** [comment]
Sure - Can you create a github repo where we could reproduce this bug?

**Comment by tobiasWenger** [comment]
I have a similar problem. If I have to scroll to the autocomplete field the list is not visible. I created a mwp and even some margin on the parent object results in the list being out of alignment.

[github repo](https://github.com/tobiasWenger/autocomplete-bug)

**Comment by robabby** [comment]
Any status updates or inputs on this issue?  I am faced with having to refactor ember-paper Autocomplete out of our app and either hand-roll a solution with ember-basic-dropdown due to the same problem @UserXXXX shows with the GIF. 

Are there any available workarounds at the moment?

**Comment by xomaczar** [comment]
Yeah it has to do with incorrect positioning due to html/body position being `relative`.
The workaround:
```
html, body {
  position: static !important;
}
```

**Comment by xomaczar** [comment]
@robaby - can you verify

**Comment by xomaczar** [comment]
@robabby

**Comment by tpetrone** [comment]
The workaround solved for me. Thanks a lot!
