### ISSUE TITLE
new installs not finding blueprint? is this a bug?

### ISSUE THREAD

**Issue by paul42** [miguelcobain/ember-paper#399]
Not certain if this is even a bug or not, but I was testing it out on a new project and got this error message:

````
LMIT-PAUL:paper-test-side-nav paul$ ember install miguelcobain/ember-paper
Installed packages for tooling via npm.
WARNING: Could not figure out blueprint name from: "miguelcobain/ember-paper". Please install the addon blueprint via "ember generate <addon-name>" if necessary.
Installed addon package.
````
to recreate:
1.  ember new a new project
2. cd into project
3. run `ember install miguelcobain/ember-paper`

is that the correct install to use? it's the one listed on the demo site so i assume that's still correct. Is the blueprinting even a problem? I don't know enough about ember addons and this plugin to know if it even installs anything via blueprint

**Comment by paul42** [comment]
tried to reproduce - must've just been me, can't duplicate.

**Comment by espa77** [comment]
I am having this same issue.

**Comment by dustinfarris** [comment]
If you are installing from master you will need to generate the blueprint manually (for any addon)

```
ember g ember-paper
```

**Comment by DanChadwick** [comment]
Thanks to @SaladFork, ember-paper is now published on npm with version 1.0.0-alpha.1, rather than 0.2. This means that you can just `ember install ember-paper`, which should run the blueprint.

I'm going to close this issue in the hopes that this is resolved, but please do re-open if there is still a problem.

**Comment by espa77** [comment]
This worked - thanks!

**Comment by tsteuwer** [comment]
@dustinfarris Even running that generates: 

```
ember generate my-addon
installing my-addon
The `ember generate <entity-name>` command requires an entity name to be specified. For more details, use `ember help`.
```
