### ISSUE TITLE
Fastboot Support

### ISSUE THREAD

**Issue by mike1o1** [miguelcobain/ember-paper#401]
I did some quick testing for Fastboot support and found a few quick wins that need to be tackled to enable support. Any additional help testing is appreciated!

- [ ] Fix references to `window.matchMedia` in [paper-sidenav-inner](https://github.com/miguelcobain/ember-paper/blob/1bea72bafb81e86fb776ace25e46d18c2a2be4f4/addon/components/paper-sidenav-inner.js#L55)
- [ ] Fix `document` references in [services:sniffer](https://github.com/miguelcobain/ember-paper/blob/1bea72bafb81e86fb776ace25e46d18c2a2be4f4/app/services/sniffer.js#L19)

**Comment by dustinfarris** [comment]
sniffer is addressed in #353 along with several others.

**Comment by dustinfarris** [comment]
I think this can be closed thanks to #430 

/cc @miguelcobain
