### ISSUE TITLE
class="layout" vs attribute layout

### ISSUE THREAD

**Issue by givanse** [miguelcobain/ember-paper#402]
The docs here: http://miguelcobain.github.io/ember-paper/release-1/#/layout/layout-containers

Say: `<div class="layout-row">`
What works is: `<div layout="row">`

Can I have some context? Are versioned docs something that the project would like to have? Are you guys waiting to release 1.0.0 before updating the docs?

**Comment by DanChadwick** [comment]
That's the v1 doc. Are you using v1 or 0.2?  We have two linked docs because they are integrated with the related demos.

**Comment by givanse** [comment]
Didn't notice the version switch button!

Pretty sure the docs need some love, but I have to double check what combination of addon version and docs I was using.

**Comment by jamesdixon** [comment]
@DanChadwick the v1 docs still look out of date unless I'm missing something? All of the v1 docs are using classes rather than attributes.

**Comment by DanChadwick** [comment]
V1 uses classes rather than attributes, right?

**Comment by jamesdixon** [comment]
Not from what I'm seeing: https://material.angularjs.org/1.0.6/layout/container

These examples show the user of attributes rather than classes.

**Comment by DanChadwick** [comment]
Right. ember-paper uses classes tho.

**Comment by miguelcobain** [comment]
We decided to use classes in ember-paper because ember can't convert html attributes to classes.
Angular has a thing called attribute directives that allows that.

Converting attributes to classes has performance advantages and that's what angular does underneath, even if you use attributes.
Ember-paper still has attribute styles imported for now, but expect it to not do that in a near future.

**Comment by jamesdixon** [comment]
@miguelcobain thanks for the explanation. That missing piece of information was the source of my confusion 😄

**Comment by DanChadwick** [comment]
Fodder for the dummy app layout page, me thinks....

**Comment by DanChadwick** [comment]
I updated the dummy app's Layout Introduction page to help clarify that, but I didn't republish the dummy app (yet).
