### ISSUE TITLE
Can you make the repo for the marketing site public?

### ISSUE THREAD

**Issue by benbabics** [miguelcobain/ember-paper#407]
It'd be nice to see the layout of components used in the ember app for the marketing site (http://miguelcobain.github.io/ember-paper/release-1/). Is that possible?

**Comment by mike1o1** [comment]
It already is :)

https://github.com/miguelcobain/ember-paper/tree/master/tests/dummy

**Comment by DanChadwick** [comment]
Just build ember-paper as if it were an app. npm and bower install.
