### ISSUE TITLE
Fractional slider

### ISSUE THREAD

**Issue by djsegal** [miguelcobain/ember-paper#424]
Is there any way to do `0` to `1`, in like `10 steps` or `steps of 0.1`?

**Comment by miguelcobain** [comment]
have you tried `step=0.1`?

**Comment by djsegal** [comment]
@miguelcobain yes

this happens on master and `1.0.0-alpha.1`

**Comment by miguelcobain** [comment]
Sliders were refactored and now support fractional values.
