### ISSUE TITLE
paper-input `validationErrors` takes too long to compute (failing tests)

### ISSUE THREAD

**Issue by dustinfarris** [miguelcobain/ember-paper#427]
If i set `errors` on paper input, say from the result of a rejected save operation, i can't assert the presence of an error message in an acceptance test.

e.g. a test (where i've set up a server (mirage) to respond with a 422 because the email is already taken):

```js
test('email taken', function(assert) {
  visit('/register');
  fillIn('.email input', 'already@taken.com');
  fillIn('.password input', 'mynewpassword');
  click('.submit');
  
  andThen(() => {
    assert.equal(find('.email .paper-input-error').length, 1));
  });
});
```

the functionality works fine in development, but the test fails.  phantom always fails.  chrome fails maybe 75% of the time, then passes randomly.

**Comment by miguelcobain** [comment]
Can you simulate this with regular inputs and ifs?
Looks strange. The computed property is not doing anything special. Are you using custom validations?

**Comment by dustinfarris** [comment]
With regular inputs and ifs the test passes.  When using paper-input it fails.  Using ember-changeset-validations which do not do anything special, very light-weight library.

**Comment by dustinfarris** [comment]
This was a wild goose chase.

Turns out the culprit was `isTouched` not registering in Phantom.

Changing my test to this works:

```js
test('email taken', function(assert) {
  visit('/register');
  fillIn('.email input', 'already@taken.com');
  triggerEvent('.email input', 'blur');
  fillIn('.password input', 'mynewpassword');
  triggerEvent('.password input', 'blur');
  click('.submit');

  andThen(() => {
    assert.equal(find('.email .paper-input-error').length, 1));
  });
});
```

@miguelcobain please close if this is the proper way to write acceptance tests involving paper-input.

**Comment by miguelcobain** [comment]
Looks good to me. Triggering blur is what toggles isTouched. Otherwise no error messages will appear.

**Comment by dustinfarris** [comment]
@miguelcobain do you think a `paperFillIn` helper would be appropriate?  that does both the fillIn and the blur?  This was hard for me to figure out, and I'm thinking we should either document it or write a test helper or both.

**Comment by miguelcobain** [comment]
Looking again, I'm surprised the `click` doesn't automatically trigger blur on the focused input.
Focusing related stuff on tests has always been tricky.

I'm a bit reluctant to include a blur event trigger on a `paperFillIn` test helper, because you may not always want to trigger it.
e.g suppose I wanted to (re)test that the error messages don't show up until blur.

**Comment by dustinfarris** [comment]
@miguelcobain it does in Chrome, but not in PhantomJS.  It feels like a bug actually, but I'm not sure if it's an Ember bug or a Phantom bug or something else.

Agree that the helper might be assuming too much, but I think this should be documented somewhere.  Maybe this issue is enough.  isTouched isn't part of the public API and it also feels like assuming to much to think the user is aware of this part of material design spec _and_ that they have to jump through an extra hoop to make it work in Phantom.  or maybe that is an appropriate assumption.  what do you think?

**Comment by miguelcobain** [comment]
> isTouched isn't part of the public API
And it doesn't need to be.

IMO, we should explain in the docs that paper-input only shows errors if the control has been touched (a blur event).

**Comment by miguelcobain** [comment]
input docs need some cleanup.
