### ISSUE TITLE
sidenav width is set to fixed size on the element

### ISSUE THREAD

**Issue by mhretab** [miguelcobain/ember-paper#43]
I the [sidenav](https://github.com/miguelcobain/ember-paper/blob/f7e6cd692a55e34d115d952ea093cf5f9ccc850d/addon/styles/scss/paper-sidenav.scss#L1) I can see you set fix width to 304px on the element. Angular Material does not have that and also the material guideline states the sidenav should be 254px. I think that the default width has to be defined in css classes not in the md-sidenav element. Any thoughts?

**Comment by miguelcobain** [comment]
You're right. I've changed the default sidebar width in baa408377c20bb70e3f817cfb94e7024a01b7bd0. However, for changing to a custom width the ideal would be to override a sass variable. Right now ember-cli doesn't support sass through addons in a way that exposes sass to the consuming app.

Also, right now we need to know the width to do the drawer animation. So, you can just set the width in the md-sidenav element. It has to be there for this to work, anyway.
But there may be a better way to do this without knowing its width. I'm open for suggestions/PRs as always!

**Comment by mhretab** [comment]
Thanks for updating the default width. Having the width is ok and this works for me now since I just want default width to be 254px. I am aware that ember-cli doesn't support sass through addons. However, to override the [element style](https://github.com/miguelcobain/ember-paper/blob/master/addon/styles/scss/paper-sidenav.scss#L8-L22) I think that its better if it is on a class instead of the element itself. What do you think?

**Comment by miguelcobain** [comment]
I think it doesn't make a big difference.
What's the difference between targeting `md-sidenav` element or `paper-sidenav` class?

**Comment by mhretab** [comment]
In general it is recommended to put styles in classes than in an element for reusability purposes. For example, in the project I am working there are two sidebars and targeting an element would target both sidebars. Furthermore having to over ride `md-sidenav` element rather than `.paper-sidenav` makes the code a bit cleaner. whenever I see `md-sidenav` on my sass, it looks odd because it doesn't have `.` .

**Comment by hhff** [comment]
@mhretab - you should just add an extra classname to the single sidebar you want to target, then in your sass you can do:

```sass
md-sidenav {

  &.second-sidenav {
    // Second sidenav specific overrides
  }
}
```

Using sass to style tags is standard.  How do you style your `span` or `a` or `p` tags generically across project?

**Comment by miguelcobain** [comment]
Also, in the future the sidebar width will be in a sass variable.
Users could just change that variable.

Sidenav was one of the things that was not ported from Angular Material (i feel their implementation really isn't "compatible" with Ember).
However, it would be great to keep our styles consistent with theirs. Angular material styles elements extensively.
