### ISSUE TITLE
onChange Input field's cursor jumps to the end of data

### ISSUE THREAD

**Issue by tanelainla** [miguelcobain/ember-paper#432]
I set up a trial environment for ember-paper and run into an issue with input fields.
Whenever I change the content of the input field, cursor jumps to the end of the date.
This is some kind of a binding issue? I don't touch this variable in the controller.

I'm running **Ember 2.6.1** and latest **ember-paper 1.0.0-alpha.1**

Here's a random input filed I took from the examples:
`{{paper-input flex=30 label="Name" value=name onChange=(action (mut name))}}`

Otherwise templates runs well and I really like it.

**Comment by miguelcobain** [comment]
I thought this was fixed in ember 2.3.1. Will investigate.

**Comment by miguelcobain** [comment]
@tanelainla can you reproduce that problem here: http://miguelcobain.github.io/ember-paper/release-1/#/components/input ?

**Comment by miguelcobain** [comment]
@tanelainla I confirmed that happens on master.

**Comment by miguelcobain** [comment]
@tanelainla this was fixed and publish on version 1.0.0-alpha.2.

Can you try and confirm it is fixed?
Thanks for reporting!

**Comment by tanelainla** [comment]
All good now. Thanks!
