### ISSUE TITLE
Standard Padding

### ISSUE THREAD

**Issue by hhff** [miguelcobain/ember-paper#44]
Another SASS variable I'd like to flag is a "standard" distance parameter.  In material design, there's some nice padding here and there, and it would be great to be able to use this throughout - it's nice on the eyes to have a standard distance.

An example is on the sidebar menu:

![screen shot 2015-02-16 at 5 38 58 pm](https://cloud.githubusercontent.com/assets/2865404/6220305/e5066c5e-b602-11e4-8629-a56454044b1e.png)

It's 1x standard-padding from top, and 2x standard-padding from left

![screen shot 2015-02-16 at 5 39 23 pm](https://cloud.githubusercontent.com/assets/2865404/6220306/e796f89e-b602-11e4-8190-674dcca9fb23.png)

Thoughts?

**Comment by miguelcobain** [comment]
I think these paddings would be included in the component styles themselves.
Of course, they could use sass variables, and the consuming app could use those variables as well.
Right now our styles are pretty much the same as angular material's (with one or two component exceptions), so I don't know if we can extract that padding from it.

Maybe it's worth look, but maybe there are some overall bigger priorities on the project.

**Comment by DanChadwick** [comment]
I think this issue is obsoleted by the current use of the Angular Material stylesheets, which are directly imported and processed during the build process. Please reopen if you disagree or want to discuss further.
