### ISSUE TITLE
Resetting paper-input value without triggering validation

### ISSUE THREAD

**Issue by lucacorti** [miguelcobain/ember-paper#440]
Is it possible to reset a paper-input value after form submission without triggering validation?

You `set(this, inputVar, null)` on the input bound variable validation is triggered and error messages are show.

**Comment by miguelcobain** [comment]
@lucacorti check paper-input docs here http://miguelcobain.github.io/ember-paper/release-1/#/components/input

At the very bottom there's a paper-form component that helps you to reset your inputs on submit.

If you need help, there are many friendly people at #e-paper channel on ember's slack.

**Comment by lucacorti** [comment]
Sorry I was looking at the input docs. Thanks for the pointer 👍
