### ISSUE TITLE
Sidenav and others broken on iOS

### ISSUE THREAD

**Issue by dustinfarris** [miguelcobain/ember-paper#448]
On iPhone I can't close an open sidenav just by tapping away from it.

![img_2956](https://cloud.githubusercontent.com/assets/1087165/17054561/798e8e38-503a-11e6-92a5-f9f55982aae5.jpg)

---

Also, on the dummy site, things appear out of whack on an iPad mini:
#### Header is cut off

![img_0109](https://cloud.githubusercontent.com/assets/1087165/17054612/9a260a54-503a-11e6-8df2-a784a4503337.JPG)

---
#### Sidenav is broken:

![img_0110](https://cloud.githubusercontent.com/assets/1087165/17054593/935dbd7a-503a-11e6-9320-40c28745a26b.JPG)

---
#### In landscape menu button is missing:

![img_0111](https://cloud.githubusercontent.com/assets/1087165/17054636/b626ea98-503a-11e6-8690-213547fd502e.JPG)

**Comment by jlommori** [comment]
+1, I experienced the "tapping away to close" bug with my own app using sidenav. It persists across Safari and Chrome on iOS 9 as well as a Safari Web App. The links in the sidenav work and it does close when a link is selected.

**Comment by tmclouisluk** [comment]
seems paper does not support iOS 8 Safari

**Comment by miguelcobain** [comment]
I know how to fix the sidenav. If anyone has some time to test it and PR, please let me know,

**Comment by miguelcobain** [comment]
This should be fixed now.
