### ISSUE TITLE
Toolbar and sidenav not fixed position.

### ISSUE THREAD

**Issue by mhretab** [miguelcobain/ember-paper#45]
Hi, by default when adding `paper-toolbar` is not fixed position. The sidenav is also not fixed and scrolls when scrolling the main content. After it didn't work in my project, I tried a new fresh app and copied everything from ember-paper and still the same thing. Is this how it is supposed to be or am I missing something.

**Comment by miguelcobain** [comment]
Does that happen to you in the demo page?
What browser?

**Comment by mhretab** [comment]
It doesn't happen on the demo page and when I clone the repo it works fine on the dummy app. The problem exists only when I install ember-paper through npm or ember-addon.

**Comment by miguelcobain** [comment]
We still need to add the flex grid layout to the docs, but this should work:

```handlebars
<div layout="column" flex>
  {{#md-toolbar}}
     {{!-- toolbar content here --}}
  {{/md-toolbar}}
  {{#md-content}}
    {{!-- scrollable content here --}}
  {{/md-content}}
</div>
```

The parent div can also be a `md-content`:
```handlebars
{{#paper-content flex-layout="column" flex=true}}
  {{#md-toolbar}}
     {{!-- toolbar content here --}}
  {{/md-toolbar}}
  {{#md-content}}
    {{!-- scrollable content here --}}
  {{/md-content}}
{{/paper-content}}
```

`flex` on the parent is there because it is likely that you include the parent in another flex container.
Angular layout docs on this are really good: https://material.angularjs.org/#/layout/container

**Comment by mhretab** [comment]
unfortunately that is not working for me, I have them wrapped `{{#paper-content flex-layout="column" flex=true}}` you can check a test app I did by entirely copying the application.hbs from the dummy app [here](https://github.com/mhretab/paper-test/blob/master/app/templates/application.hbs).

**Comment by miguelcobain** [comment]
The only problem with your test app was the main container.
It must have 100% width and height. That is why I added the `ember-app` class to the application view in the dummy app.
After setting that, everything works fine. :)

**Comment by mhretab** [comment]
Ah.. it had 100% width and height but there was another div on top of it, which I did not notice. Thanks :)
