### ISSUE TITLE
May I have the source code of demo web application?

### ISSUE THREAD

**Issue by tmclouisluk** [miguelcobain/ember-paper#451]
Since there are many usages which the demo guide does not includes.
Just want to have a reference. Thanks

**Comment by DanChadwick** [comment]
Build the addon as if it were an app. See readme / resources.

**Comment by tmclouisluk** [comment]
[](http://miguelcobain.github.io/ember-paper;)

Can I build the addon in order to get the source code of the demo web application?

**Comment by miguelcobain** [comment]
@tmcloouisluk every ember-cli addon has a dummy app under `tests` folder. Just go there and check for yourself. :)

**Comment by elliot** [comment]
https://github.com/miguelcobain/ember-paper/tree/master/tests/dummy/app

**Comment by tmclouisluk** [comment]
I got it. Thanks you guys
