### ISSUE TITLE
All paper-input are not working

### ISSUE THREAD

**Issue by tmclouisluk** [miguelcobain/ember-paper#457]
`{{paper-input flex=true label="Submission date" type="date" value=date onChange=(action (mut date))}}`

When selected any two fields (eg. month or year), the selected date value will be clear automatically.

**Comment by tmclouisluk** [comment]
Seems all inputs are not working

**Comment by tmclouisluk** [comment]
```
{{#paper-content}}
{{paper-input flex=true label="Submission date" type="date" value=date onChange=null}}
{{paper-input flex=30 label="Name" value=name onChange=null}}
{{/paper-content}}
```

is it the onchange = null problem?

**Comment by miguelcobain** [comment]
@tmclouisluk what version are you using?

Do these inputs work for you?  http://miguelcobain.github.io/ember-paper/release-1/#/components/input

**Comment by tmclouisluk** [comment]
"ember-paper": "1.0.0-alpha.3" now
I just copy them and edit the onChange=null

**Comment by miguelcobain** [comment]
@tmclouisluk using `onChange=null` will make them seem that they don't work, indeed.
inputs need to have their `value` updated in order for them to update themselves.
