### ISSUE TITLE
Google font whitelist doesnt work

### ISSUE THREAD

**Issue by krzosik** [miguelcobain/ember-paper#458]
Hi, I'm trying to have a google fonts in my ember paper components, but when I add ContentSecurityPolicy like in readme nothing is change. What should I do in that case?

**Comment by joukevandermaas** [comment]
That `ContentSecurityPolicy` line is only needed if you have the [`ember-cli-content-security-policy`](https://github.com/rwjblue/ember-cli-content-security-policy) addon installed. If that's not in your `package.json`, it will work automatically.

This addon used to be a default addon, so if you just now generated a new project using Ember CLI, you should already see the google fonts.

**Comment by krzosik** [comment]
I have content security addon, so its strange that these lines does not work.

**Comment by miguelcobain** [comment]
@krzosik please be a bit more clear. What is wrong in your app? You don't see the correct fonts? You get CSP errors?

**Comment by krzosik** [comment]
The font is not as it should be. As you can se on screenshot below with ember-paper buttons in my app (three top buttons) and buttons from new instance of ember cli project. My project doesn't has content secutiry like I said before by mistake. So my goal is to have in my app buttons and other components with correct font.

![bez tytulu](https://cloud.githubusercontent.com/assets/20403201/17218324/a541ce58-54e7-11e6-8204-0ebc4ae2faf6.png)

**Comment by miguelcobain** [comment]
Problem solved?

**Comment by krzosik** [comment]
Still not, but i'm not working with this project anymore. I only discovered that this problem was because of bootstrap (?). When I deleted bootstrap from app, the font was correct.
