### ISSUE TITLE
paper-select changes value twice

### ISSUE THREAD

**Issue by jpaas** [miguelcobain/ember-paper#462]
In 1.0.0.alpha3 when an item is selected from an item-select, the value is changed twice. First it's set to null, then it's changed to the selected value.

If the select is used for something like a filter on a list, this causes problems like 2 ajax calls to update the table. These 2 ajax calls cause a race condition where the longest one to complete will win.

**Comment by miguelcobain** [comment]
Please reopen if bug is still present on latest release.
We're now basing our implementation in ember-power-select.
