### ISSUE TITLE
paper-progress throwing error

### ISSUE THREAD

**Issue by batlefield** [miguelcobain/ember-paper#467]
When I try to use paper-progress-circular or linear as indeterminate one it crashes with error:
ember.debug.js:2314 Uncaught Error: Attempting to inject an unknown injection: `service:fastboot`

Should I install fastboot or something? I couldn't find anything about it anywhere on git or on demo page.

**Comment by miguelcobain** [comment]
You may not have the most recent ember-paper version. Please confirm. We fixed something related in one of the last releases.

**Comment by batlefield** [comment]
Thank you for the tip, I didn't have the latest version, it was alpha .
