### ISSUE TITLE
paper-sidenav: when clicking the menu button so fast, the menu will always show open without backdrop

### ISSUE THREAD

**Issue by tmclouisluk** [miguelcobain/ember-paper#471]
Even the demo page of paper
when you clicking the menu button in a fast speed
the sidenav will not be closed and always show open with no backdrop

**Comment by tmclouisluk** [comment]
seems paper-sidenav-inner click() function problem

**Comment by tmclouisluk** [comment]
the other way to trigger this bug:
click: menu->backdrop->menu->backdrop->menu->backdrop->menu->backdrop...
many times. Then it comes the same result.

Browser: chrome 52.0.2743.116 m (64-bit)

**Comment by miguelcobain** [comment]
I think using my updated fork of ember-css-transitions will solve these kind of problems.

**Comment by tmclouisluk** [comment]
it doesn't work. The menu now is always open and cannot close :(

**Comment by miguelcobain** [comment]
It is working fine here.

**Comment by tmclouisluk** [comment]
When i dont use ember-css-transitions, then it works :8ball: 
`classNameBindings: ['positionClass','isLockedOpen:md-locked-open', 'closed:md-closed'],`

**Comment by miguelcobain** [comment]
Like that it shouldn't have animations.

**Comment by miguelcobain** [comment]
This should be fixed in latest master after ember-css-transitions update to 0.1.5.
