### ISSUE TITLE
paper-card layout broken in ie 11

### ISSUE THREAD

**Issue by tmclouisluk** [miguelcobain/ember-paper#473]
![s](https://cloud.githubusercontent.com/assets/18186155/17993777/67faecbe-6b85-11e6-997f-4e26ec38ef18.png)

as the photo shown, it's not smoothly when scrolling too

**Comment by miguelcobain** [comment]
Can you test angular material cards in ie11. Do they work?

**Comment by tmclouisluk** [comment]
they work fine in https://material.angularjs.org/latest/demo/card

**Comment by miguelcobain** [comment]
@tmclouisluk can you please do some debugging here? What is different between both?

**Comment by tmclouisluk** [comment]
https://material.angularjs.org/latest/demo/card
this is using angular 1.10 version. It seems workable in ie 11.
By the way
https://material.angularjs.org/1.0.6/demo/card
in 1.0.6, it's not workable.

I guess the problem is angular material 1.0.6 does not support ie 11.

**Comment by tmclouisluk** [comment]
I suggest that should upgrade angular material from 1.0.6 to 1.10
in order to let all the ui becoming workable in ie 11 or safari(seems some not workable too)

**Comment by tmclouisluk** [comment]
I try to upgrade the angular material.
However, some problem here.

```
WARNING: Unknown `default` in $colors. `grey`
Backtrace:
        tmp/sass_compiler-input_base_path-AHJwc26U.tmp/0/app/styles/color-palett
e.scss:464, in function `color`
        tmp/sass_compiler-input_base_path-AHJwc26U.tmp/0/app/styles/angular-mate
rial/components/content/content-theme.scss:3

WARNING: Unknown `default` in $colors. `grey`
Backtrace:
        tmp/sass_compiler-input_base_path-AHJwc26U.tmp/0/app/styles/color-palett
e.scss:464, in function `color`
        tmp/sass_compiler-input_base_path-AHJwc26U.tmp/0/app/styles/angular-mate
rial/components/card/card-theme.scss:5

WARNING: Unknown `default` in $colors. `grey`
Backtrace:
        tmp/sass_compiler-input_base_path-AHJwc26U.tmp/0/app/styles/color-palett
e.scss:464, in function `color`
        tmp/sass_compiler-input_base_path-AHJwc26U.tmp/0/app/styles/angular-mate
rial/components/subheader/subheader-theme.scss:3

WARNING: Unknown `hue` in $colors. `grey`
Backtrace:
        tmp/sass_compiler-input_base_path-AHJwc26U.tmp/0/app/styles/color-palett
e.scss:464, in function `color`
        tmp/sass_compiler-input_base_path-AHJwc26U.tmp/0/app/styles/angular-mate
rial/components/sidenav/sidenav-theme.scss:3

```

do any body know how to implement it?

**Comment by miguelcobain** [comment]
@tmclouisluk upgrading angular material in ember-paper is much more than just bumping the package.json version. There are other changes besides just styles.

We need to figure out what changed between those versions and backport into ember-paper.

**Comment by tmclouisluk** [comment]
Will we plan to figure out and upgrade the version in this moment?

**Comment by xomaczar** [comment]
I think the general consensus is to finish and release v1.0 - then comeback and upgrade to the latest stable angular release.

**Comment by joineral32** [comment]
Is this on the roadmap to get fixed anytime?

**Comment by mellatone** [comment]
Can someone PR a back port of the latest `paper-card` styles from Angular Material?

cc @joineral32

**Comment by xomaczar** [comment]
@joineral32 - can you take a look at AM and backport PR? Lots of us don't use windows so just from visual acceptance testing perspective this is hard

**Comment by miguelcobain** [comment]
We're now on the latest AM styles, so this should be fixed.
