### ISSUE TITLE
dialog layout broken in safari

### ISSUE THREAD

**Issue by tmclouisluk** [miguelcobain/ember-paper#479]
![14182486_10209028019312641_1020036424_n](https://cloud.githubusercontent.com/assets/18186155/18154611/a737df60-7038-11e6-81de-f4b28798c37d.jpg)

when the content is long, the items will merge together.

**Comment by miguelcobain** [comment]
Can you post the template you used for that? So we can reproduce.

A qui, 1/09/2016, 04:39, tmclouisluk <notifications@github.com> escreveu:

**Comment by tmclouisluk** [comment]
> {{#paper-dialog onClose=(action closeAlert) origin=origin}}
> 		{{#paper-toolbar}}
> 		  <div class="md-toolbar-tools">
> 			<h2>{{value.alert_name}}</h2>
> 			<span class="flex"></span>
> 			{{#paper-button iconButton=true onClick=(action closeAlert)}}{{paper-icon icon="close"}}{{/paper-button}}
> 		  </div>
> 		{{/paper-toolbar}}
> 		
> 	<div class="layout-column alert-info">
> 		{{#each value.alert_posts as |alert|}}
> 			<p>
>             The titles of Washed Out's breakthrough song and the first single from Paracosm share the
>             two most important words in Ernest Greene's musical language: feel it. It's a simple request, as well...
>           </p>
> 		{{/each}}
> 	</div>
> {{/paper-dialog}}

Sorry for forgotten to post the template

**Comment by tmclouisluk** [comment]
Got it. The reason is I misuse the dialog. After adding {{#paper-dialog-content}} inside, that is ok now.

Sorry for wrong report
