### ISSUE TITLE
unnecessary vertical scroll on body

### ISSUE THREAD

**Issue by matheusdavidson** [miguelcobain/ember-paper#48]
These properties are needed on the body tag: ``overflow-x: hidden; overflow-y: hidden``

**Comment by miguelcobain** [comment]
Where are you seeing an unecessary vertical scroll? What browser?
Possibly screenshot?

**Comment by hhff** [comment]
this may explain some strange scrolling behavior when the side nav is open on mobile

**Comment by matheusdavidson** [comment]
Im using google chrome, notice in the screenshot that the page content does not cover all page still the scroll bar is there, if you have a look at html and body tag on angular material you'll notice those properties.

![captura de tela de 2015-02-23 19 18 30](https://cloud.githubusercontent.com/assets/2229994/6338881/d29140ce-bb90-11e4-987b-1656b85fd420.png)

**Comment by miguelcobain** [comment]
Those properties shouldn't be needed if the content isn't bigger then the parent. Those properties may just hide this.

I'm also on linux and chrome and I don't see the vertical scrollbar. Really strange...

**Comment by matheusdavidson** [comment]
Another screenshot to show that when scrollbar is really needed it adds another one, thats ugly:
![captura de tela de 2015-02-23 19 21 55](https://cloud.githubusercontent.com/assets/2229994/6338954/5206d5b2-bb91-11e4-84fc-20d70b969a6a.png)

**Comment by miguelcobain** [comment]
Which is your chrome version?

**Comment by matheusdavidson** [comment]
chroem 40.0.2214.111 (64-bit) for ubuntu 64-bits

**Comment by matheusdavidson** [comment]
If you look in angular material website you'll see those properties applied on body tag.

**Comment by miguelcobain** [comment]
This is strange. Can you clear you cache, please, just to be sure?
There was a version of the docs that had that problem.

**Comment by matheusdavidson** [comment]
Tried that now, scrollbar still there.

**Comment by matheusdavidson** [comment]
Found that this is not a bug, is a bank plugin placing elements on websites i visit ¬¬, sorry for the issue!

**Comment by miguelcobain** [comment]
Wow. -.-
Glad you figured it out.
