### ISSUE TITLE
Glimmer 2: bug with paper input

### ISSUE THREAD

**Issue by jamesdixon** [miguelcobain/ember-paper#489]
I just installed Ember 2.9 beta w/ Glimmer 2 and am receiving the following error:

```
ember.debug.js:10648 Uncaught IndexSizeError: Failed to set the 'size' property on 'HTMLInputElement': The value provided is 0, which is an invalid size.
```

The rendered input looks like this:

```html
<input id="input-ember1275" placeholder="Search by Name, Email, or Phone" type="text" accept="undefined" autocomplete="undefined" height="0" min="undefined" max="undefined" name="undefined" pattern="undefined" size="0" spellcheck="false" step="undefined" width="0" class="md-input   ">
```
I tracked it down to the `size` pass-thru in `paper-input`: https://github.com/miguelcobain/ember-paper/blob/master/app/templates/components/paper-input.hbs#L67

Here's how it renders on 2.4:

```html
<input class="md-input   " id="input-ember1323" placeholder="Search by Name, Email, or Phone" type="text">
```

It appears that Glimmer 2 or something else doesn't ignore undefined attributes.

**Comment by xomaczar** [comment]
Seems like in glimmer-1 binding an element attribute to falsy value did not set that attribute to that value however glimmer-2 it does.

**Comment by jamesdixon** [comment]
Yes, definitely a bug. Tracking here: https://github.com/emberjs/ember.js/issues/14243#issuecomment-245940430

**Comment by xomaczar** [comment]
We can close this issue as it was fixed in ember/glimmer2. See https://github.com/emberjs/ember.js/issues/14243#issuecomment-245940430

**Comment by jamesdixon** [comment]
Agreed. Can be closed.
