### ISSUE TITLE
paper-autocomplete floating breaks search

### ISSUE THREAD

**Issue by bdmac** [miguelcobain/ember-paper#496]
I'm not sure if this happens in the non-promise case but we are using promises and if I set `floating=true` on {{paper-autocomplete}} searching no longer works. In the paper-autocomplete component `sourcePromiseArray` updates as expected but nothing triggers the `suggestions` computed property to recompute.

I traced this into the paper-autocomplete template where there is a conditional that switches between using {{paper-input}} when floating or just {{input}} if not floating. If I force it to just use {{input}} regardless of the floating property then `suggestions` recomputes as expected and results appear but obviously it looks totally wrong if you want it to look like a floating label form field...

I'm not sure why using {{paper-input}} so dramatically changes the behavior. The mut of searchText appears to work fine and triggers my cache-miss callback as expected. I can't see anything else it's doing that would cause this but that's what's happening.

Any ideas?

**Comment by xomaczar** [comment]
This has been fixed in paper-menu branch.

**Comment by bdmac** [comment]
Thanks, any idea when that might make it back to master? Last time I tried paper-menu branch paper-autocomplete was in pretty bad shape.

**Comment by xomaczar** [comment]
Not sure there are still some more features to be implemented like virtual-repeat

**Comment by xomaczar** [comment]
Hopefully soon

**Comment by xomaczar** [comment]
@miguelcobain we can close this issue. Paper-menu branch addresses this.
