### ISSUE TITLE
Paper Dialog - Error when origin not present

### ISSUE THREAD

**Issue by TylerJNewman** [miguelcobain/ember-paper#502]
A function is called on an object that doesn't exist in spite of an if statement used to check if it is available.  This seems to be a scope issue.  Please screenshot for error.
<img width="819" alt="screen shot 2016-09-23 at 12 27 22 am" src="https://cloud.githubusercontent.com/assets/8213268/18778137/c42e70fc-8127-11e6-96c9-a21b2042c3d4.png">

**Comment by miguelcobain** [comment]
The immediately previous line is setting `originator` value. That's probably what set the variable to undefined.
Under what conditions does this happen? Anytime you open a dialog? What ember-paper version are you running?

**Comment by TylerJNewman** [comment]
This was occurring when I opened up a dialog.  I am not seeing the error anymore.  I wish I could tell you the exact conditions which this occurred.  My apologies.
"ember-paper": "1.0.0-alpha.3",

**Comment by miguelcobain** [comment]
Reopen if issue persists.
