### ISSUE TITLE
replace all instances of attribute based flex layout and replace with class based ones

### ISSUE THREAD

**Issue by miguelcobain** [miguelcobain/ember-paper#507]
Previously we used Angular Material's attribute based flex layout like:

``` html
<div layout="row">
  <div flex>First item in row</div>
  <div flex="20">Second item in row</div>
</div>
```

However, sometimes we need these attributes in components, so we created a FlexMixin that has those attributeBindings, e.g `{{paper-component flex="20"}}`. However, the current scenario is suboptimal:
- There are performance penalties with generic css attribute-based selectors, especially in IE
- Always using FlexMixin in every component is not very handy, especially because we cant use an attribute binding named `layout`. That property name is already taken in Ember components.

Angular Material converts attributes to classes under the hood with attribute directives. We think the classes AM uses under the hood make a perfect public api. Ember components and normal elements support `class` attribute by default.

So, the above example converts to:

``` html
<div class="layout-row">
  <div class="flex">First item in row</div>
  <div class="flex-20">Second item in row</div>
</div>
```

TODO:
- [x] replace all layout related attributes with classes in documentation (located in the dummy app of this repo) (@mellatone in https://github.com/miguelcobain/ember-paper/pull/528)
- [x] drop FlexMixin (@miguelcobain in https://github.com/miguelcobain/ember-paper/commit/338c324e7e5cdcb86b3b5764129193496ac02f5d)
- [x] stop importing attribute scss from AM [here](https://github.com/miguelcobain/ember-paper/blob/master/app/styles/ember-paper.scss#L50) (@miguelcobain in https://github.com/miguelcobain/ember-paper/commit/473ff52c563bd58122b711a1aac65ee802e7ff82)

**Comment by chriskrycho** [comment]
👋 I might take a stab at this this week.

**Comment by topaxi** [comment]
+1

I'm currently excluding the attribute css file by hand (by completely copying the `ember-paper.scss` except that one import statement) because it makes the output css file **huge!**

**Comment by chriskrycho** [comment]
Alas: I’ve gotten hammered with some surprises this month. If someone else wants this for t-shirt time… please take it.

**Comment by jamesdixon** [comment]
I noticed in the Angular docs that it says:

> Developers should continue to use Layout directives in the HTML markup as the classes may change between releases.

Thoughts?

**Comment by joukevandermaas** [comment]
@jamesdixon angular has some capabilities that ember does not. Those directives are translated to classes at runtime (or compile time?). In ember they would remain in the DOM, with performance and flexibility concerns.

I think the general conclusion was that classes are a better fit for ember.

**Comment by jamesdixon** [comment]
Fair enough! Just wanted to mention it. Thanks, @joukevandermaas!

**Comment by miguelcobain** [comment]
Fixed (see https://github.com/miguelcobain/ember-paper/issues/507#issue-180598155 for details)
