### ISSUE TITLE
Paper-Dialog isnt visible when using Ember v2.8.2

### ISSUE THREAD

**Issue by BennyAlex** [miguelcobain/ember-paper#509]
The Paper-Dialog works fine when using Ember 2.7.2 but on 2.8.2 the screen is just darken, not showing the dialog

**Comment by miguelcobain** [comment]
Any error?

**Comment by BennyAlex** [comment]
@miguelcobain no, it is even visible in the html dom

**Comment by miguelcobain** [comment]
@BennyAlex there is no 2.8.2 version. Do you mean 2.8.1?

**Comment by miguelcobain** [comment]
@BennyAlex I tried to reproduce the problem with 2.8.1 and couldn't make it happen.

**Comment by miguelcobain** [comment]
Please reopen if the issue persists.
