### ISSUE TITLE
dialog error with latest jquery version

### ISSUE THREAD

**Issue by Luiz-N** [miguelcobain/ember-paper#518]
Attempting to load {{paper-dialog-content}} component with the latest version of jquery (3.1.1) throws the following error:

`jquery.js:9793 Uncaught TypeError: Cannot read property 'indexOf' of undefined`

seems to be a breaking change from jquery's side... here's a relevant SO about it.

http://stackoverflow.com/questions/37738732/jquery-3-0-url-indexof-error

**Comment by miguelcobain** [comment]
Which ember-paper version are you on?
The only potential problem I can see is this line: https://github.com/miguelcobain/ember-paper/blob/master/addon/components/paper-dialog-content.js#L29

But we're already using `on('load'` there.

**Comment by Luiz-N** [comment]
yup you're right. I was on 1.0.0-alpha.3 so bumping to 1.0.0-alpha.4 fixed the issue. thanks
