### ISSUE TITLE
paper-menu not working

### ISSUE THREAD

**Issue by zlodes** [miguelcobain/ember-paper#523]
## Stack trace:
```
TypeError: Cannot read property 'addEndEventListener' of undefined
    at vendor-fcc6982….js:39
    at T (vendor-fcc6982….js:19)
    at new L (vendor-fcc6982….js:19)
    at i.hideWrapper (vendor-fcc6982….js:39)
    at i.toggleMenu (vendor-fcc6982….js:39)
    at i.send (vendor-fcc6982….js:12)
    at i.n [as send] (vendor-fcc6982….js:12)
    at i.toggleMenu (vendor-fcc6982….js:39)
    at i.sendAction (vendor-fcc6982….js:12)
    at i.click (vendor-fcc6982….js:38)s @ vendor-fcc6982….js:8
```

This bug works for all examples here: http://miguelcobain.github.io/ember-paper/release-1/#/components/menu

## Steps to reproduce:

1. Open devtools console
2. Click some menu icon here: http://miguelcobain.github.io/ember-paper/release-1/#/components/menu
3. Close alert
4. Click outside of menu

**Comment by miguelcobain** [comment]
If you notice, there is a little warning sign that means that component wasn't updated yet (more details on the intro page).

My suggestion would be to use the paper-menu branch which has working paper-menu, paper-select and paper-autocomplete. That branch will be merged into master soon.
The branch is usable.
You can use the new API ahead of time. :)

**Comment by zlodes** [comment]
@miguelcobain, oh. Thanks!

**Comment by zlodes** [comment]
@miguelcobain, how to use paper-menu from `paper-menu` branch?

**Comment by miguelcobain** [comment]
@zlodes

Try

```bash
$ npm install --save-dev miguelcobain/ember-paper#paper-menu
$ ember g ember-paper
```

**Comment by zlodes** [comment]
@miguelcobain 
I could not find examples of using new paper-menu API. Found it in tests. Thanks.

**Comment by miguelcobain** [comment]
You can look at the dummy APP in tests on that same branch.

You can spin up the dos from that branch by cloning it and running `ember s` (after npm and bower installs).
