### ISSUE TITLE
editMode Button broken in alpha.5 and ember >= 2.8

### ISSUE THREAD

**Issue by BennyAlex** [miguelcobain/ember-paper#526]
Using this Button in ember >= 2.8
`{{#paper-button primary=true raised=true fab=true }}
    {{paper-icon "editMode"}}
{{/paper-button}}`
the icon is shifted to left
![unbenannt](https://cloud.githubusercontent.com/assets/17402724/19717953/5e559c8c-9b63-11e6-88bd-e306ab80cc0d.PNG)

**Comment by miguelcobain** [comment]
Which ember paper version are you using?
Does this happen with other ember versions?

**Comment by BennyAlex** [comment]
@miguelcobain 
Paper: v1.0.0-alpha.5

Ember 2.9.0 and 2.8.2 have got both this problem

**Comment by emurillo510** [comment]
After messing around with the css. By removing width: auto; under md-icon results centering the icon.

md-icon[md-font-icon] {
    line-height: 1;
    /* width: auto; */  taking this out fixes it.
}

<img width="1271" alt="screen shot 2016-10-26 at 6 30 34 pm" src="https://cloud.githubusercontent.com/assets/1156174/19751120/dfe01e06-9bab-11e6-837e-21f472b565b7.png">

**Comment by BennyAlex** [comment]
@emurillo510 
I already saw this but it will affect the other icons too and then some distances are disarranged

**Comment by Luiz-N** [comment]
I noticed this issue if you have other material design css files in your project. (Such as https://github.com/mike-north/ember-cli-materialize)

**Comment by miguelcobain** [comment]
Seems fixed.
