### ISSUE TITLE
fix backdrop out animation

### ISSUE THREAD

**Issue by miguelcobain** [miguelcobain/ember-paper#53]
Currently the backdrop disappears instantly instead of fading out animation

**Comment by alexlafroscia** [comment]
Do you have an example of what you'd like this to look like instead? I would love to help fix this.

**Comment by miguelcobain** [comment]
The main problem is here: https://github.com/miguelcobain/ember-paper/blob/master/app/templates/components/paper-nav-container.hbs#L2

When the sidenav is closed, `open` is set to false and the backdrop is immediately removed from DOM. We need to give some time for the backdrop to fade out before removing it.

Two solutions came to mind:
- Perhaps using a `transitionEnd` event or something.
- Maybe the backdrop could always stay there but we get it "out of the way" with some styling trick

Not really sure. :/

**Comment by alexlafroscia** [comment]
Alright cool, I'm coming up on Spring Break next week and will see if I can get a PR together for this :smile:

**Comment by alexlafroscia** [comment]
I'm reading through the code and trying to understand it.  What does the backdrop do?  And where is the resizing of the browser listened for?

**Comment by miguelcobain** [comment]
Backdrop is the dark transparent element that covers the content when the sidenav is open (in open/close mode).
The resizing behaviour is entirely defined using css media queries.

**Comment by alexlafroscia** [comment]
Oh, I see. Thanks!
