### ISSUE TITLE
paper-input breaks native form validation

### ISSUE THREAD

**Issue by arschmitz** [miguelcobain/ember-paper#530]
Adding a simple form like

``` html
<form id="login-form" {{action "login" on="submit"}} class="layout-column">
    {{paper-input flex=100 label="E-mail" type="email" required=true value=email onChange=(action (mut email))}}
    {{paper-input flex=100 label="Password" type="password" required=true value=password onChange=(action (mut password))}}
    {{#paper-button type="submit" raised=true class="cd-button-primary"}}Login{{/paper-button}}
</form>
```

breaks initial submit validation of empty inputs. Reading some issues that sound related to how your handling the initial `isTouched. The problem is this completely breaks normal form validation on submit. 

you can see the correct native behavior here http://jsbin.com/hucefilomo/edit?html,output

**Comment by arschmitz** [comment]
This is made worse by the fact that most of the time when an input is left blank its going to be because it was missed and so therefore never has been focused making using required essentially useless. 

Is there a way to trigger the error state manually?

**Comment by miguelcobain** [comment]
You mean the following *native* error message isn't displayed?
![screen shot 2016-10-31 at 11 16 48](https://cloud.githubusercontent.com/assets/631691/19852495/8ab84792-9f5b-11e6-9aa1-c1f136135665.png)

**Comment by arschmitz** [comment]
@miguelcobain no i mean no error is displayed at all native or from ember paper. The error displays only after the input has been interacted with once.

**Comment by arschmitz** [comment]
@miguelcobain i found this issue which seems to explain the root cause that you dont want to display it being invalid until interaction (which is correct) but it also needs to display when the form is submitted and they are still blank even if they have not been interacted with

https://github.com/miguelcobain/ember-paper/issues/336

**Comment by shoxter** [comment]
@arschmitz Wouldn't the functionality of the `paper-form` solve your problem?

Is there a reason you prefer the native form to the `paper-form`?

**Comment by arschmitz** [comment]
@shoxter mostly just because i didn't know it existed. This should really be listed as its own component on the website not hidden at the bottom of the input page. I tried using a paper form and this fixes the issue. 

Thank you!
