### ISSUE TITLE
paper-autocomplete remote only UI in alpha6

### ISSUE THREAD

**Issue by bdmac** [miguelcobain/ember-paper#534]
Have you guys tested using paper-autocomplete with remote-only results? All of your examples in the docs have `options` already present even if you simulate a search so when you click in the paper-autocomplete it renders those options and looks OK.

In my testing, if I remove options and only provide a `search` action, when you click in paper-autocomplete it wants to show the searchMessage (from ember-power-select). This looks pretty terrible by default. So I tried passing searchMessage=false to paper-autocomplete which passes through to power-select and attempts to not show the searchMessage but instead show the options. However since I have no options it just expands the empty `dropdown.component` which gives a big empty floating div essentially.

Basically I think it's rendering the `optionsComponent` here: https://github.com/miguelcobain/ember-paper/blob/master/app/templates/components/paper-autocomplete.hbs#L74

Is this a limitation of extending power-select since they seem to put the input for search INSIDE the dropdown whereas paper-autocomplete has the input outside the dropdown?

What I would prefer is to approximate the previous behavior pre-paper-menu branch merge. In the old behavior, when I clicked in the paper-autocomplete w/no results and nothing entered yet it simply remained closed and showed my `placeholder`. I am unsure how to accomplish this now that paper-autocomplete extends power-select.

Here is what I see:

Default behavior with no `options`:
```
{{#paper-autocomplete
      placeholder="Select a Business..."
      search=(perform searchBusinesses)
      onSelectionChange=(action 'selectionChanged') as |business autocomplete|}}
      <span class="item-title">
        <span>{{paper-autocomplete-highlight searchText=autocomplete.searchText label=business.name}} ({{business.subdomain}})</span>
      </span>
{{else}}
  Unable to locate a business by that name.
{{/paper-autocomplete}}
```
<img width="773" alt="screen shot 2016-10-31 at 11 08 32 am" src="https://cloud.githubusercontent.com/assets/47326/19865677/78c4d510-9f5a-11e6-8003-6b11eec13b8e.png">

Behavior if I force `searchMessage=false` which `mustShowSearchMessage` eval to false:
```
{{#paper-autocomplete
      placeholder="Select a Business..."
      search=(perform searchBusinesses)
      searchMessage=false
      onSelectionChange=(action 'selectionChanged') as |business autocomplete|}}
      <span class="item-title">
        <span>{{paper-autocomplete-highlight searchText=autocomplete.searchText label=business.name}} ({{business.subdomain}})</span>
      </span>
{{else}}
  Unable to locate a business by that name.
{{/paper-autocomplete}}
```
<img width="770" alt="screen shot 2016-10-31 at 11 08 48 am" src="https://cloud.githubusercontent.com/assets/47326/19865679/7d1025fc-9f5a-11e6-9e0f-3565bae9dad1.png">

**Comment by bdmac** [comment]
Maybe is there some way to have the dropdown.trigger not actually trigger the dropdown.component just because it has focus if there are no client-side options until you have actually entered text to search for?

**Comment by xomaczar** [comment]
I can take a look at it

**Comment by xomaczar** [comment]
Confirm. Will try to fix it

**Comment by miguelcobain** [comment]
@xomaczar any news on this?

**Comment by xomaczar** [comment]
I can confirm the issue - still needs to be fixed
