### ISSUE TITLE
paper-autocomplete + floating label + allowClear=true

### ISSUE THREAD

**Issue by bdmac** [miguelcobain/ember-paper#539]
Running against alpha6.

If I use paper-autocomplete with the floating label option and allowClear=true the reset button appears beneath the autocomplete input rather than inline with it as it seems like it should.

<img width="831" alt="screen shot 2016-10-31 at 3 51 02 pm" src="https://cloud.githubusercontent.com/assets/47326/19874371/e856aa3a-9f81-11e6-8635-01d17043b1b9.png">

The template code used for this is:
```
{{#paper-autocomplete
        label="Business Name"
        selected=selectedCluster
        search=(perform searchClusters)
        labelPath="name"
        searchMessage=false
        allowClear=true
        onSelectionChange=(action 'selectionChanged') as |cluster autocomplete|}}
    <span class="item-title">
      <span><strong>{{paper-autocomplete-highlight searchText=autocomplete.searchText label=cluster.name}}</strong> &mdash; {{cluster.address}} ({{cluster.cluster_id}})</span>
    </span>
{{/paper-autocomplete}}
```

**Comment by bdmac** [comment]
FWIW I was able to get around this positioning issue with the following CSS:
```
md-autocomplete[md-floating-label] button {
  margin: 0 5px;
  top: 15px;
}
```

**Comment by xomaczar** [comment]
@bdmac looks nice.
@miguelcobain What's the behavior we want? I can't really see an example in AM where label & allowClear are used at the same time. Regardless, I think I like the css fix vs. not showing the clear button if allowClear=false -- if you don't want clear button then don't set allowClear.
Thoughts?

**Comment by miguelcobain** [comment]
@xomaczar looks like it landed on master tão days ago: https://github.com/angular/material/issues/9715

Maybe it's something we can backport?
