### ISSUE TITLE
add tests

### ISSUE THREAD

**Issue by miguelcobain** [miguelcobain/ember-paper#54]
Let's add tests!
- [x] paper-checkbox
- [x] paper-radio
- [x] paper-sidenav
- [x] paper-nav-container
- [x] paper-sidenav-toggle
- [x] sidenav custom events initializer
- [ ] paper-backdrop
- [ ] paper-button
  - [ ] sends action
- [ ] paper-card
- [ ] paper-content
- [ ] paper-divider
- [ ] paper-icon
- [ ] paper-list / paper-item / paper-tile-left / paper-tile-content
- [ ] paper-switch
- [ ] paper-text
- [ ] paper-toolbar
- [ ] base focusable
- [ ] ripple mixin
- [ ] events mixin (also access its need)
- [ ] flex mixin (also access its need)

Common tests:
- Test tagname and class for all components.

**Comment by alexlafroscia** [comment]
If you spec out what features of each should be covered, I would be happy to start etching away at this.

**Comment by miguelcobain** [comment]
I basically look at the component implementation and try to test every bit of code I can find.
I'll try to complete this list.
