### ISSUE TITLE
Paper-Icons Not Displaying Correctly

### ISSUE THREAD

**Issue by shoxter** [miguelcobain/ember-paper#544]
If a `paper-icon` inside of a `paper-button` with `iconButton=true` has `size=48` on it, the `md-icon` element no longer resides inside the `button` element (its parent) causing funky behavior in the layout of surrounding elements.

**Comment by miguelcobain** [comment]
Is this related to https://github.com/miguelcobain/ember-paper/issues/526 in any way?

**Comment by shoxter** [comment]
@miguelcobain It's a different issue, I'm going to investigate further and see if they are related.

**Comment by shoxter** [comment]
@miguelcobain After investigating, these are different instances of the same issue.

I'm still looking into it.

**Comment by shoxter** [comment]
@miguelcobain I found the issue.

The CSS rule `.md-button.md-icon-button` is setting a static height/width to 40px.

This works fine as long as you don't increase/decrease the size of the icon inside of the paper button.

For example, I used `size=48` on the paper-icon inside of my icon button. The images show the problem and the solution -- the solution is removing the set height/width values on that rule and letting the button size itself based on what the user puts inside of the button block (in my case, a size 48 paper-icon).

![screenshot from 2016-11-03 10 30 09](https://cloud.githubusercontent.com/assets/19478126/19969966/dfcd1d5a-a1b0-11e6-9e69-5bf2bcc0e705.png)
![screenshot from 2016-11-03 10 30 24](https://cloud.githubusercontent.com/assets/19478126/19969965/dfc90882-a1b0-11e6-9ae3-f2589d2004d2.png)

**Comment by miguelcobain** [comment]
@shoxter so, angular material doesn't support icon buttons with icons other than the normal size. Is this correct?

**Comment by shoxter** [comment]
@miguelcobain If this is a direct port, I would guess not. There's no way for me to really verify because their site shows all the icon buttons as the same size.

Either way, it's a simple enough fix to implement locally so I'm not too worried about it. I'll close this.

**Comment by miguelcobain** [comment]
@shoxter I say that AM doesn't support this because I see styles that set a specific `width` on icon buttons.
