### ISSUE TITLE
paper-menu positioning off

### ISSUE THREAD

**Issue by jamesdixon** [miguelcobain/ember-paper#546]
The positioning of the paper-menu content doesn't attach to the element and instead always shown in the upper left-hand corner of the page. I've tracked this down to the `top` and `left` properties having an  extra `px` attached to the properties. It appears that `ember-basic-dropdown` already adds the unit and with that, it's being added twice resulting in the property becoming invalid.

Note that I'm running against master.

I'll submit a PR with a fix.

Relevant code from `ember-basic-dropdown`: https://github.com/cibernox/ember-basic-dropdown/blob/4295170a2e53277b6b0af4503b6e2168a7d79d25/addon/components/basic-dropdown.js#L180

**Comment by miguelcobain** [comment]
I don't think this is an issue anymore since we updated ember-basic-dropdown.
