### ISSUE TITLE
jshint error for 'self is not defined'

### ISSUE THREAD

**Issue by SirZach** [miguelcobain/ember-paper#553]
https://github.com/miguelcobain/ember-paper/blob/master/addon/components/paper-autocomplete-trigger-container.js#L26

Looks like it came in for a PR to allow for touch devices to use autocomplete. I'd submit a PR for the fix but I'm not sure if it's supposed to be `this.document` or just `document`. My guess is that it should just be `document`.

**Comment by miguelcobain** [comment]
That's correct, @SirZach.
That line was forgotten in https://github.com/miguelcobain/ember-paper/pull/535

**Comment by SirZach** [comment]
closed by #555
