### ISSUE TITLE
1.0.0-alpha.7 form.submit-button missing

### ISSUE THREAD

**Issue by leifdejong** [miguelcobain/ember-paper#557]
@miguelcobain hey just noticed that while installing `1.0.0-alpha.7` with NPM that the following line is missing in the `Source code (tar.gz) - app/templates/components/paper-form.hbs` but not in the `Source code (zip)`:

```javascript
submit-button=(component "paper-button"
    onClick=(action "onSubmit")
  )
```

This is causing the following error naturally: `
Assertion Failed: A helper named "form.submit-button" could not be found`.

Possibly there was a problem while cutting the tar.gz version?

Also I am very interested in `ember-paper` and using it heavily in the projects I work on. Would love to help contribute to get 1.0.0 pushed out as soon as possible. Please let me know if there are any areas you would like me to work on or help get some of the features out such as the toast, paper-tab, and paper-chips.

**Comment by miguelcobain** [comment]
@leifdejong that feature is on master, not on 1.0.0-alpha.7.
However, the website is for master.

I should make a new release so that people can use the website.

**Comment by miguelcobain** [comment]
`v1.0.0-alpha.8` was published.

**Comment by leifdejong** [comment]
@miguelcobain awesome thanks a lot!
