### ISSUE TITLE
Assertion Failed: A helper named "form.submit-button" could not be found

### ISSUE THREAD

**Issue by BennyAlex** [miguelcobain/ember-paper#561]
I using the latest master version of ember-paper and when I using a form like:

```
{{#paper-form onSubmit=(action "save" form) as |form|}}
{{#form.submit-button raised=true primary=true}}Submit{{/form.submit-button}}
{{/paper-form}}
```
an error occurs saying "Assertion Failed: A helper named "form.submit-button" could not be found"...

**Comment by miguelcobain** [comment]
We are yielding `submit-button`: https://github.com/miguelcobain/ember-paper/blob/master/app/templates/components/paper-form.hbs#L8-L10

Are you sure you're using master?

**Comment by BennyAlex** [comment]
Sorry for troubled you. One of my teammebers extends paper-form and isnt yielding the submit-button -.-
Now the button is working, but it is really useless, because it dosnt react on the enter key

**Comment by miguelcobain** [comment]
@BennyAlex https://github.com/miguelcobain/ember-paper/issues/460

**Comment by BennyAlex** [comment]
@miguelcobain I know this but why you yield an SUBMIT-button when it isnt a real submit-button? This makes no sense in my opinion

**Comment by miguelcobain** [comment]
@BennyAlex Are you saying you don't see an advantage?

The advantage is that the yielded submit button has the click action already set for you.

**Comment by BennyAlex** [comment]
yeah I see it but then its an action button, not a submit button

**Comment by miguelcobain** [comment]
@BennyAlex if you have any suggestions on how to improve paper-form, we would love to hear you!

**Comment by BennyAlex** [comment]
I can show you what I am using at the moment, but I dont think you will like it.
component.hbs:
```
{{#paper-form onSubmit=(action "submit" myvalue) as |form|}}
   {{form.input label="label" value=myvalue
       onChange=(action (mut myvalue)) 
       onKeyDown=(if form.isInvalid "" (action "submit" myvalue))}}
       {{#paper-button disabled=(or form.isInvalid (not myvalue)) type="submit" onClick=(action "submit" myvalue)}}submit{{paper-icon icon="arrow_forward"}}{{/paper-button}}
{{/paper-form}}
```
component.js:
```
actions: {
  submit(myvalue, event){
    if (event.key === 'Enter' || event.type === 'click') {
      //do something
    }
  },
}
```
