### ISSUE TITLE
Touch on paper-backdrop doesn't dismiss sidebar on mobile

### ISSUE THREAD

**Issue by alexlafroscia** [miguelcobain/ember-paper#57]
The `paper-backdrop` component should recognize a tap as well as a click to trigger hiding the sidebar again.

**Comment by miguelcobain** [comment]
It is working on my phone. Strange. 
Running Android 4.4.4 on Chrome.

**Comment by alexlafroscia** [comment]
I tried it in Mobile Safari and touching the backdrop doesn't dismiss the sidebar.  I'll try to run it with the inspector open on my Macbook so I can verify what's going on.
