### ISSUE TITLE
Paper item ripple effect throws error when destroying item

### ISSUE THREAD

**Issue by arschmitz** [miguelcobain/ember-paper#574]
If a paper item is removed during an `onClick` it can cause an error

`Uncaught Error: Assertion Failed: calling set on destroyed object`

This happens when set is called to set `mouseActive` to `false` the fix is pretty simple to just wrap the call in an if like this

```js
if ( !get(this, 'isDestroyed') && !get(this, 'isDestroying') ) {
  set(this, 'mouseActive', false);
}
```

**Comment by A-Helberg** [comment]
https://github.com/miguelcobain/ember-paper/pull/564  should solve this

**Comment by arschmitz** [comment]
@A-Helberg it will not though i believe its a problem with your fix and not that its a different problem ill comment on your PR about it

**Comment by miguelcobain** [comment]
Please reopen if still an issue.
