### ISSUE TITLE
md-content should slide as sidebar comes into view

### ISSUE THREAD

**Issue by alexlafroscia** [miguelcobain/ember-paper#58]
When the sidebar comes into view based on the browser width increasing past a certain point, the `md-content` element should transition gradually with the sidebar instead of "jumping" to the other position and leaving a blank space that the sidebar then fills.  That's how the Material Angular site does it, anyway, and it looks/feels  a lot nicer.  I'm happy to fix this if you want it fixed.

**Comment by miguelcobain** [comment]
Yes, angular material also animates width. This is an edge use case (since it only happens when we resize the viewport), but it should also be addressed.

**Comment by miguelcobain** [comment]
This was fixed a long time ago on later versions.
