### ISSUE TITLE
probably erroneous vendorProperty method in constants service

### ISSUE THREAD

**Issue by panthony** [miguelcobain/ember-paper#584]
See:
```js
  vendorProperty(name) {
    let prefix = this.get('sniffer.vendorPrefix').toLowerCase();
    return this.get('webkit') ? `-webkit-${name.charAt(0)}${name.substring(1)}` : name;
  },
```

The `prefix` variable is never used.

Since there are no tests not sure what the intent was.

**Comment by panthony** [comment]
And this issue appears to be old:

https://github.com/miguelcobain/ember-paper/commit/3f709857a71e1335ab03af74d534f9a9667dd37a#diff-8076479e6b261f5f26674cda37327a89

**Comment by miguelcobain** [comment]
@panthony Strange that jshint isn't complaining. :/

**Comment by panthony** [comment]
@miguelcobain It started complaining when I moved the code to the `addon` directory.

**Comment by miguelcobain** [comment]
Ah, that makes sense then.
