### ISSUE TITLE
Missing -webkit prefixes

### ISSUE THREAD

**Issue by alexlafroscia** [miguelcobain/ember-paper#59]
I've noticed a bunch of issues that appear only on Webkit browsers because `ember-paper` seems to largely be missing any `-webkit` prefixes on its CSS selectors.  Maybe something like [`broccoli-autoprefixer`](https://github.com/sindresorhus/broccoli-autoprefixer) can be added so that it'll add the prefixes automatically?

**Comment by miguelcobain** [comment]
broccoli-autoprefixer is already included. Check index.js. You shouldn't be having this problem.

**Comment by alexlafroscia** [comment]
Really? Because I constantly have problems in Chrome with things not working right due to a lack of the `webkit` prefix.

**Comment by miguelcobain** [comment]
Please check on master. I wasn't passing the correct options to autoprefixer.

**Comment by alexlafroscia** [comment]
Cool, I"ll check this out tomorrow and take a look at some of the other things I made issues for since I should have a good chunk of down time :smile:

**Comment by alexlafroscia** [comment]
Yeah, this seems to be good now.  If I ran a search for `-webkit` previously on `dummy.css` in the browser, it would turn up around 4 or 5 items.  Now it's turning up 400+.  I think the changes you made took care of it :+1:
