### ISSUE TITLE
paper select not show on alpha 12

### ISSUE THREAD

**Issue by beastmst** [miguelcobain/ember-paper#591]
when the page load, the paper-select not show the default selected.. only when focus on, then the selected option show.

when page loaded.. selected option not shown
![2016-12-22_11-43-21](https://cloud.githubusercontent.com/assets/1916904/21414615/0af52e80-c83c-11e6-9c56-fed41e8062eb.jpg)

when use keyboard tab to the ember-select, the selected option shown 
 ![2016-12-22_11-44-05](https://cloud.githubusercontent.com/assets/1916904/21414614/0af4ce4a-c83c-11e6-9c94-578d48130104.jpg)

**Comment by miguelcobain** [comment]
@beastmst very strange. It seems to be working perfectly for me.
I updated the demo page with that example: https://github.com/miguelcobain/ember-paper/commit/b37c006de5d1f5f0d8acad7c24565454b6a6c134

Show us some code.

**Comment by beastmst** [comment]
both my options and selected are a computed..

**Comment by beastmst** [comment]
after some testing, I think is a bug in my code.. please close this issue
