### ISSUE TITLE
Cannot put actions in route?

### ISSUE THREAD

**Issue by jsArgus** [miguelcobain/ember-paper#596]
I'm fairly new to Ember so this might be a newbie mistake. When calling an action from within a paper-button with the action in a route the following error is produced:

> "An action named 'editCategory' was not found in (generated dashboard.categories.index controller)"

Outside a paper-button actions defined in a route work fine.

This can be reproduced in the demo by moving one of the actions in form.hbs from the controller to a new file `routes/forms.js`. Error:

> "Assertion Failed: An action named 'basicSubmitAction' was not found in <dummy@controller:forms::ember858>"

I would expect an action to fire first from the route, and if it is not found there from the controller. Should I do this differently? Is this a bug? Is there a workaround other then placing all actions in the controller?

**Comment by miguelcobain** [comment]
Can you post your template for us to see how are you passing the action?

**Comment by jsArgus** [comment]
`{{#paper-list}}
  {{#paper-subheader}}Categorie administratie{{/paper-subheader}}
  {{#each model as |category|}}
    {{#unless category.isNew}}
      {{#paper-item class="md-3-line"}}
        <div class="md-list-item-text">
          <h3>{{category.name}}</h3>
          ID: {{category.id}}
        </div>
        {{#paper-button secondary=true iconButton=true onClick=(action "editCategory" category)}}
          {{paper-icon "edit"}}
        {{/paper-button}}
      {{/paper-item}}
    {{/unless}}
  {{/each}}
{{/paper-list}}`

**Comment by miguelcobain** [comment]
@jsArgus so, you're using a closure action. Closure actions don't bubble to the route by default. That's just how they work.
However, you can still use them (because they're so cool) + actions in routes using an addon: https://github.com/DockYard/ember-route-action-helper

The headline is:
> Bubble closure actions in routes

Tip: you can use github's code blocks wrapping in triple backticks ```

**Comment by jsArgus** [comment]
Ok, thanks!

**Comment by v3ss0n** [comment]
Not properly benchmarked but closures seems to be alot faster than route actions.

**Comment by miguelcobain** [comment]
@v3ss0n closures and route actions are not mutually exclusive.

You mean closures and named actions?
