### ISSUE TITLE
Ember-Paper has issues with LiquidFire {{liquid-outlet}}

### ISSUE THREAD

**Issue by brendanoh** [miguelcobain/ember-paper#60]
@ef4 introduced me (and many people) to Ember-Paper at EmberConf during a talk that mainly focuses on LiquidFire. Both projects are fantastic and I want to be able to use them both together.

However working with ember-paper it seems like {{liquid-outlet}} actually breaks functionality and many of the styles for MD as they are very particular.

Has anyone had success integrating the two? 

I would love to help out especially if @ef4 or @miguelcobain have thoughts on the integration.

Brendan

**Comment by miguelcobain** [comment]
I agree that liquid-fire will become useful in some cases.
Just as a reminder, the goal of this project is to follow the material design spec. So animations will need to follow it as well.

Here is the spec on material transitions (probably especially useful for liquid-outlets) http://www.google.com/design/spec/animation/meaningful-transitions.html#meaningful-transitions-visual-continuity
I think liquid-fire fits this case very well.

But for now, I don't know why both wouldn't work together. What is exactly the problem?

**Comment by brendanoh** [comment]
I was trying to recreate the demo page and to make that work I needed to add ` classNames: ["ember-app"]` to my application view. However, when I added {{liquid-outlet}} it seems to add div tags that break the CSS structure.

Specific issue I had was that sidebar nav and main paper content areas would not scroll independently when using {{liquid-outlet}} instead of {{outlet}}.

I am also currently having an issue where the sidebar toggle is not toggling the sidebar. The toggleSidenav custom event never gets called although the click event is fired fine.

I love the project and once I get a handle on things I want to help out however I can.

Brendan

**Comment by hhff** [comment]
After watching @ef4's talk at Ember Conf - I feel like getting a `ember-paper` x `liquid-fire` branch happening here would be great.

@ef4 showed a demo of the same type of visual continuity that is in the top example of your material design link @miguelcobain.  Exposing that stuff to the developer will mean big stuff for the developer.

I really really want to help here, but I can't see myself freeing up for at least a couple weeks.  :heart:

**Comment by brendanoh** [comment]
+1 @hhff 

I will contribute as well.

**Comment by miguelcobain** [comment]
This probably won't happen until https://github.com/ef4/liquid-fire/issues/195 is resolved.
So let's make that happen!

**Comment by brendanoh** [comment]
@miguelcobain well a liquid-fire branch is not a requirement for me. How you want to implement the animations isn't as important as full compatibility. 

I just need them to work together and I will contribute to ember-paper regardless.

**Comment by miguelcobain** [comment]
Making this liquid-fire compatible is definitely a first step here.
I don't know what is the blocking issue here.

If it helps, you can add classes to the divs that liquid-fire adds. e.g `{{liquid-outlet class="some-class"}}`.
I believe that the problem may be these extra divs not having the correct styles.

**Comment by elwayman02** [comment]
Is anyone working on this?

**Comment by knownasilya** [comment]
Would also love for this to work, no updates in a while it seems.

**Comment by miguelcobain** [comment]
I've been playing with liquid-fire + ember-paper. Actually, we suggest to use it in the new tabs implementation: http://miguelcobain.github.io/ember-paper/#/components/tabs
I really don't see why wouldn't both addons work together.

Another completely separate issue is to provide custom liquid-fire transitions that respect the material spec.
This issue is about compatibility problems. I couldn't find any. liquid-fire needs extra markup, indeed, but usually you can overcome that easily.

**Comment by dan-hill** [comment]
I am still having issues with paper-menu targeting when using liquid-outlet. Is there a trick to it that maybe I am missing?

**Comment by miguelcobain** [comment]
@dan-hill can you try ember-paper master? I committed a fix for that a couple of days ago.

**Comment by dan-hill** [comment]
@miguelcobain Thanks! Works perfect now.
