### ISSUE TITLE
Offline fonts

### ISSUE THREAD

**Issue by anthonycollini** [miguelcobain/ember-paper#601]
Hello,

I need to develop my app offline, and the only external request that is being made is from this library and it's trying to receive the material icons from google. Is there any quick way that you know of to disable this external icon loading and have it pull from a local source instead?

**Comment by miguelcobain** [comment]
@anthonycollini the easiest approach would be:

- PR ember-paper to u8se a custom option that enables/disables font loading from google fonts. This should be very straightforward.
- Then, in your own app, disable ember-paper's google fonts loading, and and import fonts manually, like any other font

If you need help, jump in the #e-paper channel on ember's slack.

**Comment by v3ss0n** [comment]
for me , i use service worker to cache them all , easiest way.
https://github.com/jkleinsc/broccoli-serviceworker

**Comment by miguelcobain** [comment]
This should be a lot easier now with https://github.com/miguelcobain/ember-paper/pull/636
