### ISSUE TITLE
Content Security Policy directive: "font-src 'self'".

### ISSUE THREAD

**Issue by BransonGitomeh** [miguelcobain/ember-paper#61]
i install ember paper on a new CLI app ,when trying to use elements like navbar...i get this errors in console like 10 of them

 Refused to load the font 'https://fonts.gstatic.com/s/robotodraft/v1/er-TIW55l9KWsTS1x9bTfgeOulFbQKHxPa89BaxZzA0.woff2' because it violates the following Content Security Policy directive: "font-src 'self'".

havent found a way of fixing them yet

version: 0.2.0-beta.1

please help!!!!

**Comment by brendanoh** [comment]
That is perfectly normal and nothing ember-paper can do about it really.

Add this to the ENV section of your config file after the empty APP section:
```javascript
    contentSecurityPolicy: {
      'default-src': "'none'",
      'script-src': "'self' 'unsafe-inline' 'unsafe-eval'",
      'font-src': "'self' https://fonts.gstatic.com",
      'connect-src': "'self'",
      'img-src': "'self'",
      'report-uri':"'localhost'",
      'style-src': "'self' 'unsafe-inline'",
      'frame-src': "'none'"
    }
```

Read more about it: https://github.com/rwjblue/ember-cli-content-security-policy

Brendan

**Comment by alexlafroscia** [comment]
Is there a way that we can add the URL to the CSP in the plugin?

**Comment by hhff** [comment]
You can do it in an initializer - but it's kinda an anti-pattern...

**Comment by miguelcobain** [comment]
Whatever the outcome of this is, we should have a section on the README.

Apart from that, I think we can do one of three things:
- do nothing
- use an initializer
- use a blueprint, mention in the docs and let the user decide? Don't know if blueprints allow this kind of thing.

A question: would hosting the font ourselves (as an asset) remove this warning?

**Comment by hhff** [comment]
Yes hosting it would remove the error - but I don't think we should.

The philosophy behind the ember content security policy is to "complain loudly" so that the developer is acutely aware what cross origin requests are being made in their app.

I think a line in the Readme and a link to the CSP addon is enough!

**Comment by alexlafroscia** [comment]
> A question: would hosting the font ourselves (as an asset) remove this warning?

I think so? Because you can reference fonts on `self` by default, so that should work...

***

I think that we should just do nothing, personally. Whitelisting stuff in the CSP is something that you have to do no matter where you add an external font from, and I think it's better to use Google's hosting of the font.

**Comment by miguelcobain** [comment]
I'm glad we're all in sync, then. :smiley: 

A README update commit will close this.

**Comment by BiggaHD** [comment]
> That is perfectly normal and nothing ember-paper can do about it really.
> 
> Add this to the ENV section of your config file after the empty APP section:
> 
> ```js
>     contentSecurityPolicy: {
>       'default-src': "'none'",
>       'script-src': "'self' 'unsafe-inline' 'unsafe-eval'",
>       'font-src': "'self' https://fonts.gstatic.com",
>       'connect-src': "'self'",
>       'img-src': "'self'",
>       'report-uri':"'localhost'",
>       'style-src': "'self' 'unsafe-inline'",
>       'frame-src': "'none'"
>     }
> ```
> 
> Read more about it: https://github.com/rwjblue/ember-cli-content-security-policy
> 
> Brendan

After I put you .env inside of a <meta> tag, all of the errors disappear. Thank you.
