### ISSUE TITLE
paper-chips throws error on blur on Firefox

### ISSUE THREAD

**Issue by eduardoweiland** [miguelcobain/ember-paper#611]
This seems similar to #606 but it's a bit different. Can be reproduced on the [demo page](http://miguelcobain.github.io/ember-paper/release-1/#/components/chips) when using Firefox (this error does not occur in Chromium). Just clicking on the field then clicking out of it gives the error `ReferenceError: event is not defined`. The field keeps the focused state after loosing focus.

Seems like it is caused by this line https://github.com/miguelcobain/ember-paper/blob/7ba0c103ebd093792c60241000eae1f0df4fe29c/addon/components/paper-chips.js#L232.

```javascript
if (!isEmpty(event) && !isEmpty(event.relatedTarget) && this.$(event.relatedTarget).is(selector)) {
  return true;
}
```

The variable `event` seems to be global. Replacing it with `window.event` seems to solve the issue.

**Comment by pauln** [comment]
`window.event` doesn't seem to fix the issue for me, but passing the event through from the calling functions does.  Note, however, that you need to be using Firefox 48 or higher, as earlier versions don't have support for `mouseEvent.relatedTarget` - so it's not possible to tell where the focus is moving to in a blur event (without ugly workarounds using `setTimeout`).
