### ISSUE TITLE
Safari Bug: Form submit button not tabbable

### ISSUE THREAD

**Issue by leifdejong** [miguelcobain/ember-paper#620]
Environment: Mac OSX 5.6.2 - Safari Version 9.1 (11601.5.17.1)

Replication Steps:

Go to the Form Section of the Dummy App (http://miguelcobain.github.io/ember-paper/release-1/#/forms)
Tab to reach first input "First Name"
Tab to reach the submit button
Enter to try and invoke submit

Expected: Enter should have submitted the form if the button was in focus
Observed: Nothing happens

**Comment by miguelcobain** [comment]
Forms now have a `<form` tagName. This is fixed.
