### ISSUE TITLE
paper-Input can't just be an input (needed for ember-cli-filter-component)

### ISSUE THREAD

**Issue by whiskeysauer** [miguelcobain/ember-paper#634]
This was raised once before when someone questioned why the onChange is required. I am trying to implement [ember-cli-filter-component](https://github.com/zakmac/ember-cli-filter-component) and this has a single input element which receives the query value. Since my entire UI is using ember-paper, I want this input to be styled with MD. So I am trying to use a paper-input element. I set the onChange to null. In doing so, the paper-input renders, but it will not accept input. When you type it just immediately goes away.

The addon is handling everything (I assume) like detecting when the input changes. This will then filter the list. The addon works nicely but I am just not sure how I can style that input with Material Design.

Here is the template for my component. This receives the customer model. **This template does NOT use the paper-input. So I am hoping someone can look at this template which does work and tell me how I can swap out that input with a paper-input**.

```
{{#filter-content content=model properties="displayName, customer_name" as |fc query|}}
    {{input value=query placeholder="Customer Search"}}
      {{#each fc as |customer|}}
      {{#paper-item class="md-3-line" onClick=(action "goToPerson" customer) }}
        {{gravatar-image
          email=customer.email
          class="md-avatar"
          size=50
          defaultImage="mm"
        }}
        <div class="md-list-item-text">
          <h3>{{customer.displayName}}</h3>
          <h4>{{customer.email}}</h4>
          <p>Some notes here.</p>
        </div>
        {{paper-divider}}
      {{/paper-item}}
    {{else}}
      {{#paper-subheader}}Sorry. no records found{{/paper-subheader}}
      {{/each}}
    {{/filter-content}}
```

**Comment by xomaczar** [comment]
paper-input only supports one way binding by design ("data down, actions up) - this is idiomatic way of building components/apps in Ember.
```
{{#filter-content content=model properties="displayName, customer_name" as |fc query|}}
  {{paper-input value=query  onChange=(action (mut query)) placeholder="Customer Search"}}
    {{#each fc as |customer|}}
    {{#paper-item class="md-3-line" onClick=(action "goToPerson" customer) }}
      {{gravatar-image
        email=customer.email
        class="md-avatar"
        size=50
        defaultImage="mm"
      }}
      <div class="md-list-item-text">
        <h3>{{customer.displayName}}</h3>
        <h4>{{customer.email}}</h4>
        <p>Some notes here.</p>
      </div>
      {{paper-divider}}
    {{/paper-item}}
{{else}}
  {{#paper-subheader}}Sorry. no records found{{/paper-subheader}}
  {{/each}}
{{/filter-content}}
```

**Comment by whiskeysauer** [comment]
Great! May I ask what that "mut" is? I saw that all over the examples but I did not see any explanation of what that represents in the action. Usually I see an actual action and then some value passed. Thanks again for your solution.

**Comment by xomaczar** [comment]
The `mut` helper, when used with action, will return a function that sets the value passed to `mut` to its first argument. See: http://emberjs.com/api/classes/Ember.Templates.helpers.html#method_mut

**Comment by xomaczar** [comment]
Does that answer your question? If so, could you please close this issue?

**Comment by whiskeysauer** [comment]
Perfect. Thanks for the explanation and link. Very helpful.

**Comment by xomaczar** [comment]
You'r welcome.
