### ISSUE TITLE
Backdrop style=undefined

### ISSUE THREAD

**Issue by Subtletree** [miguelcobain/ember-paper#638]
md-backdrop gets `style="position:fixed; undefined"`.

paper-backdrop.js lines 25-28:
```
  backdropStyle: computed('fixed', 'translateStyle', function() {
    let style = this.get('translateStyle');
    return this.get('fixed') ? htmlSafe(`position:fixed; ${style}`) : style;
  }),
```

Appears `this.get('translateStyle')` is never defined. I'd make a pull request to remove it but unsure what the original purpose was.

This is visible on the [demo page](http://miguelcobain.github.io/ember-paper/release-1/#/components/dialog). Only the 'Dialog with parent' doesn't have the problem.

**Comment by miguelcobain** [comment]
@Subtletree pretty sure it's safe to remove that. That is a leftover from copy pasting from elsewhere.
