### ISSUE TITLE
"Assertion Failed: calling set on destroyed object" upon leaving Component that contains a 'paper-grid-list'

### ISSUE THREAD

**Issue by mwreppa** [miguelcobain/ember-paper#640]
Hey!
I am using 1.0.0alpha15.
I have a component that contains a 'paper-grid-list' within my application. Upon leaving that component the following error is thrown within the console:

```
EmberError "Assertion Failed: calling set on destroyed object: <XXXXXX@component:paper-grid-list::ember1478>.layoutInvalidated = [object Boolean]"
stack: "Error↵    at assert (http://localhost:4200/assets/vendor.js:31035:13)↵    at Object.assert (http://localhost:4200/assets/vendor.js:42707:34)↵    at Object.set (http://localhost:4200/assets/vendor.js:47371:22)↵    at http://localhost:4200/assets/vendor.js:48234:33↵    at Object.changeProperties (http://localhost:4200/assets/vendor.js:47159:16)↵    at Object.setProperties (http://localhost:4200/assets/vendor.js:48227:32)↵    at Class.setProperties (http://localhost:4200/assets/vendor.js:60073:26)↵    at Class.doLayout (http://localhost:4200/assets/vendor.js:123451:14)↵    at fn (http://localhost:4200/assets/vendor.js:26254:16)↵    at invoke (http://localhost:4200/assets/vendor.js:25671:14)"__proto__: Error
assert @ ember.debug.js:5700
assert @ ember.debug.js:17372
set @ ember.debug.js:22036
(anonymous) @ ember.debug.js:22899
changeProperties @ ember.debug.js:21824
setProperties @ ember.debug.js:22892
setProperties @ ember.debug.js:34738
doLayout @ paper-grid-list.js:75
fn @ ember.debug.js:919
invoke @ ember.debug.js:336
flush @ ember.debug.js:404
flush @ ember.debug.js:528
end @ ember.debug.js:598
run @ ember.debug.js:721
_runExpiredTimers @ ember.debug.js:1106
Backburner._boundRunExpiredTimers @ ember.debug.js:567
```

After finding the issue [#196](https://github.com/miguelcobain/ember-paper/issues/196) i could identified that it seemed to be the same source of error:

```javascript
doLayout: function doLayout() {
    try {
        var tilesInvalidated = this.get('tilesInvalidated');
        this._layoutDelegate(tilesInvalidated);
    } finally {
        this.setProperties({
            'layoutInvalidated': false,
            'tilesInvalidated': false
        });
    }
}
```

The error happens as soon as the finally block is called meaning that 'this' paper-grid-list was already destroyed at the moment the 'setProperties' was called.
I am not calling the 'invalidateLayout' action from anywhere.

**Comment by miguelcobain** [comment]
@mwreppa so, you mean that #196 didn't fix your problem?

**Comment by mwreppa** [comment]
Unfortunately not. I think the fix is not able to catch when ember decides to destroy the object between the check introduced in the invalidateLayout() function
```javascript
invalidateLayout() {
    if (this.get('layoutInvalidated') || this.get('isDestroyed') || this.get('isDestroying')) {
        return;
    }
    this.set('layoutInvalidated', true);
    run.next(this, this.doLayout);
}
```
and the actual call within the finally block in the doLayout() function
```javascript
doLayout() {
    try {
        let tilesInvalidated = this.get('tilesInvalidated');
        this._layoutDelegate(tilesInvalidated);
    } finally {
        this.setProperties({
            'layoutInvalidated': false,
            'tilesInvalidated': false
        });
    }
}
```
sorry i did not provide any pull request but i am a beginner with ember and i was not confident enough to provide a fix for this issue since i am not familiar with the inner mechanics of ember and when a object is being destroyed or not.
my guess is, that there would need to be a check within the finally block in order to prevent accessing the paper-grid-list component.

**Comment by miguelcobain** [comment]
Got it.
Any `run.something` method should have guards that check if the component was destroyed.

Should be easy to fix. You can ping me on slack at #e-paper channel if you need some help.

**Comment by mwreppa** [comment]
Thank you very much!

**Comment by BJKPriyanka** [comment]
@mwreppa can you tell me how did you fix it

**Comment by Subtletree** [comment]
@BJKPriyanka What version of ember-paper are you using?

If you're not on `1.0.0-beta.1` or after could you try that and see if it works? 🙂

**Comment by miguelcobain** [comment]
I think this was fixed in latest versions. If not, please reopen.
