### ISSUE TITLE
Icon: `cloud-check` is being displayed as 2 icons

### ISSUE THREAD

**Issue by anthonycollini** [miguelcobain/ember-paper#641]
The `cloud-check` icon is being displayed as 2 icons, cloud and check. Other hyphenated icons work fine, like `cloud-download` and `cloud-circle`.

I am using it as follows:

```
    {{paper-input
      label='Confirmation Code'
      type='text'
      value=confirmationCode
      onChange=(action (mut confirmationCode))
      icon='cloud-check'
      required='style'
    }}
```

**Comment by miguelcobain** [comment]
@anthonycollini what happens if you use a normal `{{paper-icon "cloud-check"}}`?

**Comment by anthonycollini** [comment]
Same thing happens. As well, the `verified` icon doesn't work. Perhaps we have an outdated version of the material icons?

**Comment by miguelcobain** [comment]
@anthonycollini we're just linking to the google fonts api here: https://github.com/miguelcobain/ember-paper/blob/master/index.js#L43

It should be always updated.

The same happens in Angular Material, btw. This needs investigation.

**Comment by anthonycollini** [comment]
They must have updated it, because that's the website I used to find it.

**Comment by anthonycollini** [comment]
Let's close this issue, as the icon names I was using don't seem to exist any longer.
