### ISSUE TITLE
How can I reset searchText in autocomplete?

### ISSUE THREAD

**Issue by estshy** [miguelcobain/ember-paper#642]
Basically I need a select with search inside to allow user for adding new items to result collection from collection of possible options. Adding new item should cause search to be reseted. I though about using paper-autocomplete but unfortunately it doesn't work the way it should. Overwriting value passed as `searchText` to null doesn't do anything. Is there any official way of solving this issue?

**Comment by miguelcobain** [comment]
@estshy how are "overriding" that value? I'd like to see your template, if possible.

**Comment by estshy** [comment]
Sure. Example should show what I am trying to do

```
{{#each languages as |language| }}
  {{language.name}}    
{{/each}}

{{#paper-autocomplete
  label="Add another language"
  labelPath="name"
  searchField="name"
  options=options
  searchText=searchText
  onSelectionChange=(action 'addLanguage')
  as |lang select|}}
  {{lang.name}}
{{/paper-autocomplete}}

actions: {
  handleLanguageAdd(lang) {
    if (lang) {
      this.get('languages').pushObject(lang);
    }

    this.set('searchText', null);
  }
}
```

**Comment by miguelcobain** [comment]
@estshy what happens if you `this.set('searchText', '');`?

**Comment by pauln** [comment]
I ran into this while working on Chips, and the only workaround I was able to find was using jQuery to set the value to an empty string - once you've located the relevant trigger input, `input.val('');` will clear it.

If we can get an "official" way to reset/clear/set the searchText and have it actually clear the text in the trigger input, we should be able to use it to tidy up the Chips implementation slightly.

**Comment by xomaczar** [comment]
Autocomplete keeps an internal state of recently searched text. When a user makes selection and then starts backspacing - md spec calls for search box to kee the recently search text minus deleted chars. However, give the latest use case - I believe it's a bug and we need to address it

**Comment by estshy** [comment]
@pauln I've also tried dom manipulation but it doesn't work correctly. See @xomaczar response

**Comment by pauln** [comment]
@estshy Have you tried calling `this.set('searchText', '');` followed by `input.val('');` (where `input` is the jQuery-wrapped trigger input)?  The current Chips implementation does this, and I've also done it with a standalone `paper-autocomplete` (outside of Chips).  If the combination of both doesn't do what you expect, describing what _does_ happen might help us figure out the best way to handle this situation :-)

**Comment by estshy** [comment]
@pauln It seems to be working at first glance. I am typing text into the input, then I am selecting the value and everything is cleared out (thanks to `.val()`). Unfortunately after clicking on the input the value is back there. I think it is not in sync with searchText param so doing `this.set('searchText', '');` has no effect and it can not be changed by DOM manipulation.

**Comment by anthonycollini** [comment]
I ran into this issue. I decided to go a different route, not using auto-complete and building my own, however, a hack I though of was to use `getOwner` to find the correct component where it's set, and clear it from there.

**Comment by anthonycollini** [comment]
Does anyone have a hack for this in the meantime?

**Comment by ultish** [comment]
As a temporary measure I had to do 3 things to clear it:
1. set .val('') via jquery
2. this.set('searchText', '');
3. Get the internal 'api' and call this.get('api').actions.search(''); This runs a clear command under the covers in ember power select. 

I got the 'api' object by setting it in my action 
```
focusIn: function(api, event) {
   this.set('api', api);
}
```
And then setting onfocus=(action 'focusIn') in the template for paper-autocomplete

**Comment by betocantu93** [comment]
@ultish tried your approach, but it's not working. 

```

{{#paper-autocomplete
							selected=selectedCity
							label="Ciudad"
							labelPath="name"
							options=stateCities
              required=(if selectedState true false)
              errorMessages=(hash
								required="Tienes que escoger una ciudad"
							)
              triggerClass="selectedCity"
              onFocus=(action "focusIn")
							searchText=(readonly citySearchText)
  						onSearchTextChange=(action (mut citySearchText))
							allowClear=true
							noMatchesMessage="Seleccione primero un estado"
							searchField="name"
							onSelectionChange=(action "onChangeCity") as |city select|}}

							{{paper-autocomplete-highlight
								label=city.name
								searchText=select.searchText
								flags="i"}}
					{{/paper-autocomplete}}

if(this.get('api')){
          Ember.$('.selectedCity').find("input").val('');
          this.set('citySearchText','');
          this.get('api').actions.search('');
        }


```
Any other way or tip?

**Comment by ultish** [comment]
Digging a little into the code, the paper-autocomplete-trigger.js's **text** computed property is the culprit. This computed property is used by the template's input value, and if 'searchText' is set to an empty string programatically (via model update for example), it will return _innerText instead of searchText variable. This causes the input to display the previous typed value instead of an empty string.
#### paper-autocomplete-trigger.js
```javascript
 text: computed('selected', 'searchText', '_innerText', {
    get() {
      let {
        selected,
        searchText,
        _innerText
      } = this.getProperties('selected', 'searchText', '_innerText');

      if (selected) {
        return this.getSelectedAsText();
      }
      return searchText ? searchText : _innerText;  // <-- when searchText is set to "", it returns _innerText. _innerText will be what it was previously
    },
```

Scenario tested:
1. Type in a word (eg "test") into autocomplete, but don't select any value
2. Change 'searchText' variable to "" (eg this.set('searchText', '') )
3. The autocomplete will show the previously typed in text (eg "test")

**Comment by ultish** [comment]
@betocantu93 after the debugging above, i've modified my hack to:
```javascript
// closes the dropdown if necessary
this.get('api').actions.close();
// clears the search text
this.set('searchText', '');
// sets power select search action to null
this.get('api').actions.search(null);
// updates ember paper autoselect trigger text computed property
Ember.$('input').onchange("");
```

**Comment by xomaczar** [comment]
@ultish are you willing to contribute an actual fix to resolve this problem once and for all - I, @ibarrik @miguelcobain are willing to help...

**Comment by ultish** [comment]
@xomaczar sure, i'll take a look this weekend

**Comment by betocantu93** [comment]
@ultish thanks I will test it as soon as possible, also, now that you will be working on this, maybe #786 could be included? it's related to **clear** functionality in mobile

**Comment by ultish** [comment]
@betocantu93 Yep, have fixed

**Comment by ultish** [comment]
@xomaczar didn't get much time to look into it this weekend afterall, was having issues with ember power select's internal selection properties and how to deal with clearing selection when searchText is set to null or when selectedItem is set to null.

**Comment by xomaczar** [comment]
np - that's why this is an OSS project. I also haven't had time to dig in - I think we are violating DDAU principle by having some weired side effects(e.g. _innerSearchText)

**Comment by xomaczar** [comment]
@estshy @ultish latest master resolves this issue - please verify

**Comment by miguelcobain** [comment]
Please reopen if still not solved.
