### ISSUE TITLE
alpha.15 broke the slider click-to-select functionality

### ISSUE THREAD

**Issue by hoboman313** [miguelcobain/ember-paper#644]
alpha.14 -> can click somewhere on the slider to set its value
This behavior has regressed in alpha.15 which makes the slider feel very annoying to use as the user must always drag the slider thumb.

**Comment by miguelcobain** [comment]
@mansona can you take a look please?

**Comment by hoboman313** [comment]
hey, if you guys are looking at it can you also please fix the basic slider functionality breaking ( ex. hard to change value ) when its parent element gets resized. You can see it breaking on https://miguelcobain.github.io/ember-paper/release-1/#/components/slider when you resize the browser window, as an example.

**Comment by miguelcobain** [comment]
This is now fixed. Keep in mind that `paper-slider` is now a DDAU component. It will trigger an `onChange` action with the new value. It is up to you to update the value yourself (like `paper-input`, `paper-checkbox`, `paper-switch`, etc).

**Comment by miguelcobain** [comment]
Also `v1.0.0-alpha.16` was released with this.

**Comment by hoboman313** [comment]
Can confirm that the aforementioned bugs are fixed in the latest alpha. Good job!
