### ISSUE TITLE
Validation state does not update when required is dynamically changed

### ISSUE THREAD

**Issue by steven-ferguson** [miguelcobain/ember-paper#648]
I have a `paper-input` which I would like to dynamically set `required` on. Unfortunately, the validations are not rerun when the `required` property is changed.

```hbs
{{#paper-form as |form|}}
    {{paper-checkbox label="Required" value=isRequired onChange=(action (mut isRequired))}}
    {{paper-input value=foo label="Foo" required=isRequired onChange=(action (mut foo))}}
    {{#form.submit-button disabled=form.isInvalid primary=true raised=true}}
        Submit
    {{/form.submit-button}}
{{/paper-form}}
```

When the checkbox is clicked, I would expect `form.isInvalid` to change to `true`, but it remains `false`.

**Comment by miguelcobain** [comment]
@steven-ferguson This should be fixed in master. I also added tests to cover this case.
Can you please test if the fix works for you?

**Comment by steven-ferguson** [comment]
@miguelcobain Just tested it out, and it is working as expected. Thanks!
