### ISSUE TITLE
Feature: onKeyUp (key-up) 

### ISSUE THREAD

**Issue by dephora** [miguelcobain/ember-paper#651]
Using {{paper-input}} to handle filters results in two core issues.

- `onKeyDown=(action "handleFilterEntry") ` is 1 character behind with regular typed entry and backspacing. For example, to filter the name 'pam' properly, 1 extra character after the 'm' has to be typed for the 'm' to be logged. Additionally, an empty input does not clear the filter until backspaced once more after the input is empty.

- Pasting input with `onKeyDown` results in no input received. 

Note: I'm using ag-grid however as seen below the issue happens in console.log so it's unrelated to ag-grid.

**users-ag.js**
```
...
value: '',
...
actions: { 
  handleFilterEntry(){
    let filterInputValue = this.get('value');
    console.log(filterInputValue);  // this is also behind 1 character
    this.gridOptions.api.setQuickFilter(filterInputValue);
  }
}
```

**users-ag.hbs** 
```
...
// does not work
  {{ paper-input
     label="Filter ..."
     value=value
     onChange=(action (mut value))
     onKeyDown=(action "handleFilterEntry") 
  }}

// works perfectly
 <md-input-container class="table-header-input md-default-theme  md-has-icon">
   {{paper-icon "search"}}
   {{input value=value class="md-input" placeholder="Filter .."
   key-up=(action "handleFilterEntry") }}
 </md-input-container>
```
Seen above in the template are two examples of the 'same' filter. One using `{{paper-input}}` which doesn't work. One using a regular `{{input}}` and working perfectly. (Under normal circumstances one is commented out while the other is active being that I'm using the same value props / actions).

This is issue is not specific to ember-paper but happens with a typical `{{input key-down}}` or ` {{input key-press}}` as well. This is resolved with with `key-up` as seen in the second example in the template. Input, backspacing,  and pasting all work with `key-up`. The console.log is in sync with `key-up` correctly as well.

I'm fairly new to Ember so it's possible I'm overlooking / doing something incorrectly. 

Really appreciate the great work on the library.

**Comment by miguelcobain** [comment]
@dephora why don't you do that filtering in the onChange function?

**Comment by dephora** [comment]
@miguelcobain Do you mean something along the lines of the following?

**users-ag.js**
```
...
value: '',
...
actions: {
  handleFilterEntry(propName, value){
      this.set('value', value)
      let filterInputValue = this.get('value');
      this.gridOptions.api.setQuickFilter(filterInputValue);
    }
}
```

**users-ag.hbs**
```
  {{paper-input
    label="Filter ..."
    value=value
    onChange=(action "handleFilterEntry" value)       
  }}
```

This works, however I'm not sure if this follows best practices between your library and Ember?

**Comment by miguelcobain** [comment]
Yes. Instead of `let filterInputValue = this.get('value');` you can use `value` directly.
What is `propName`?

**Comment by dephora** [comment]
Oh yea, sorry I had set a `filterInputValue` variable from previous testing.

As for `propName`: without a param before `value`, when typing a letter into the input it vanishes before it registers. Much the same way when `mut` isn't present  on the action which is why I wondered if not using `mut` was not advisable.

**Comment by miguelcobain** [comment]
@dephora not using `mut` is completely fine.

This:
```hbs
onChange=(action (mut value))
```

is just a shortcut for:

```hbs
onChange=(action "updateValue")
```
```js
updateValue(value) {
  this.set('value', value);
}
```

If you want to do more complex things, a custom action is the way to do it.

**Comment by dephora** [comment]
@miguelcobain Okay cool - really appreciate the help and quick responses.
