### ISSUE TITLE
Consider an addon/plugins section for third party ember-paper addons

### ISSUE THREAD

**Issue by Subtletree** [miguelcobain/ember-paper#652]
It could be beneficial to have a section on the docs page with links to addons made for ember paper e.g

- https://github.com/CoachLogix/ember-paper-selection-dialog

- https://github.com/CoachLogix/ember-paper-swiper

It could encourage others to make their custom ember-paper components public too.
For example I have a paper-autocomplete component that gets addresses from google places api which could be re used.

EDIT: List of known addons:

https://github.com/CoachLogix/ember-paper-selection-dialog
https://github.com/CoachLogix/ember-paper-swiper
https://github.com/CoachLogix/ember-paper-stepper
https://github.com/miguelcobain/ember-paper-expansion-panel
https://github.com/ibarrick/paper-data-table
https://github.com/Subtletree/ember-paper-link
https://github.com/cogniteev/ember-paper-tabs (will be moved into core at some stage)
https://github.com/NLincoln/ember-paper-dual-slider

**Comment by miguelcobain** [comment]
I also wanted this for a while.

**Comment by devotox** [comment]
Here are a list of some i have created
- https://github.com/devotox/paper-pikaday
- https://github.com/devotox/paper-time-picker
- https://github.com/devotox/paper-password

**Comment by v3ss0n** [comment]
@devotox  feel free to add them to the existing list and submit pull request.
please add prefix ember- to your repos to keep the same naming convention with the rest of ember paper addons. 

ember-paper-pikaday
ember-paper-time-picker
ember-paper-password
