### ISSUE TITLE
Demo website broken

### ISSUE THREAD

**Issue by xypaul** [miguelcobain/ember-paper#653]
Simply showing an empty screen for http://miguelcobain.github.io/ember-paper/
<img width="1109" alt="screen shot 2017-02-21 at 4 17 23 pm" src="https://cloud.githubusercontent.com/assets/2549828/23151738/479efa92-f851-11e6-8e0d-0049a87326dc.png">

**Comment by miguelcobain** [comment]
It's back up. Thanks.
