### ISSUE TITLE
[Question] How does the parent-mixin work?

### ISSUE THREAD

**Issue by BennyAlex** [miguelcobain/ember-paper#654]
Hello, 
I need in my application something like the childComponents - function which is provided by the parent-mixin.

I dont understand how the childComponents - Array is filled. I see that the child will be pushed to it within the register - method, but the register method will never be called...

**Comment by miguelcobain** [comment]
We should avoid using parent-mixin and child-mixin in favor of ember-composability-tools.
Please visit https://github.com/miguelcobain/ember-composability-tools
