### ISSUE TITLE
paper-input does not pass `name` attribute in textarea mode

### ISSUE THREAD

**Issue by mellatone** [miguelcobain/ember-paper#655]
`{{paper-input textarea=true name="anything" onChange=(action noop)}}`

**Comment by miguelcobain** [comment]
@mellatone atm we the correct way to do that would be to:

```hbs
{{paper-input textarea=true passThru=(hash name="anything") onChange=(action noop)}}
```

We set that particular attribute here: https://github.com/miguelcobain/ember-paper/blob/master/addon/templates/components/paper-input.hbs#L21

Please reopen/comment if you think something is wrong.
