### ISSUE TITLE
Autocomplete scrolling not working properly

### ISSUE THREAD

**Issue by anthonycollini** [miguelcobain/ember-paper#660]
When the autocomplete window is opened, it scrolls with the body of the html if you scroll outside the dropdown pane. See video.

![autocomplete-error](https://cloud.githubusercontent.com/assets/933222/23385176/547ef062-fd1c-11e6-970a-72a96afb48cf.gif)

**Comment by xomaczar** [comment]
Does angular material v1.0.8 exhibits similar behavior/bug?

**Comment by anthonycollini** [comment]
@xomaczar No, it prevents the scrolling of the page. https://material.angularjs.org/latest/demo/autocomplete

**Comment by xomaczar** [comment]
This has been fixed since v1.0.0-beta.3 & can be closed.
