### ISSUE TITLE
sidenav example not working 

### ISSUE THREAD

**Issue by beastmst** [miguelcobain/ember-paper#664]
when following the sidenav example, when click on the toggle button..
the leftSideBarLockedOpen value change, but the side nav not showed...

after some debugging, leftSideBarLockedOpen was change but lockedOpen not change..

any idea why?

```hbs
 //template/application.hbs
    <div style="position: relative">
      {{#paper-sidenav-container class="inner-sidenav"}}

           {{#paper-sidenav
             class="md-whiteframe-z2"
             name="left"
             open=leftSideBarOpen
             lockedOpen=leftSideBarLockedOpen
             onToggle=(action (mut leftSideBarOpen))}}
             {{#paper-toolbar as |toolbar|}}
               {{#paper-toolbar-tools}}Left Sidenav{{/paper-toolbar-tools}}
             {{/paper-toolbar}}
             {{#paper-content padding=true}}
               Çup?
             {{/paper-content}}
           {{/paper-sidenav}}

           {{#paper-card-content class="flex"}}
             <div class="layout-fill layout-align-start-center layout-column" style="height: 500px">
               <p>
                 Another way of using the sidenav is to toggle the <code>lockedOpen</code> state.
                 This corresponds to the "persistent sidenav" pattern in the material spec.
               </p>
               <p>
                 Left sidenav is <strong>{{if leftSideBarLockedOpen "locked" "unlocked"}}</strong>.
               </p>

               {{#paper-button raised=true onClick=(action "toggle" "leftSideBarLockedOpen")}}
                  {{if leftSideBarLockedOpen "Unlock" "Lock"}} left sidenav
               {{/paper-button}}

             </div>
           {{/paper-card-content}}

         {{/paper-sidenav-container}}
    </div>
```

```js
//controller/application.js
import Ember from 'ember';

export default Ember.Controller.extend({
  actions: {
    toggle(propName) {
       this.toggleProperty(propName);
    }
  },
});
```

**Comment by miguelcobain** [comment]
@beastmst 

Please wrap your code in ```, it makes it easier to read. (i've done that for you).
Please provide more info. What is the value of `yeotoggle`? The examples prove that the sidenav works, so you must be missing some detail.

Your code doesn't make a lot of sense to me. Firsst, what do you want to achieve with `lockedOpen=yeotoggle`? Second, your `onToggle` action is mutating a `leftSideBarOpen` property that is *never* used again.

Please try to rephrase your question as cleary as possible. Help us help you! :+1:

**Comment by beastmst** [comment]
sorry about that, i have edited the code.. basically it is just copy directly from the example.  In addition, I also copy the toggle function from the /tests/dummy/app/controllers/demo/sidenav.js.  After run it, the code can trigger the toggle when i click on the button, but the problem is lockedOpen not trigger, the updateLockedOpen() in paper-sidenav-inner.js not call at all when i click on the button

**Comment by beastmst** [comment]
manage to solve it, basically need to add in this to the parameter list:
 '''
       {{#paper-sidenav
             class="md-whiteframe-z2"
             name="left"
             open=leftSideBarOpen
             lockedOpen=leftSideBarLockedOpen
             isLockedOpen=leftSideBarLockedOpen    -->this line 
             onToggle=(action (mut leftSideBarOpen))}}
'''
