### ISSUE TITLE
#paper-wormhole div not cleaned up in acceptance tests

### ISSUE THREAD

**Issue by joukevandermaas** [miguelcobain/ember-paper#665]
In [this initializer](https://github.com/miguelcobain/ember-paper/blob/master/addon/initializers/paper-wormhole.js), Ember Paper adds a `div#paper-wormhole` to the DOM when the app boots. However, when the app shuts down this `div` is never removed. This happens with every acceptance test, leaving a bunch of `div#paper-wormhole`'s in the DOM at the end of a test run.

I propose Ember Paper simply only adds the div if it's not already there:

```js
if (document.getElementById('paper-wormhole')) {
  return;
}
```

**Comment by miguelcobain** [comment]
@joukevandermaas we should just get rid of that initializer and use the `contentFor` hook, like ember-basic-dropdown, for example: https://github.com/cibernox/ember-basic-dropdown/blob/master/index.js#L25-L33
