### ISSUE TITLE
{{paper-input}} Helper text

### ISSUE THREAD

**Issue by panthony** [miguelcobain/ember-paper#668]
The `{{paper-input}}` component is missing the possibility to display an helper text:

https://material.io/guidelines/components/text-fields.html#text-fields-required-fields

**Comment by miguelcobain** [comment]
You can pass in a helper text to the paper-input's block. Some useful properties are yielded to the block to help you conditionally render the text (e.g isInvalid, isInvalidAndTouched, etc).
Then you need to style it accordingly. See how angular material did it: https://material.angularjs.org/latest/demo/input

It would be nice to have an example of this in the docs.

**Comment by panthony** [comment]
@miguelcobain I did not see that, thanks for the tip, works great after a little styling 👍
