### ISSUE TITLE
paper-input: configurable custom validation message

### ISSUE THREAD

**Issue by panthony** [miguelcobain/ember-paper#672]
The current custom validation system is pretty nice, but it lacks the capacity to adapt the error message.

For exemple, let's say I want to match a user input against a regex.

I'd like to produce an error more like:

- `The character '%@' is not allowed.`

Instead of a generic/less helpful:

- `Must not contains :whatever your regex allow:`

Given the current implementation I'm not sure what could be the best approach but I'm open to provide the PR.

**Comment by miguelcobain** [comment]
currently we pass the validation message through `Ember.String.loc` with `paramValue` and `currentValue`.
You could specify your message like `The character '%@2' is not allowed.`. `%@2` uses the second parameter, since you're not interested in the first one.

**Comment by panthony** [comment]
Won't do what I'm trying to achieve.

Let's say I have a username input that can only takes letters and digits, `/[a-z0-9]/i`.

If the user type `u$er`.

I wanted to display a very specific message like `"$" is not allowed in username.`.

But in this case, `currentValue` is `u$er` (not what I want), and `paramValue` is resolved before `validate` is called so I can't even workaround by updating the validator itself to set the offending char.

Having a return value such as `true` if valid and `String` with the error message if invalid would have given way more liberty.

**Comment by miguelcobain** [comment]
Can't you calculate `"$" is not allowed in username.` from `u$er`?

**Comment by panthony** [comment]
Not why I did not see that I could override the `message` property when the validation failed with the exact message that I require, like I did for `paramValue` ...

Sometimes you need a good night sleep  :sleeping:. 

Sorry for the waste of time !
