### ISSUE TITLE
What should I use: flex=50 or class="flex-50"

### ISSUE THREAD

**Issue by BennyAlex** [miguelcobain/ember-paper#673]
In the demo page is a paper-input with flex=50, but there also elements with class="flex-50".

In my application it looks like that flex=50 doesnt work.

So can you provide any information on this please?

**Comment by joukevandermaas** [comment]
@BennyAlex In the 'old' ember-paper, it used to be `flex=50`. Now it's `class=flex-50`. See [this page](http://miguelcobain.github.io/ember-paper/release-1/#/layout/introduction) in the documentation for more information on ember-paper's layout system.

This `flex=50` in the documentation was probably missed when this change was made.

**Comment by BennyAlex** [comment]
@joukevandermaas thank you. And in your link there are various layout classes provided, but I there is no description what they do. For example, whats the difference between layout-wrap and layot-align. I know there are cases where you are need both, but this isnt anywhere explained

**Comment by joukevandermaas** [comment]
@BennyAlex You're correct, and I think the documentation should be expanded. However, the classes map basically one-on-one to the flexbox CSS attributes. [Here](https://css-tricks.com/snippets/css/a-guide-to-flexbox/) is some explanation that I've always found helpful.

**Comment by BennyAlex** [comment]
@joukevandermaas Yes they are helpful. Why is there one div with class="layout-column flex"? Does it mean that that the layout direction is column and it is 100% large (flex-100)?

**Comment by joukevandermaas** [comment]
Yup, that is what it means!
