### ISSUE TITLE
md-menu has outline issue after selected

### ISSUE THREAD

**Issue by iirving** [miguelcobain/ember-paper#679]
on my app, and the demo ember-paper app, after selecting a menu item I've been seeing a (blue) outline.  (see attach image)
![screen-cap-menu-outline](https://cloud.githubusercontent.com/assets/24158/24108812/20ff3f22-0d65-11e7-8c72-9446297f27c7.png)

I've been able to corrent this by add to my app.scss: 
`md-menu {
  outline: none;
}`

as for doing a pr to fix this for everyone?
adding this to node_modules/angular-material-source/src/components/menu/menu.scss doesnt make sense.
would it make sense to add this fix to app/styles/ember-paper.sccs after the imports?  if not there then where/how?

**Comment by miguelcobain** [comment]
Do you see this in angular material?
If not, how did they solve that?

**Comment by iirving** [comment]
not seeing this in the current am demo (https://material.angularjs.org/latest/demo/menu).

I'll look into how they solve it.

**Comment by miguelcobain** [comment]
Basically, we had `tabindex="0"` from ember-basic-dropdown and AM doesn't have any tabindex defined.
I changed it to `-1` to make sure that element never gets focused (bypassing the focus to the nested button).

**Comment by iirving** [comment]
thks.  yea i saw that it was a ":focus" issue for ep.
