### ISSUE TITLE
Import Hammer as module

### ISSUE THREAD

**Issue by alexlafroscia** [miguelcobain/ember-paper#68]
I've been trying to switch over to importing Hammer as an AMD module and I haven't gotten it to work.  I tried both

```js
import Hammer from "hammer"
```

and 

```js
import Hammer from "hammerjs"
```

and neither of them worked.  Does Hammer definitely support being imported as a module?

**Comment by hhff** [comment]
Pretty sure you need to name the export in the `index.js` file:

http://www.ember-cli.com/managing-dependencies/

**Comment by alexlafroscia** [comment]
Ahh, perfect! Thanks so much, that's really helpful :smile:

**Comment by alexlafroscia** [comment]
Blegh, I still can't get it working... This is the first I'm doing any real research into AMD modules.  It seems to me that Hammer doesn't export a named module, as the "export" code looks like this:

```js
define(function() {
  return Hammer;
});
```

Based on that, I'm not sure how it fits in with the AMD module importing that @hhff linked to above.  I searched a bunch online, and couldn't find any examples of packages that import Hammer this way or packages that import other similar modules.

**Comment by alexlafroscia** [comment]
I found [this](http://stackoverflow.com/a/24370031/2250435) after searching long enough.  It looks like the Sock.js example that the author gives uses the same syntax that Hammer does, which is not compatible with what Ember.js expects.

**Comment by miguelcobain** [comment]
Yes, looks like ember-cli doesn't support the import of anonymous AMD modules.
This issue https://github.com/ember-cli/ember-cli/issues/2177 will fix that, hopefully.

Meanwhile we either use globals or [ember-browserify](https://github.com/ef4/ember-browserify).

**Comment by alexlafroscia** [comment]
I took a look at getting it going with `ember-browserify` but it still seems to be having issues... I moved the Hammer dependency to be install through NPM instead of Bower and am importing it using

```js
import Hammer from 'npm:hammerjs'
```

but I'm still getting 

> Could not find module npm:hammerjs

**Comment by hhff** [comment]
oh dang i thought hammer was named??  i remember seeing a PR for them to support AMD, and it was named, but that may have been their 1.0x codebase

**Comment by hhff** [comment]
my 2c - let's just do it with globals until that CLI PR gets in.  <3

**Comment by alexlafroscia** [comment]
Yeah, I agree.  `ember-browserify` is really cool, but unfortunately that seems like the easiest way to go.

**Comment by alexlafroscia** [comment]
Maybe we can add an Issue label of `BLOCKED` or something like that

**Comment by fps20** [comment]
`import 'hammerjs';`
It helped me
