### ISSUE TITLE
Installation failed on Windows platform

### ISSUE THREAD

**Issue by nanoart** [miguelcobain/ember-paper#680]
ember install ember-paper failed on Windows with the error, **spawn undefined ENOENT**

**Comment by miguelcobain** [comment]
@nanoart can you give us some more detail?
What ember-cli version? More importantly, what is the full error printed on the console?
Seems unrelated with ember-paper because we don't spawn any process ourselves, but we might delegate to the correct place.

**Comment by joukevandermaas** [comment]
@nanoart this is a transient error with ember-cli that sometimes happens while installing an addon on windows. I assume there's an issue for it in the [ember-cli](https://github.com/ember-cli/ember-cli) repo.

**Comment by nanoart** [comment]
That was full error message.

After some dig,  I found it was related to git (my git version 1.7.9 was too old). It failed at

git clone --template=C:\Users\nanoart\AppData\Roaming\npm-cache\_git-remotes\_templates --mirror git://github.com/angular/material.git C:\Users\nanoart\AppData\Roaming\npm-cache\_git-remotes\git-github-com-angular-material-git-v1-0-9-fa37ba9c

After git upgrade to (2.12.0), the installation works!

Many thanks.
