### ISSUE TITLE
update didUpdateAttrs in paperAutocompleteTrigger [DEPRECATED in ember.js]

### ISSUE THREAD

**Issue by cs3b** [miguelcobain/ember-paper#682]
Ember will stop passing arguments to component lifecycle hooks. => http://emberjs.com/deprecations/v2.x/#toc_arguments-in-component-lifecycle-hooks

https://github.com/miguelcobain/ember-paper/blob/f07be761164cc97b55e2fa4ae45703e6619c9d4b/addon/components/paper-autocomplete-trigger.js#L42

**Comment by sergafts** [comment]
Any updates on this?

**Comment by xomaczar** [comment]
Fixed in #726
