### ISSUE TITLE
tooltip... will it be any implementation for the tooltip component?

### ISSUE THREAD

**Issue by beastmst** [miguelcobain/ember-paper#695]
will it be any implementation for the tooltip component? 
or do you have any recommendation of ember addon for it?

**Comment by panthony** [comment]
+1 would be nice.

For now i'm using https://github.com/sir-dunxalot/ember-tooltips which I like for its simple API.

**Comment by miguelcobain** [comment]
closed by https://github.com/miguelcobain/ember-paper/pull/752
