### ISSUE TITLE
Error using chips on Ember (CLI) 2.13: expected an implementation for 6

### ISSUE THREAD

**Issue by backspace** [miguelcobain/ember-paper#705]
Hey, thanks for all the work on this, it’s been helpful for me to have a lot of UI taken care of so I can focus on business logic.

I tried updating an application to Ember 2.13 today and ran into this error in the console, with part of the UI failing to render:

`ember.debug.js:19829 Error: expected an implementation for 6`
<details>
<summary>Stacktrace</summary>
<pre>
    at Object.debugAssert [as assert] (ember.debug.js:1498)
    at Compilers.compile (ember.debug.js:1201)
    at compileStatement (ember.debug.js:1200)
    at ember.debug.js:1200
    at Array.forEach (<anonymous>)
    at WrappedBuilder.compile (ember.debug.js:1200)
    at ComponentLayoutBuilder.compile (ember.debug.js:1173)
    at Object.compileLayout (ember.debug.js:1173)
    at Cache._emberMetal.Cache.owner [as func] (ember.debug.js:11330)
    at Cache.get (ember.debug.js:18578)
</pre>
</details>

I tracked it down to [this line](https://github.com/backspace/prison-rideshare-ui/commit/f91401396271aa284524a2d93bdb12d931f5e280) in my header template:

```
{{#paper-chips readOnly=true content=chips as |item|}}<span title='{{item.title}}'>{{item.label}}</span>{{/paper-chips}}
```

I’m admittedly using chips outside their intended purpose, just to show an indicator in the header when you’re viewing a “sandbox” site. I can accomplish this differently without using chips, I was just being lazy about CSS etc.

I’ve removed the use of `paper-chips` for now but hopefully I’ll find some time to look into this and propose a fix.

My limited investigation has shown me that the failure is unrelated to the block use; even when I changed the template to this it still produced the same error:

```
{{paper-chips readOnly=true content=chips}}
```

It’s my belief that this relates to Babel 6, based on the text of the error, but it’s pretty mysterious!

**Comment by bjornharrtell** [comment]
The same error message popped up in https://github.com/miguelcobain/ember-paper/pull/578 but was worked around.. would be good to find out what the real cause is though.

**Comment by backspace** [comment]
Thanks for that connexion, @bjornharrtell. I wonder if this is actually a missing tag from [the new Glimmer that uses integers to represent tags](https://github.com/glimmerjs/glimmer-vm/pull/379/files)?

**Comment by backspace** [comment]
Thanks to insight from @rwjblue on the Ember Community Slack, it looks like this is a manifestation of [this known issue](https://github.com/glimmerjs/glimmer-vm/issues/453). As he suggested, when I changed the `md-chips-wrap` and `md-chip` elements to be `div`s instead, the error disappeared.

I’ll write about this on that thread.

**Comment by nizarayari** [comment]
Anyone founnd a simple solution for this issue?

**Comment by Subtletree** [comment]
For now I've just changed `ember-source` to `2.12.0` in package.json

**Comment by nizarayari** [comment]
There is no work around? bc I cannot change back to 2.12

**Comment by Subtletree** [comment]
Unfortunately I don't think there is a work around except fixing these 2 issues in glimmer : (

https://github.com/glimmerjs/glimmer-vm/issues/493
https://github.com/glimmerjs/glimmer-vm/issues/494

What's blocking you from dropping back to 2.12?

**Comment by rwjblue** [comment]
FWIW, I am working on those two issues. Hope to have _something_ for the rest of the glimmer team to review tomorrow. Unfortunately, there are some compounding factors in glimmer-vm ATM.  Basically, Ember 2.13/2.14 are using glimmer-vm packages at `0.22.x`, but master is a significantly different architecture. So any changes we make at this point have to be fixed twice 😭 ...

**Comment by nizarayari** [comment]
Thanks for your great work @rwjblue. @Subtletree , is there any better glimmer perf for your app with 2.13?

**Comment by Subtletree** [comment]
I basically just upgraded to 2.13, hit these issues then dropped back to 2.12 so didn't get a chance to test it. Still have ember-cli 2.13 though so get  `ember install` with yarn etc which is awesome.

🥇 rwjblue!

**Comment by nizarayari** [comment]
Hey guys, do you have any idea when this issue will be fixed? thanks

**Comment by bjornharrtell** [comment]
There is a good chance it's fixed with the recently released Ember 2.13.3, but have not confirmed yet. Planning to do that today when updating https://github.com/miguelcobain/ember-paper/pull/709.

**Comment by bjornharrtell** [comment]
Confirmed that 2.13.3 resolves this issue (at least when using Chips as in the demo page).

**Comment by nizarayari** [comment]
Worked for me as well after upgrading to `"ember-source": "~2.13.3"`

**Comment by miguelcobain** [comment]
To everyone involved in this fix, thank you!

**Comment by bjornharrtell** [comment]
This issue has been fixed as of https://github.com/miguelcobain/ember-paper/pull/709, so should be closed.

**Comment by backspace** [comment]
It’s true, it worked for me with Ember 2.13.3! Thanks, all. 😀
