### ISSUE TITLE
paper-toast

### ISSUE THREAD

**Issue by miguelcobain** [miguelcobain/ember-paper#706]
> @xomaczar thanks again for your interest. I actually have what I think to be a good plan to tackle toasts.

### Step 1 - `paper-toast` component

Make a `{{#paper-toast` component. This will be our basic building block. It would work pretty much like a `{{#paper-dialog` and it would be public in case people want to make more customised things in a toast. A basic example:

```hbs
{{#if isToastOpen}}
  {{#paper-toast onClose=(action (mut isToastOpen) false)}}
    Toast was shown successfully!
  {{/paper-toast}}
{{/if}}

{{#paper-button onClick=(action (mut isToastOpen) true)}}
  Open toast
{{/paper-button}}
```

API:
- `hideDelay` - default `3000` - number of ms before triggering the `onClose` action. Note that the action is responsible for closing the toast, DDAU style, pretty much like dialogs. we could support a special value like `false` to make a toast that never automatically closes itself.
- `parent` - default `paper-wormhole` - this is the id of the parent of the toast we will render into, again very similar to dialogs. I'm not 100% sure if we can render toasts on paper-wormhole as well, but I don't see why we can't.
- `position` - default `'bottom left'` - possible values are `'bottom left'`, `'bottom right'`, `'top left'`, `'top right'`.
- `capsule` - default to `false` - Whether or not to add the `md-capsule` class to the toast to provide rounded corners.

The component will probably yield some util components that hide the material markup underneath:

```hbs
{{#paper-toast onClose=(action (mut isToastOpen) false) as |toast|}}
  {{#toast.text}}
    Custom toast!
  {{/toast.text}}
  {{#toast.close-button}}
    Close
  {{/toast.close-button}}
  {{!--
    for maximum flexibility, we should also yield the close action.
    users may trigger it in any way they want
  --}}
  <button onclick=(action toast.closeAction)>Close using ember</button>
{{/paper-toast}}
```

Notes:
- the component would include the ColorMixin to support `accent=true`.
- I believe we'll need to use ember-css-transitions for animating the toast.
- We need this building block, and there's no reason we shouldn't make it public (that is, we should export it to the consuming app). It may allow more complex toasts the service won't. Speaking of that...

### Step 2 - `paper-toast` service and `paper-toast-container`

Make a `paper-toast` service so we can show toasts more easily in js land.
Like most of the notification ember addons, this service will pair with a `{{paper-toast-container}}` component (if you have a better name, go ahead). People can place this container anywhere, but it is usually placed in `application.hbs`.

Basically, the service will hold the global state and the `paper-toast-container` component will `each` the available toasts on the service, passing in every property needed to `{{#paper-toast`. Please refer to the material spec on what to do when multiple toasts are requested. I'm not sure what should happen.

API:
- `showSimple(text[, options])` - convenience method to build a simple toast. `text` is the text displayed in the toast, `options` is a hash with the same properties that `{{#paper-toast` supports.
- `showComponent(componentName[, options]` -  method to build a toast with a component as its content. `componentName` is the name of the component to render, `options` is a hash with the same properties that `{{#paper-toast` supports. `paper-toast-container` will eventually use the ember `{{component` helper to dynamically render the requested component. I particularly like this method. :)
- both methods should return a `Promise` that resolves when that specific toast's `onClose` action is sent.

### Other considerations

- This really should be tested. Dialog tests should help.
- We should be able to dismiss a toast by swiping it. That isn't a priority. I can tackle or help on that, if someone needs it. I've been using Hammer a lot lately.

**Comment by henrixapp** [comment]
Shouldn't it be called `paper-snackbar`,according to [https://material.io/guidelines/components/snackbars-toasts.html](https://material.io/guidelines/components/snackbars-toasts.html#)

**Comment by miguelcobain** [comment]
Closed by https://github.com/miguelcobain/ember-paper/pull/750
