### ISSUE TITLE
{{paper-menu}} broken with ember-power-select v1.8.4

### ISSUE THREAD

**Issue by vsymguysung** [miguelcobain/ember-paper#711]
The `ember-paper` version is `1.0.0-alpha.19`. the version of `ember-cli` is `2.13.2`.

It seems that  `{{basic-dropdown}}` component is throwing the error while calling the reposition method in the `content.js`.  The following is the actual logs from the console.

```
TypeError: Cannot read property 'get' of undefined
    at calculatePosition (paper-menu.js:100)
    at Class.reposition (basic-dropdown.js:178)
    at Class.open (content.js:175)
    at invokeWithOnError (ember.debug.js:2197)
    at Queue.flush (ember.debug.js:2256)
    at DeferredActionQueues.flush (ember.debug.js:2380)
    at Backburner.end (ember.debug.js:2450)
    at ember.debug.js:3016
```
Thanks.

**Comment by miguelcobain** [comment]
Are you using the same ember-basic-dropdown version in your project as the one that ember-paper uses?

**Comment by vsymguysung** [comment]
I am not using `ember-basic-dropdown` separately at all in my project. I am only using `ember-paper` and `ember-power-select`.

**Comment by miguelcobain** [comment]
@vsymguysung ember-power-select includes ember-basic-dropdown.

You need to use ember-power-select 1.2.0

**Comment by vsymguysung** [comment]
So I assume that  the `ember-power-select` v1.2.0 and above  are not compatible with the most recent `ember-paper` v1.0.0-alpha.19.   FYI,  `{{paper-menu}}` component in `ember-paper` v1.0.0-alpha.19 works fine with `ember-power-select` v1.7.2 from my testing.  Thanks.
