### ISSUE TITLE
Paper Dual Slider

### ISSUE THREAD

**Issue by NLincoln** [miguelcobain/ember-paper#717]
I've made a modified version of `paper-slider` that has two circles. It looks as you'd expect: 
![2017-05-28_11 58 12](https://cloud.githubusercontent.com/assets/2380692/26530571/fb67d60c-439c-11e7-9114-c32142e12ce1.png)

Would there be interest in bringing this component into ember-paper proper?

**Comment by v3ss0n** [comment]
If that is not  in material design (google material) or in Angular material , it is not likley to included in main repo. You can release one like ember-paper-swiper ; https://github.com/coachlogix/ember-paper-swiper

**Comment by NLincoln** [comment]
:+1: I was thinking that might be the case.

**Comment by Subtletree** [comment]
+1 for making it into an ember-paper addon though!

**Comment by NLincoln** [comment]
Addon created: https://github.com/NLincoln/ember-cli-ion-rangeslider

**Comment by Subtletree** [comment]
*https://github.com/NLincoln/ember-paper-dual-slider
