### ISSUE TITLE
ember-paper 0.2.15 Hammer.js target is undefined

### ISSUE THREAD

**Issue by ultish** [miguelcobain/ember-paper#721]
Hi all,

I'm currently still using ember-paper 0.2.x and have recently upgraded ember as well as ember paper. But given this basic package.json which only includes a new ember-cli@2.12.3 and ember-paper@0.2.15, I get an error from hammer.js once I add a {{paper-button}} to a component's template file.

Is 0.2.x series just not compatible with latest ember, and i must upgrade to 1.0.x? 

`target is undefined
addEventListeners/<@http://localhost:4800/assets/vendor.js:72140:9
each@http://localhost:4800/assets/vendor.js:71978:9
addEventListeners@http://localhost:4800/assets/vendor.js:72139:1
Input.prototype.init@http://localhost:4800/assets/vendor.js:72367:1
Input@http://localhost:4800/assets/vendor.js:72352:5
MouseInput@http://localhost:4800/assets/vendor.js:72714:5
createInputInstance@http://localhost:4800/assets/vendor.js:72403:12
Manager@http://localhost:4800/assets/vendor.js:74200:18
Hammer@http://localhost:4800/assets/vendor.js:74060:12
didInsertElement@http://localhost:4800/assets/vendor.js:97418:39
superWrapper@http://localhost:4800/assets/vendor.js:51464:17
CoreView<.trigger@http://localhost:4800/assets/vendor.js:53418:16
superWrapper@http://localhost:4800/assets/vendor.js:51464:17
didCreate@http://localhost:4800/assets/vendor.js:23633:9
commit@http://localhost:4800/assets/vendor.js:62088:17
commit@http://localhost:4800/assets/vendor.js:20196:7
_renderRoots@http://localhost:4800/assets/vendor.js:23023:9
_renderRootsTransaction@http://localhost:4800/assets/vendor.js:23052:9
_renderRoot@http://localhost:4800/assets/vendor.js:22973:7
_appendDefinition@http://localhost:4800/assets/vendor.js:22886:7
appendOutletView@http://localhost:4800/assets/vendor.js:22869:7
Queue.prototype.invokeWithOnError@http://localhost:4800/assets/vendor.js:10921:9
Queue.prototype.flush@http://localhost:4800/assets/vendor.js:10982:9
DeferredActionQueues.prototype.flush@http://localhost:4800/assets/vendor.js:11106:9
Backburner.prototype.end@http://localhost:4800/assets/vendor.js:11176:7
Backburner.prototype.run@http://localhost:4800/assets/vendor.js:11290:11
Backburner.prototype.join@http://localhost:4800/assets/vendor.js:11321:1
run.join@http://localhost:4800/assets/vendor.js:33324:12
run.bind/<@http://localhost:4800/assets/vendor.js:33387:14
resolve/</mightThrow@http://localhost:4800/assets/vendor.js:3906:21
resolve/</process<@http://localhost:4800/assets/vendor.js:3974:12`

package.json

> {
>   "name": "test",
>   "repository": "",
>   "scripts": {
>     "build": "ember build",
>     "start": "ember server",
>     "test": "ember test"
>   },
>   "devDependencies": {
>     "broccoli-asset-rev": "^2.4.5",
>     "ember-ajax": "^2.4.1",
>     "ember-cli": "2.12.3",
>     "ember-cli-app-version": "^2.0.0",
>     "ember-cli-babel": "^5.1.7",
>     "ember-cli-dependency-checker": "^1.3.0",
>     "ember-cli-eslint": "^3.0.0",
>     "ember-cli-htmlbars": "^1.1.1",
>     "ember-cli-htmlbars-inline-precompile": "^0.3.6",
>     "ember-cli-inject-live-reload": "^1.4.1",
>     "ember-cli-qunit": "^3.1.0",
>     "ember-cli-sass": "^6.2.0",
>     "ember-cli-shims": "^1.0.2",
>     "ember-cli-sri": "^2.1.0",
>     "ember-cli-uglify": "^1.2.0",
>     "ember-data": "^2.12.0",
>     "ember-export-application-global": "^1.0.5",
>     "ember-load-initializers": "^0.6.0",
>     "ember-paper": "^0.2.15",
>     "ember-resolver": "^2.0.3",
>     "ember-source": "~2.12.0",
>     "ember-welcome-page": "^2.0.2",
>     "loader.js": "^4.2.3"
>   },
>   "engines": {
>     "node": ">= 4"
>   },
>   "private": true
> }

bower.json:
> {
>   "name": "xw-test",
>   "dependencies": {
>     "hammer.js": "^v2.0.8",
>     "matchMedia": "0.2.0"
>   }
> }

**Comment by v3ss0n** [comment]
It won't be sure to be compatible since no longer maintained

**Comment by miguelcobain** [comment]
@ultish please upgrade to latest ember-paper. The CHANGELOG will help you a lot in that process.
