### ISSUE TITLE
provide a theme

### ISSUE THREAD

**Issue by SirZach** [miguelcobain/ember-paper#73]
I'd like to override the primary color for the app to get away from the blue. I know I can import ember-paper in my app.scss file but how do I change the primary and any other variables?

**Comment by SirZach** [comment]
So I found that you have all the color palettes that I would like to use in color-palette.scss which is awesome! I'm just not sure how to go about using them to compile the css file that provides the styles for all the ember-paper components.

**Comment by leoeuclids** [comment]
@SirZach you can import the `color-palette` first, set `$primary-color-palette` with your color and then import `ember-paper`

like this...
````css
@import 'color-palette';

$primary-color-palette: $color-indigo;

@import 'ember-paper';
````

**Comment by SirZach** [comment]
@leoeuclids hmm I tried that in app.scss and it was a no-go. the primary button colors are still the blue.

**Comment by SirZach** [comment]
I had accidentally imported ember-paper at the top of my file. Your code works great. It should make it onto the README. Thanks!

**Comment by leoeuclids** [comment]
No problem @SirZach, glad i could help.
