### ISSUE TITLE
Autocomplete search returns bad results

### ISSUE THREAD

**Issue by raghuvaran** [miguelcobain/ember-paper#734]
The paper-autocomplete search returns bad results that even doesn't match the text in anyway. 

Here is my template:

`        {{#paper-autocomplete
                      placeholder="Type RTU unit #"
                      options=rtus
                      labelPath="label"
                      searchFeild="label"
                      search=(action "searchRtu")
                      selected=installation.rtu
                      label=(translate "rtu_unit")
                      allowClear=true
                      onSelectionChange=(action (mut installation.rtu)) as |rtu autocomplete|
        }}
        {{paper-autocomplete-highlight label=rtu.label searchText=autocomplete.searchText flag="i"}}
        {{/paper-autocomplete}}`

And `rtus` look like:
`      { id: 1, label: 'RTU 1' },
       { id: 2, label: 'RTU 2' }`

When I type : 
 **1** it works (displays 'RTU 1'),
 **2** it displays all results,
 **3** it displays 'RTU 1',
 **4** it displays 'RTU 2',
 **5** => none, etc.

**Comment by panthony** [comment]
@raghuvaran You actually pass the search callback in your template:

```hbs
search=(action "searchRtu")
```

This is your code that is doing the filtering, if there is an issue it's probably in `searchRtu`, maybe this issue can be closed?
