### ISSUE TITLE
Whats left to drop Alpha , and Move to Beta?

### ISSUE THREAD

**Issue by v3ss0n** [miguelcobain/ember-paper#738]
Since we are using e-p alpha without problem in Production - serving over 9000 monthly active users now, i guess its time to announce Beta.
Whats left in features that needed to be matured to announce this a beta? Lets focus on those.

**Comment by miguelcobain** [comment]
@v3ss0n I wanted to update grid-list component at least to have an API that is coherent with the new convention: http://miguelcobain.github.io/ember-paper/release-1/#/components/grid-list

Essentially, convert dash-cased attributes to camelCased. Also remove `md-` prefix.

Also `{{#paper-grid-list` should yield a `grid` hash, such that we can use it like
```hbs
{{#paper-grid-list}}
```

**Comment by miguelcobain** [comment]
beta.1 was released 👍
