### ISSUE TITLE
extra space inside of link-to helper when used with paper-button

### ISSUE THREAD

**Issue by arlofeirman** [miguelcobain/ember-paper#745]
Hello! Great job with ember-paper, I've enjoyed working with it on my project.
I'm using version 0.2. Maybe my issue got fixed in the latest version.

I'm experiencing an issue when wrapping a paper-button inside of a link-to helper.

The code for the link/button:

```
{{#link-to "sign-up"}}
  {{#paper-button raised=true}}Sign Up{{/paper-button}}
 {{/link-to}}

{{#link-to "sign-in"}}
  {{#paper-button raised=true}}Sign In{{/paper-button}}
{{/link-to}}
```
An extra space is getting added inside of the <a> tag after the button. 
You can see the underline in between the sign in and sign up buttons here:

<img width="438" alt="screen shot 2017-07-04 at 8 36 19 am" src="https://user-images.githubusercontent.com/25486156/27833431-d36a410a-60a0-11e7-811a-54f3eb80fca1.png">

The problem is solved by bringing the `{{/link-to}}` up to the same line as the button:

```
{{#link-to "sign-up"}}
  {{#paper-button raised=true}}Sign Up{{/paper-button}}{{/link-to}}
{{#link-to "sign-in"}}
  {{#paper-button raised=true}}Sign In{{/paper-button}}
{{/link-to}}
```
It looks like the return character gets treated as a space somehow. 
Indenting my `{{link-to}}` and nested `{{#paper-button}}` like this 
works fine everywhere else in the project. It would like to keep code style consistent.

Screenshot of the html in chrome inspector:

<img width="1296" alt="screen shot 2017-07-04 at 10 13 14 am" src="https://user-images.githubusercontent.com/25486156/27833834-66478fea-60a2-11e7-8961-835e6e58e966.png">

I thought this was worth making an issue for, incase anyone else has run into the same thing and has a solution.

**Comment by miguelcobain** [comment]
@arlofeirman 

a quick way to "solve this" is to use handlebars whitespace removal syntax. e.g
```hbs
{{#link-to "sign-up"~}}
  {{#paper-button raised=true}}Sign Up{{/paper-button}}
{{~/link-to}}

{{#link-to "sign-in"~}}
  {{#paper-button raised=true}}Sign In{{/paper-button}}
{{~/link-to}}
```

You should upgrade ember-paper version to the latest.
We have this addon for button links: https://github.com/Subtletree/ember-paper-link

Additionally, latest ember-paper versions support an href attribute which you can use to do something like:
```hbs
{{#paper-button href=(href-to 'contacts.contact' contact) target="_blank"}}
  href link
{{/paper-button}}
```

this example uses https://github.com/intercom/ember-href-to

**Comment by arlofeirman** [comment]
Thanks! Is the latest version of paper compatible with ember 2.10.2?

**Comment by miguelcobain** [comment]
@arlofeirman affirmative :)

Despite the alpha tag, we're very close to 1.0. In the light of ember's upgrade path, we don't want to break things when we land 1.0. Also, if we do break something, it will be documented in the changelog.
