### ISSUE TITLE
color palette contrast function conflicts with css filter: contrast()

### ISSUE THREAD

**Issue by Subtletree** [miguelcobain/ember-paper#754]
Using a [contrast filter](https://developer.mozilla.org/en/docs/Web/CSS/filter#contrast()_2) now tries to use the contrast function defined in `color-palette.scss`.

The contrast function will need renaming unless there's some other scss tricks I'm unaware of.

Just leaving this here as a reminder, will whip up a pr this week.

Also there's some lingering usages of `'contrast'` in the demo that need changing to `'contrastDefaultColor'`

**Comment by miguelcobain** [comment]
I was completely unaware of that filter. I can rename the function.

> Also there's some lingering usages of 'contrast' in the demo that need changing to 'contrastDefaultColor'

What usages are you referring to?

**Comment by Subtletree** [comment]
maybe just this one:

https://github.com/miguelcobain/ember-paper/blob/c3f2d798d32ad881a8e25467f28ae6b15afabffe/tests/dummy/snippets/theme.color-function.scss

**Comment by miguelcobain** [comment]
So,

```scss
color: color($primary, 'contrast');
```
would change to
```scss
color: renamedContrast($primary);
```

**Comment by Subtletree** [comment]
I don't fully understand how the color functions work but I think there's no longer a 'contrast' property on each color, so would have to be `color: color($primary, 'contrastDefaultColor');`

**Comment by Subtletree** [comment]
Just looked in what contrast is doing and think your way is right

**Comment by Subtletree** [comment]
Guess this needs changing too: https://github.com/miguelcobain/ember-paper/blob/c3f2d798d32ad881a8e25467f28ae6b15afabffe/tests/dummy/snippets/theme.import.scss

Not sure how to go about it maybe just
```
$color-teal: map-merge($color-teal, ('defaultContrastColor':  $light-contrast-color));
$color-light-green: map-merge($color-light-green, ('defaultContrastColor':  $light-contrast-color));

**Comment by miguelcobain** [comment]
That's correct. That example is explaining how change a value of a palette.

**Comment by miguelcobain** [comment]
Thankfully, changing the contrast shouldn't be something we need to do as often anymore. :)
