### ISSUE TITLE
Paper-tabs horizontal scroll not working

### ISSUE THREAD

**Issue by betocantu93** [miguelcobain/ember-paper#756]
So I read the new commits, updated to beta.1 and I'm testing the new paper-tabs, they are awesome, by the way, great job and implementation.but I found that while on smaller screen sizes the horizontal scroll only works once, so I can´t navigate through all the tabs.
``` 
{{#paper-tabs
 borderBottom=true
 selected=selectedNavItem
 onChange=(action (mut selectedNavItem)) as |tabs|}}
	{{#tabs.tab name=1}}
		Motivo de Consulta
        {{/tabs.tab}}
	{{#tabs.tab name=2}}
		Antecedentes
        {{/tabs.tab}}
	{{#tabs.tab name=3}}
		Interrogatorio APyS
        {{/tabs.tab}}
	{{#tabs.tab name=4}}
		Exploración Física
        {{/tabs.tab}}
{{/paper-tabs}}
```

                 
<img width="408" alt="screen shot 2017-07-20 at 5 15 57 pm" src="https://user-images.githubusercontent.com/9092644/28441243-6e59aae0-6d6f-11e7-9b91-6859af0477ac.png">

<img width="431" alt="screen shot 2017-07-20 at 5 21 41 pm" src="https://user-images.githubusercontent.com/9092644/28441395-22e0446a-6d70-11e7-969c-9b310af47177.png">

So I can't reach the "Exploración Física" tab, which is the number 4.

I'm not sure why this could be happening.

**Comment by miguelcobain** [comment]
You are correct, sir.

I pushed a fix to master, can you try it and confirm if it fixes the problem?

Running `yarn add miguelcobain/ember-paper` or `npm install miguelcobain/ember-paper` should work.

**Comment by betocantu93** [comment]
@miguelcobain Thanks!! it's working now! Awesome!

**Comment by miguelcobain** [comment]
Thanks for reporting. The fix will be on the next release. 👍
