### ISSUE TITLE
Error: argument `$color` of `rgba($color, $alpha)` must be a color

### ISSUE THREAD

**Issue by proche90210** [miguelcobain/ember-paper#757]
I got error this during a clean install of my master which was working.

In my package.json I had `"ember-paper": "^1.0.0-alpha.20",`
and I'm using ember 2.12.2.

I removed the caret to set the version to exactly `1.0.0-alpha.20` and it fixed the error. 

This must be an issue with the new version of `ember-paper: 1.0.0-beta.1.
`

**Comment by miguelcobain** [comment]
Are you using the color function in your styles?

**Comment by proche90210** [comment]
Ya

**Comment by miguelcobain** [comment]
And can you show us the code where you use it?

**Comment by proche90210** [comment]
Sorry running ember serve
```
The Broccoli Plugin: [BroccoliMergeTrees] failed with:
Error: argument `$color` of `rgba($color, $alpha)` must be a color

Backtrace:
	tmp/sass_compiler-input_base_path-EuPlnhGD.tmp/app/styles/angular-material/core/style/mixins.scss:315, in function `rgba`
	tmp/sass_compiler-input_base_path-EuPlnhGD.tmp/app/styles/angular-material/core/style/mixins.scss:315, in mixin `checkbox-primary`
	tmp/sass_compiler-input_base_path-EuPlnhGD.tmp/app/styles/angular-material/components/checkbox/checkbox-theme.scss:36
    at options.error (/home/petroc/Documents/Orreco/Ember-CoachCentral/coach-central/node_modules/node-sass/lib/index.js:291:26)
```

**Comment by miguelcobain** [comment]
I don't see how this can happen. To help me find the problem:
- Can you provide some code that is responsible for this error? Are you overriding ember-paper's palettes or styles?
- In case you're not, can you please reproduce this problem in a project or twiddle and share it with us?

**Comment by proche90210** [comment]
Sorry not back in work until Monday. I'll try to give a better update for you then. I didn't write the css, another developer did.

**Comment by sl249** [comment]
I'm running into the same issue while updating to the beta. Here's the backtrace 

`Backtrace:
	tmp/sass_compiler-input_base_path-eCYnn0a1.tmp/app/styles/angular-material/components/checkbox/checkbox-theme.scss:31, in function `rgba`
	tmp/sass_compiler-input_base_path-eCYnn0a1.tmp/app/styles/angular-material/components/checkbox/checkbox-theme.scss:31
    at options.error (/Users/ricardob/Documents/trove-data-catalog/node_modules/node-sass/lib/index.js:291:26)`

**Comment by miguelcobain** [comment]
@sl249 are you overriding or creating a custom color palette in your project?

**Comment by sl249** [comment]
Overriding $color-grey

**Comment by miguelcobain** [comment]
@sl249 can you paste that code?

**Comment by sl249** [comment]
`    $color-grey: (
      '0': #D3D3D4,
      '50': #9A9D9F,
      '100': #7B7F83,
      '200': #64696D,
      '300': #404547,
      '400': #2C3134,
      '500': #25292C,
      '600': #1E2124,
      '700': #12181E,
      '800': #0C141C,
      '900': #060D13,
      '1000': #01060B,
      'A100': #ffffff,
      'A200': #2C3134,
      'A400': #bdbdbd,
      'A700': #616161,
      'contrast': $light-contrast-color,
      'background': #343A3E
    );
    $foreground: $foreground-light;`

**Comment by miguelcobain** [comment]
@sl249 can you try

```
   $color-grey: (
      '0': #D3D3D4,
      '50': #9A9D9F,
      '100': #7B7F83,
      '200': #64696D,
      '300': #404547,
      '400': #2C3134,
      '500': #25292C,
      '600': #1E2124,
      '700': #12181E,
      '800': #0C141C,
      '900': #060D13,
      '1000': #01060B,
      'A100': #ffffff,
      'A200': #2C3134,
      'A400': #bdbdbd,
      'A700': #616161,
      'contrastDefaultColor': $light-contrast-color
    );
```

also, not sure what your `background` key was doing there, unless you use it manually in your own scss styles.

**Comment by sl249** [comment]
@miguelcobain Yeah the background is something i'm using manually with the color function. Looks like that did after replacing all the instances where I was using 'contrast' in my own stylesheet. Thanks!

**Comment by miguelcobain** [comment]
Yes. `contrastDefaultColor` is the new `constrast`.
For future reference, I'll explain this change here.

We now have a much more powerful method for contrast colors. Basically, a palette as all the information it needs to know what contrast color a specific shade needs.

So, a palette can have:
- `contrastDefaultColor` - the contrast color that is returned - you can specify any color, but the standard contrast colors are `$light-contrast-color`, `$dark-contrast-color` and `$strong-light-contrast-color`
- `contrastDarkColors` - the shades of the palette that have `$dark-contrast-color` as its contrast color. This lets you override the default color for the shades you specify here.
- `contrastLightColors` - the shades of the palette that have `$light-contrast-color` as its contrast color. This lets you override the default color for the shades you specify here.
- `contrastStrongLightColors ` - the shades of the palette that have `$strong-light-contrast-color` as its contrast color. This lets you override the default color for the shades you specify here.

Any of the last 3 can take a sass list of strings, e.g `'contrastLightColors': ('600', '700', '800', '900', 'A700')`.
You can take a look at the palettes file to see the built-in palettes: https://github.com/miguelcobain/ember-paper/blob/master/app/styles/color-palette.scss

This allows me to introduce the new `colorContrast` function.
This function uses all of this information to **return a contrast color given a specific color**.
It acts as the counterpart of the `color` function.

For example, if you want some element with the primary color and some text on it you can use:
```scss
.my-element {
  background-color: color($primary);
  color: colorContrast($primary);
}
```

This makes sure that the text will use the correct contrast according to the information in the palette.

I think this is a very powerful system, and lets me focus on colors globally, and not on a case by case basis.

**Comment by drummy2** [comment]
I get this error when installing on a brand new clean project.  I don't know if I am missing a dependency.  I cannot see any mention of a color function.

`Error: argument `$color` of `rgba($color, $alpha)` must be a color

       Backtrace:
        tmp/sass_compiler-input_base_path-uJvmJPGr.tmp/app/styles/angular-tabs-theme.scss:54, in function `rgba`
        tmp/sass_compiler-input_base_path-uJvmJPGr.tmp/app/styles/angular-tabs-theme.scss:54, in mixin `md-tab-accent`
        tmp/sass_compiler-input_base_path-uJvmJPGr.tmp/app/styles/angular-tabs-theme.scss:101
        on line 54 of tmp/sass_compiler-input_base_path-uJvmJPGr.tmp/app/styles/angular-tabs-theme.scss
>>             background: rgba(color($accent, 'contrast'), 0.1);
   ------------------------^`

**Comment by franktopel** [comment]
I also have this issue with `"bootstrap": "^4.1.1",`.

**Comment by panthony** [comment]
@drummy2 See the previous comment:

https://github.com/miguelcobain/ember-paper/issues/757#issuecomment-317515253

**Comment by drummy2** [comment]
So the issues for me were around variables in Sass clashing with bootstrap and other color functions. These variables are only set if they are null already.

**Comment by jesustorresor** [comment]
I got an error when installing my project

**Sass Syntax Error (SassCompiler) in app/styles/default-theme.scss:105:80

Error: argument `$color` of `red($color)` must be a color
        on line 105 of tmp/sass_compiler-input_base_path-Dn4WHhl5.tmp/app/styles/default-theme.scss, in function `red`
        from line 105 of tmp/sass_compiler-input_base_path-Dn4WHhl5.tmp/app/styles/default-theme.scss, in mixin `paper-theme-variables`
        from line 117 of tmp/sass_compiler-input_base_path-Dn4WHhl5.tmp/app/styles/default-theme.scss
        from line 64 of tmp/sass_compiler-input_base_path-Dn4WHhl5.tmp/app/styles/ember-paper.scss
        from line 5 of tmp/sass_compiler-input_base_path-Dn4WHhl5.tmp/app/styles/app.scss
>> trast: #{red($contrast-color)}, #{green($contrast-color)}, #{blue($contrast-
   ------------------------------------------^



Stack Trace and Error Report: C:\Users\jtorres\AppData\Local\Temp/error.dump.041e274482d24f016c23738a9ff03b9f.log**

i have the same palette

**Comment by miguelcobain** [comment]
@jesustorresor what are using to override the primary, accent or warn variables?

**Comment by Cerealkillerway** [comment]
I'm having this issue using sass lighten:
`$dark-primary: paper-color('deep-purple');`
`$test: lighten($dark-primary, 10%);`

**Comment by guru-kaybus** [comment]
@Cerealkillerway lighten or rgba or other SCSS functions works only with the #color code; any additional character it wont work. Even $dark-primary: #673ab7 !default; will not work.
