### ISSUE TITLE
Cards attributes

### ISSUE THREAD

**Issue by exigez** [miguelcobain/ember-paper#76]
Hi,
I am a novice developer, just starting out with ember, and I have question about you implementation of Cards:
Is there a property that can allow using cards as buttons? I want to be able to select a card in my app, and I'm not sure if this is a trivial thing to do or something that needs to be implemented and hasn't yet.

**Comment by miguelcobain** [comment]
You would need to reopen the paper-card component and implement your click behavior there.
Example:

```javascript
// app/components/paper-card.js
import PaperCardComponent from 'ember-paper/components/paper-card';

export default PaperCardComponent.extend({
  click: function() {
    //this makes this component send out an action to our app if it is clicked
    this.sendAction();
  }
});
```

Then in your template:
```handlebars
{{paper-card action="cardClicked"}}
```

Then the normal ember action process takes place. Learn more about actions: http://guides.emberjs.com/v1.10.0/templates/actions/

I didn't test the code, but I'm pretty sure it works. Let me know if you have any problems. Thanks.
