### ISSUE TITLE
Hide class without any breakpoint should not add display none style.

### ISSUE THREAD

**Issue by grodriguez85** [miguelcobain/ember-paper#764]
I want to hide some div when the screen size is "sm" or smaller. The correct way is by adding the classes "hide show-gt-sm" to the div, but because hide class adds display: none !important this doesn't happen. I don't know if this isn't a bug and is intended or this just happens to me, but on Angular JS Material the classes hide and show-gt-sm together does work as I expect.

**Comment by miguelcobain** [comment]
@grodriguez85 do you happen to be using bootstrap as well? bootstrap has a class of `hide` that clashes with AM styles.

**Comment by grodriguez85** [comment]
@miguelcobain You're absolutely right, that's exactly my problem, thank you!
