### ISSUE TITLE
BUG: Autocomplete executes remote query on focus out

### ISSUE THREAD

**Issue by grodriguez85** [miguelcobain/ember-paper#767]
It must only executes the remote query when searchText changes. This causes me problems when trying to click on the noMatchesMessage as it tries to perform a query and the noMatchesMessage goes away before I can click  on it.

*For the query I'm using ember concurrency addon.

I will save the searchText used in the last query performed to don't execute the query on focus out to solve my issue, but this is still a bug.

**Comment by xomaczar** [comment]
Confirm - will PR a fix soon

**Comment by xomaczar** [comment]
@grodriguez85 latest master resolves this issue - please verify

**Comment by grodriguez85** [comment]
Yes, it's working as expected now, closing this issue.
