### ISSUE TITLE
Paper menu still works with a disabled paper button

### ISSUE THREAD

**Issue by themmer** [miguelcobain/ember-paper#774]
The paper menu still pops up if I disable the paper button that activates the paper menu.

This would be a scenario where I would like to prevent any user interaction on the menu (disable the whole menu). For now I can just disable all menu items as a workaround and give the disabled button aesthetic affordance.

```
{{#paper-menu as |menu|}}
  {{#menu.trigger}}
    {{#paper-button accent=true iconButton=true disabled=isDisabled}}
      {{paper-icon "audiotrack" title="Song Title"}}
    {{/paper-button}}
  {{/menu.trigger}}
  {{#menu.content width=4 as |content|}}
    {{#content.menu-item disabled=isDisabled onClick=(transition-to "search.songs.song" id)}}
      <span>View Song Page</span>
    {{/content.menu-item}}
  {{/menu.content}}
{{/paper-menu}}
```

**Comment by Subtletree** [comment]
You can disable a menu with `{{#paper-menu disabled=true as |menu|}}`.

Looks like it doesn't apply any disabled style though which could be good to add.

I guess in the meantime you could disable both the menu and button

**Comment by hergaiety** [comment]
I know this is a very old post, but I ran into this today. Alas Subtletree's suggestion did not work (and I see no code in Paper Menu suggesting that `disabled=true` is supported.

I was able to write an automated rendering test that would click the **child of** a disabled button, which would open the menu. For us it seems specific to clicking children of the disabled button.

My fix was to conditionally stop propogation depending on the disabled state. Something like...

```hbs
// template
<PaperMenu as |menu|>
  <menu.trigger>
    <PaperButton @disabled={{this.isDisabled}}>
      <span {{on "click" this.handlePropagation}}>Child Element</span>
...
```

```js
// component js
...
@action
handlePropagation(event) {
  if (this.isDisabled) event.stopPropagation();
}
...
```

**Comment by Subtletree** [comment]
> Alas Subtletree's suggestion did not work (and I see no code in Paper Menu suggesting that disabled=true is supported.

Ah looks like `disabled` didn't make it through the octane refactor
https://github.com/miguelcobain/ember-paper/blob/53a61df265f0c448f96052b2f40cc272b8fe85e3/addon/templates/components/paper-menu.hbs#L4

**Comment by miguelcobain** [comment]
I added the argument back. Should be fixed in the next release. Thanks for reporting!

**Comment by miguelcobain** [comment]
Please try `1.0.0-beta.32` and reopen if issue persists.

**Comment by athlyzer-michael** [comment]
The issue comes up again in `1.0.0-beta.35`. The mentioned workaround works fine though.
