### ISSUE TITLE
paper-menu: badly positioned when used in {{liquid-bind}}

### ISSUE THREAD

**Issue by panthony** [miguelcobain/ember-paper#783]
With the following snippet:

```hbs
        {{#liquid-bind "dummy" as |current|}}
          {{#paper-menu as |menu|}}
            {{#menu.trigger onClick=null}}
              {{#paper-button iconButton=true}}
                {{paper-icon "more vert" class="md-menu-origin"}}
              {{/paper-button}}
            {{/menu.trigger}}
            {{#menu.content as |content|}}
              {{#content.menu-item onClick=(action (mut var))}}
                test
              {{/content.menu-item}}
            {{/menu.content}}
          {{/paper-menu}}
        {{/liquid-bind}}
```

When I click on the menu, the menu content will be displayed on the top of the page instead of next to the trigger.

**Edit:**

The culprit is `transform: translateY(0);` on the `.liquid-container` class.

**Comment by proche90210** [comment]
Just wondering did you find any fix this?

**Comment by panthony** [comment]
No I did not, but I didn't really look into it either.

**Comment by Houndsto0th** [comment]
I've also seen this. If you remove the liquid bind the menu functions correctly. It must have something to do with how liquid bind is interacting with base dom elements and how the outlet for the menu gets targeted

**Comment by miguelcobain** [comment]
This was fixed by https://github.com/miguelcobain/ember-paper/commit/d69255597e1c06834aebdc7ccad85d874bfdbb18

Please use master while there's no release.

**Comment by miguelcobain** [comment]
`v1.0.0-beta.4` was published with this fix.

**Comment by panthony** [comment]
@miguelcobain Awesome, and the changelog really helps when bumping the ember paper version 💯
