### ISSUE TITLE
How to hide/show toolbar item like the website does?

### ISSUE THREAD

**Issue by brancoliticus** [miguelcobain/ember-paper#784]
The toolbar on the website shows the menu icon when the browser's width is small, so you can click and see the sidenav, and hides the menu icon when the browser's width is big. And I cannot see a way to reproduce that behaviour for my own project in the documentation.

**Comment by Subtletree** [comment]
It uses the `hide-gt-sm` class which isn't in the docs at the moment. You can see them on the [angular docs](https://material.angularjs.org/latest/layout/options) though.

Also you can see the ember demo app in the dummy folder if you need it. Here's the header: https://github.com/miguelcobain/ember-paper/blob/master/tests/dummy/app/templates/components/page-toolbar.hbs

**Comment by brancoliticus** [comment]
Thanx.
