### ISSUE TITLE
Routable tabs don't highlight the right route if you hard refresh

### ISSUE THREAD

**Issue by xtagon** [miguelcobain/ember-paper#789]
Hi, this isn't really a bug per-se. The solution just isn't in the docs yet, so I wanted to share how I did it.

The problem: If you have tabs for nested routes, then clicking on a tab will highlight it and transition to that route. However, if happen to transition here from somewhere else, the first tab is selected, not the one matching the current route.

The solution is to use `selected` and `value` as such:

```htmlbars
{{#paper-tabs selected=currentRouteName as |tabs|}}
  {{#tabs.tab class="flex" value="foo.nested-one" href=(href-to "foo.nested-one")}}
    Nested One
  {{/tabs.tab}}
  {{#tabs.tab class="flex" value="foo.nested-two" href=(href-to "foo.nested-two")}}
    Nested Two
  {{/tabs.tab}}
  {{#tabs.tab class="flex" value="foo.nested-three" href=(href-to "foo.nested-three")}}
    Nested Three
  {{/tabs.tab}}
{{/paper-tabs}}
```

And here is how I get the current route name in my controller:

```javascript
  applicationController: Ember.inject.controller("application"),
  currentRouteName: Ember.computed.reads("applicationController.currentRouteName"),
```

**Comment by panthony** [comment]
Came up with the same solution except that I'm using this service:

https://github.com/rwjblue/ember-router-service-polyfill

To retrieve the current route name.

**Comment by xtagon** [comment]
Hey thanks @panthony I think I'll do that too!

**Comment by miguelcobain** [comment]
I've been using that myself. Anyone willing to PR this to the docs?
