### ISSUE TITLE
Problem with dropdown position

### ISSUE THREAD

**Issue by Ig0rM** [miguelcobain/ember-paper#801]
According to material design dropdown should opens at central position, but now it always place existing value to the bottom and show only upper values in dropdown.
![29823342-0a153432-8cd7-11e7-97aa-8e5152f323a1](https://user-images.githubusercontent.com/8351575/29823386-2c01dba4-8cd7-11e7-921c-1e941d03f75a.png)

Should be like this 
![29823433-4fa9100e-8cd7-11e7-93c0-fe10757e031a](https://user-images.githubusercontent.com/8351575/29823466-68a58588-8cd7-11e7-901a-5e62258ebca9.png)

**Comment by acgrama** [comment]
Any news regarding this issue?

**Comment by robabby** [comment]
+1 We are experiencing this issue as well.

**Comment by larryh** [comment]
I'm seeing it as well. I'm using 1.0.0-beta.4. 

I have a select containing the 50 states. When I select a state from the first several choices - and keep selecting from the first several choices - all is well. 

It is when I go further down the list that the problem occurs. The first time the several options appear a little above their original position, maybe 1/3rd up the page. The next time they creep up to about 2/3rds up the page. After that they appear nestled against the top of the page.

**Comment by eguana-Florian** [comment]
This issue could be fixed, more or less, by adding following line to paper-select-menu.js, line 102    centeredNode.scrollIntoViewIfNeeded();

**Comment by larryh** [comment]
I tried what you suggested but got a _centeredNode is not a function_ error. Even if it did work, I'm not really comfortable with inserting a local fix into someone else's library code, especially when that code gets updated on a fairly regular basis.

But thank you for taking the time to reply.

**Comment by eguana-Florian** [comment]
Don´t understand how you managed to get that error.... Can you copy your code in here?
I am also not happy with changing code in a npm package locally. But at the moment I don´t have the time to create a fork and a pull request. You are very welcome to do so. ;)

**Comment by larryh** [comment]
Here are lines 94 - 110 of paper-select-menu.js, including the line I pasted into it:

    let focusedNode = centeredNode;
    if ((focusedNode.tagName || '').toUpperCase() === 'MD-OPTGROUP') {
      focusedNode = optionNodes[0] || contentNode.firstElementChild || contentNode;
      centeredNode = focusedNode;
    }

    // Get the selectMenuRect *after* max-width is possibly set above
    containerNode.style.display = 'block';
        centeredNode.scrollIntoViewIfNeeded();
    let selectMenuRect = selectNode.getBoundingClientRect();
    let centeredRect = getOffsetRect(centeredNode);

    if (centeredNode) {
      let centeredStyle = window.getComputedStyle(centeredNode);
      centeredRect.paddingLeft = parseInt(centeredStyle.paddingLeft, 10) || 0;
      centeredRect.paddingRight = parseInt(centeredStyle.paddingRight, 10) || 0;
    }

**Comment by eguana-Florian** [comment]
ok, sorry, my bad. Obviously scrollIntoViewIfNeeded is only supported in Chrome.....
But centeredNode.scrollIntoView() should also work fine

**Comment by larryh** [comment]
NP. And that did work, but I think I will wait until some kind of "official fix" makes its way into the code. I'm not familiar with this type of code, and entering a browser-dependent fix is just something I'm not comfortable with. Also, I am really just starting out (i.e. learning) so I can afford to wait, as I have a zillion other ember things to try to figure out.

Thanks again!

**Comment by panthony** [comment]
Was this issue a duplicate of #773 ? Maybe it can be closed now?

**Comment by larryh** [comment]
Looks to be a duplicate (thanks for pointing that out), and thus it seems like both of them can be closed.
