### ISSUE TITLE
paper-dialog-inner does not get md-content-overflow class unless img element present

### ISSUE THREAD

**Issue by rpkwv8** [miguelcobain/ember-paper#807]
The contentOverflow classBinding is only assigned in the callback of img element load event. If I do not have an img element in my paper-dialog, md-content-overflow class is never assigned and the border styling separating scrollable content from the dialog actions is shown. Link below is to the lines responsible. Angular material determines overflow twice-- once in $$rAF and then again after images are loaded. Ember-paper should do the same.

https://github.com/miguelcobain/ember-paper/blob/69cc168e9ac211a1631aa7a0bbba9a8907945adb/addon/components/paper-dialog-inner.js#L35-L45

**Comment by miguelcobain** [comment]
This should be fixed on master. Thanks. 👍
