### ISSUE TITLE
Select options inside a dialog remain open when closing dialog using the ESC key.

### ISSUE THREAD

**Issue by grodriguez85** [miguelcobain/ember-paper#808]
I have several paper-selects on a paper-dialog. If the ESC key is pressed while having a paper-select options box open, the modal closes but the options box remains open and unclosable cause its select component isn't on the template anymore. Any idea on how to solve this without disabling the ESC key?

**Comment by grodriguez85** [comment]
Meanwhile I solve the issue by closing the dialog on another loop, enabling the select options to close.

`close(){
			Ember.run.next(() => {
				this.set('open', false);
			});
		},`

**Comment by panthony** [comment]
I just encountered this issue with a `paper-select` within a `ember-paper-expansion-panel` which triggers the `collapse` actions when `esc` is pressed.

I think it would be sense for `paper-select` to prevent bubbling of the `esc` key.

https://github.com/miguelcobain/ember-paper/blob/master/addon/components/paper-select-menu-inner.js#L47

**Comment by miguelcobain** [comment]
@panthony maybe we should prevent bubbling of all keyDown events?

**Comment by panthony** [comment]
@miguelcobain I'd say prevent bubbling of `esc` key is a safe bet since this is actually an action handled by the select itself.

For other keys I don't know what it really implies so I'd leave it.

**Comment by schekin** [comment]
Whats can i do to resolve simple trouble with ember-paper-select ??
