### ISSUE TITLE
paper table component / styles?

### ISSUE THREAD

**Issue by gschorkopf** [miguelcobain/ember-paper#814]
Hello there,

First of all, lovely library! I've really enjoyed using it.

I have some data that must be displayed in a table. I see there's an example of a table here http://miguelcobain.github.io/ember-paper/#/typography at the bottom of the page, but I'm having trouble implementing it. 

Does that table have a component? Are there specific classes for a table? What would be an example of how to use a table? I could help you add it to the docs if I had some direction.

Much appreciated.

**Comment by miguelcobain** [comment]
Hi @gschorkopf 

We don't include a table component as it is a complex thing and we want to make sure we get that right.

If you want to use the table in typography, the styles are in the dummy app: https://github.com/miguelcobain/ember-paper/blob/master/tests/dummy/app/styles/demo.scss

look for the table, tr and td styles.

Also, if you need more complex tables, there are a couple of ember-paper addons that implement tables. Check out the addons: http://miguelcobain.github.io/ember-paper/#/addons

**Comment by gschorkopf** [comment]
Thanks for the response!
