### ISSUE TITLE
paper-tabs don't exist in production?

### ISSUE THREAD

**Issue by NullVoxPopuli** [miguelcobain/ember-paper#818]
In development, paper tabs work fine, but in production, I get this error:
![2017-09-18-080402_739x212_scrot](https://user-images.githubusercontent.com/199018/30541130-0e8077fe-9c48-11e7-9aa0-7bd865a85369.png)

super strange

**Comment by NullVoxPopuli** [comment]
this happens in the test environment, too: https://gitlab.com/precognition-llc/aeonvera-ui/-/jobs/33325582

**Comment by NullVoxPopuli** [comment]
So this is probably an issue with the version that's being pulled in the CI env. hmm

**Comment by joukevandermaas** [comment]
This must be something in your build/CI pipeline. It's working fine in our app.

**Comment by miguelcobain** [comment]
CI cache?

**Comment by NullVoxPopuli** [comment]
package.json:
```
    "ember-paper": "^1.0.0-alpha.20",
    "ember-paper-expansion-panel": "^0.0.1",
```

**Comment by NullVoxPopuli** [comment]
yeah, I think it was ci cache. busting the cache by updating my package.json with the latest version (beta3 at the time of writing this) fixed it. :-)
