### ISSUE TITLE
[QUESTION] Custom class for toast service

### ISSUE THREAD

**Issue by erzzo** [miguelcobain/ember-paper#829]
Hi,
I wanted to use the `ToastService` to show different types of messages: success, failed, info.
Therefore I need to add a custom class to every toast to change the text color or background.

Is there a way of implementing it? I've seen the material guidelines and there is a default bg color for that, but...

I'm relatively new to the Ember community, but I think when it's not possible I can write my own service for that.

Thanks for the reply!

**Comment by miguelcobain** [comment]
@erzzo support for this was added now on master through the #820 PR.

**Comment by erzzo** [comment]
@miguelcobain great!
