### ISSUE TITLE
Can someone explain to me where to find documentation on some code in the dummy app?

### ISSUE THREAD

**Issue by brancoliticus** [miguelcobain/ember-paper#831]
There are is-active and href-to in the application.hbs file:

    {{#menu-item active=(is-active "index" currentRouteName) href=(href-to "index")}}Introduction{{/menu-item}}

They seem to be some sort of actions or macros or something but I can't find documentation on the emberjs website or them being defined somewhere in the dummy app.

**Comment by Subtletree** [comment]
`is-active`
https://github.com/miguelcobain/ember-paper/blob/master/tests/dummy/app/helpers/is-active.js

`href-to`
https://github.com/intercom/ember-href-to

**Comment by brancoliticus** [comment]
Thanks for the answer.
