### ISSUE TITLE
Using paper-button as a link to a url

### ISSUE THREAD

**Issue by exigez** [miguelcobain/ember-paper#85]
Hi,
I am a novice and trying to figure out how to do this. As far as I can understand, i should pass the link address as an argument in target (example: target=view). Is this correct?

**Comment by SirZach** [comment]
If you're trying to go to a URL within your app (a transition) I do something like this...
```htmlbars
{{paper-button action="goToRoute"}}
```
And then have the action on the controller or the nearest route handle the action like
```javascript
actions: {
  goToRoute: function () {
    this.transitionTo('<route_name>');
  }
}
```
