### ISSUE TITLE
Paper tabs calculate wrong position for the inkBar on app loading

### ISSUE THREAD

**Issue by gmarquet** [miguelcobain/ember-paper#858]
go to http://miguelcobain.github.io/ember-paper/#/components/tabs (without cache enabled)
and click on the first active tab then the component should update the inkBar to the correct values.

The currentWidth of the _selectedTab seems to be wrong.
I suspect the change in width between before and after the loading of the font.

**Comment by kkgomez2** [comment]
I also have this problem.

**Comment by panthony** [comment]
Duplicate of #858 ?
