### ISSUE TITLE
CSS of Ember Paper not complete implemented?

### ISSUE THREAD

**Issue by GELight** [miguelcobain/ember-paper#859]
Hi,

I searched a possibility to align inline elements like text to "right" etc..... 
In the materialize css there are helper classes available for this. ( http://materializecss.com/helpers.html )
I thought Ember paper is based on materialized design and used all css definitions?

Why Ember have complete own class definitions for all?
It's not possible to use the original css definitions from materialize?

Best regards, 
Mario

**Comment by panthony** [comment]
Hi,

Ember paper is based on the [angular](https://material.angularjs.org/latest/) project, not materialize css.

Looking at the "helpers" part of materialize, it should be pretty straightforward to add them to your project if necessary.

Note that showing/hiding elements [do exists](http://miguelcobain.github.io/ember-paper/#/layout/introduction) in ember paper.

**Comment by GELight** [comment]
Ah.. thanks for the tipp.

Greetings, 
Mario
