### ISSUE TITLE
Glimmer support / hasBlock support

### ISSUE THREAD

**Issue by SirZach** [miguelcobain/ember-paper#86]
After upgrading to ember/canary to get the glimmer engine, paper-buttons no longer show up in the app. I'm not entirely sure why this is breaking.

**Comment by SirZach** [comment]
If you could point me in the right direction I could take a crack at getting a PR going

**Comment by miguelcobain** [comment]
@SirZach, ember-try tests against ember canary. Looks like the tests are passing in ember canary.

What is exactly the problem? What don't the buttons show up?
Please try with the latest `0.1.0` version.

**Comment by SirZach** [comment]
I'll try with 0.1.0 tonight. The text in the buttons were not showing up.

**Comment by miguelcobain** [comment]
How did it go?

**Comment by SirZach** [comment]
I'm seeing that if I use the buttons as block components then the text on the button doesn't show up. If I switch it over to a non-block component and set the text to the label attribute, it'll show up.

**Comment by miguelcobain** [comment]
Nice.

A failing test would be awesome.

**Comment by miguelcobain** [comment]
Looks like the way to go now is using `hasBlock`: http://emberjs.com/api/classes/Ember.Component.html#property_hasBlock

**Comment by SirZach** [comment]
I'll take a crack at spinning up a PR although not sure when you can merge it since I'm not sure when you want to start supporting glimmer...

**Comment by miguelcobain** [comment]
Ideally we should support the same versions that ember-try tests, and that includes Glimmer.
There are things we can do to support both.

**Comment by SirZach** [comment]
So I've been playing around with some tests and whatnot and have found that if I use ember-1.13 or later then using <code>hasBlock</code> is the way to go, otherwise, we need to use <code>template</code>. I can write a computed property in the base component to check for <code>hasBlock</code> first and then fall back to <code>template</code> if that makes sense to you.

**Comment by SirZach** [comment]
currently dealing with a bug where the actual implementation for <code>hasBlock</code> has disappeared. tracking progress at https://github.com/emberjs/ember.js/issues/11301. until that's fixed my PR will have to be on hold

**Comment by SirZach** [comment]
When https://github.com/emberjs/ember.js/pull/11313 is merged in, we'll be able to continue to check for <code>{{#if template}}</code> until you don't want to support pre-Glimmer and then you can make the change to <code>hasBlock</code>.

**Comment by miguelcobain** [comment]
Bingo. :+1:

**Comment by benedikt-d** [comment]
https://github.com/miguelcobain/ember-paper/pull/118

**Comment by miguelcobain** [comment]
Closed via #113.
