### ISSUE TITLE
paper-toast service, multiple toasts

### ISSUE THREAD

**Issue by RedTn** [miguelcobain/ember-paper#866]
When multiple paper-toasts are shown via the service, the toasts simply overlap each other. The material design [spec ](https://material.io/guidelines/components/snackbars-toasts.html#snackbars-toasts-usage)says that if a new toast is to be displayed, the current toast must begin transitioning out before the second should transition in.

It would be great if this could be the default option! Or at least add the option for it to do this.
I'd be glad to work on a PR for this, once I know the maintainers will be willing to merge it.

**Comment by miguelcobain** [comment]
Are you using the paperToaster service?
I remember that they should appear one at a time. You try it in the demo page.
Can you confirm?

**Comment by RedTn** [comment]
Sorry I think I chose the wrong words when I said 'overlap'. I think in this case on the demo site, if a second toast is created before the first toast has expired the first toast should immediately begin a transition out regardless of how much duration it has left.

**Comment by RedTn** [comment]
I think its fair to say that its a bit ambiguous whether the first toast should go down regardless of duration when the second comes up, will close.
