### ISSUE TITLE
paper-progress-circular's stroke-dashoffset is NaN

### ISSUE THREAD

**Issue by BobrImperator** [miguelcobain/ember-paper#878]
![image](https://user-images.githubusercontent.com/15948633/34574627-42dacc86-f178-11e7-99f2-bd2ac3fdb486.png)

Hi, I've encountered (probably a bug) with progress-circular, I pass it a value either string, or number between 1-100, and the problem is that the circle is ALWAYS filled, no matter what, it is filled, and when I inspected it's path element, I saw that stroke is NaN.

So I was meddling with the component inside node_modules, and value is passed to it, and on the line 167 the value itself is already NaN.

```
{{paper-progress-circular diameter=100 value=progress}}
{{minutes-to-hours summarizedDays.worked}} / {{minutes-to-hours summarizedDays.target}}
<br> {{progress}}% {{yield}}
```
progress here is numerical, but I've  been trying to pass it a raw "20" for instance too.
```  
"ember-paper": "^1.0.0-beta.2",
"ember-cli": "^2.16.2",
"ember-data": "2.17.0",

ember is 2.17.0
```
I've checked progress-cilcular on different versions of ember i.e same one that 
http://miguelcobain.github.io/ember-paper/#/addons stands on, and ember paper 1.0.0.-beta.4 and 0.2.5

**Comment by miguelcobain** [comment]
@BobrImperator this seems very weird to me because the section on the docs seems to be working just fine: http://miguelcobain.github.io/ember-paper/#/components/progress-circular
Check the playground section.

Can you provide an ember-twiddle or some example code that I can run and reproduce this issue?

**Comment by BobrImperator** [comment]
I am pretty confused too that on paper's sote everything seems to be ok.
I'll try to do it ASAP but I won't be able to for a while.

**Comment by xomaczar** [comment]
The problem is with initial render when value is set explicitly (and therefore render in determinate mode) and oldValue is undefined. In demo things seem to work because we never set value explicitly and then do initial render.

**Comment by BobrImperator** [comment]
Hello, I'm sorry for so late response.
https://github.com/BobrImperator/demo-paper-progress-circular
Here's my demo showing The Bug.

Thank you for quick responses ;)

**Comment by xomaczar** [comment]
@BobrImperator can you see if #879 fixes your issue

**Comment by xomaczar** [comment]
^ @miguelcobain

**Comment by BobrImperator** [comment]
Yes, it does fix the issue!
![image](https://user-images.githubusercontent.com/15948633/34620818-13bff3ca-f247-11e7-908f-e0aeaae70a50.png)
Thank you!
