### ISSUE TITLE
Redefine actionable elements or create a decorator?

### ISSUE THREAD

**Issue by singhkgautam** [miguelcobain/ember-paper#890]
While working on paper-button I realized that it would have been convenent if I would not have to replace my buttons with paper-button. Why not just provide a decorator for standard button? Something like this
{{#paper-button-decorator}}<button {{action 'doSomething'>Button<button>{{/paper-button-decorator}}

There are following advantage of this approach:
1. It will be easier to implement
2. Will work with route actions without any tweaking. Currently {{#paper-button}} only works with controller action.
3. Migrating to ember-paper would be easier. 
4. Can be used to wrap links as well, though the name would be ambiguous

Any thoughts?

**Comment by miguelcobain** [comment]
You can still use route actions with `{{#paper-button onClick=(route-action "someRouteAction"` with the help of the ember-route-action addon.
Remember you can also links with paper-button using `{{#paper-button href="google.com"`
If you use ember-href-to addon, you can even write `{{#paper-button href=(href-to "some.route" model)`

I think paper-button is flexible enough for most use cases. Your suggestion adds some complications like styling. The button styles target the md-button class. You would have to be aware of that and add it yourself. But then you would also have to implement the warn, primary, accent classes, etc.

If you find a use case paper-button does fit very well, I'll be happy to consider it. Thanks!

**Comment by singhkgautam** [comment]
@miguelcobain thanks for the response. I didn't knew about the route-action so thanks for that.
> Your suggestion adds some complications like styling. 


This is the exact reason why I am suggesting a wrapper. Additional styling can be applied by the wrapper components.

One of the issue with your solution is with some organizations there might be setback in installing a new plugin for things as trivial as this. Also there might be other reasons for using anchor like opening it in new window or for SEO purpose. Let me know if I a getting it wrong?

**Comment by miguelcobain** [comment]
> Also there might be other reasons for using anchor like opening it in new window or for SEO purpose
Maybe you're talking about the `target="_blank"` attribute? paper-button supports that and many other anchor attributes. I may not have been clear, but if you pass in an href to paper-button, it will render a normal `<a` tag, not a `<button` tag.

> This is the exact reason why I am suggesting a wrapper. Additional styling can be applied by the wrapper components.
So, this hypothetical wrapper wouldn't have any styles? What would the wrapper be used for, then?

**Comment by singhkgautam** [comment]
@miguelcobain The anchor part make sense now.
The wrapper may not have style of its own but would apply styling for the warapped element in our case button. 
So when you call it with a button like:
`{{#paper-button-decorator}}<button {{action 'myAction'>MyAction<button>{{/paper-button-decorator}}`
the button with be rendored something like this:

`<button tabindex="0" id="ember380" data-ember-action="" data-ember-action-316="316" class="md-default-theme md-button md-primary md-raised ember-view md-ink-ripple">MyAction<div class="md-ripple-container"></div></button>`

**Comment by miguelcobain** [comment]
It's not trivial to do that. The "decorator" component would have to add classes to the inner element, register events, etc. Just that by itself is a complex issue. And then new questions arise, like "what if we specify multiple elements inside the "decorator"?

It doesn't seem to be a desirable path, especially since you can do pretty much everything with `{{#paper-button` like if it was a `<button`.

**Comment by singhkgautam** [comment]
> It's not trivial to do that. 
Yes I agree. I am heart broken ;) but I can live with it 👍 
Thanks for the explaination I learned something today.

**Comment by miguelcobain** [comment]
No problem. And thanks for bringing in your perspective!
