### ISSUE TITLE
paper-tabs: setting center=true squashes tabs / breaks pagination

### ISSUE THREAD

**Issue by pauln** [miguelcobain/ember-paper#893]
If tabs are rendered with `center=true` on a small screen, they get squashed up to fit within the visible space, preventing pagination from kicking in:
![localhost_4222_ iphone 7](https://user-images.githubusercontent.com/574359/36708614-b42eec98-1bd8-11e8-8ba1-9bdef8f27352.png)

This can be seen by adding `center: true` to the `demo/tabs.js` controller in the dummy app and loading it in a narrow browser (i.e. on a mobile device or using mobile view in dev tools).

I'm guessing that this hasn't been noticed yet because if `center` is toggled after page load (such as by ticking the `center` box in the docs) or you open the page in a larger window and then resize to mobile size, the tabs appear full size and paginated, as expected:
![localhost_4222_ iphone 7 1](https://user-images.githubusercontent.com/574359/36708693-11044aa8-1bd9-11e8-9be4-cb332205472c.png)

**Comment by panthony** [comment]
I think this issue is fixed on master
