### ISSUE TITLE
#paper-button can't see actions defined under route actions

### ISSUE THREAD

**Issue by nedjic** [miguelcobain/ember-paper#897]
#paper-button can't see actions defined under route actions drop error "... Assertion Failed: An action named 'signOut' was not found in (generated login controller)..."

// templates/login.hbs
{{#paper-button onClick=(action "signOut")}}Sign In{{/paper-button}}

// routes/login.js
export default Route.extend({
  session: service(),
  actions: {
    signOut() {
      this.get('session').close();
    }
  }
});

**Comment by panthony** [comment]
You cannot do this. This has nothing to do with `paper-button` but this is how ember works.

If you really want to do something like this you can use this addon:

https://github.com/DockYard/ember-route-action-helper

But this is discouraged as stated in their README. I let you read why

**Comment by nedjic** [comment]
Thanks for your answer. But can you help me understand because it's working when I use regular HTML button? Thanks.
// templates/login.hbs
<button {{action "signOut"}}>Sign Out</button>

**Comment by nedjic** [comment]
I found the answer to my question. Thanks again.
