### ISSUE TITLE
New bind-attr deprecation warning

### ISSUE THREAD

**Issue by razor-x** [miguelcobain/ember-paper#90]
After running `ember server`:

```
DEPRECATION: The `bind-attr` helper ('paper-app/templates/components/paper-button.hbs' @ L1:C8) is deprecated in favor of HTMLBars-style bound attributes.
```

```
Ember Inspector
1.8.0

Ember
1.13.0-beta.2

Ember Data
1.0.0-beta.18

Firebase
2.2.5

EmberFire
1.4.5

jQuery
2.1.4

PaperApp
0.0.0.7b799f9e
```

**Comment by razor-x** [comment]
Additional note: using ember-cli 0.2.5, so maybe this should be handled as part of or after an overall upgrade. Is anyone working on that? Otherwise I can start a new branch and work on merging the changes from `ember upgrade`.

**Comment by miguelcobain** [comment]
You're using Ember `1.13.0-beta.2`. Props for that!

We need to target multiple versions of ember. Can we use HTMLBars-style bound attributes without breaking anything?

**Comment by razor-x** [comment]
I'm just starting with Ember, and with all of the big changes coming in 2.0 I figured I might as well start with 1.13. I expect the transition period to be a bit rocky so I'll try to contribute back where I can.

I'm not sure about what ember versions would break by addressing this deprecation. As I understand it, the Ember roadmap plans to support 1.13 for a while as addons work to fully support 2.0. If there are more issues like this along the road to 2.0, maybe a parallel approach is needed? Say a 1.0.0 branch to target the Ember 2.0 release.

**Comment by matheusdavidson** [comment]
I'm interested to help in this project. I was looking some of the last issues and some are about ember 2.0 features, so i think @razor-x has a point about the new branch for 2.0 so we can start using nice features like pods, glimmer and all HTMLBars goodies.

**Comment by miguelcobain** [comment]
@matheusdavidson We can start using Ember 2.0 features now. Having a separate branch would mean to throw away all the hard work Ember core team did for us.
Ember took a well though path to move to Ember 2.0. Everything (almost?) is backwards compatible. Even HTMLBars and Glimmer. We don't need to be afraid to keep working with latest Ember version. :)

You mentioned pods. Pods are out of the scope of this addon. You can use pods in your app. Pods in addons is something being worked out in ember-cli.
Regarding Glimmer, we should support it right away!

**Comment by SirZach** [comment]
@miguelcobain Do you think releasing a 1.0.0 version of this as official support for Ember 2.0?

**Comment by miguelcobain** [comment]
As of #100, we should release a 2.0.0 version, right?

**Comment by SirZach** [comment]
Even so fas a 2.0.0.beta. I can help create a PR to get things moving in
that direction

**Comment by miguelcobain** [comment]
PRs are welcome, as always. :D
We should however outline its goals before, so we can avoid unnecessary work and keep the focus from the beginning.

**Comment by miguelcobain** [comment]
bind-attr and other deprecations are solved.

**Comment by akashdsouza** [comment]
Ok I have a link tag that has a bind-attr to the href attribute. The attribute points to a link returned from a function in the application's controller. How is the deprecation applied here.

**Comment by miguelcobain** [comment]
@akashdsouza `bind-attr` is deprecated, you shouldn't use it.

**Comment by akashdsouza** [comment]
@miguelcobain I understand that. That's why I'm asking how to do the same without bind-attr .

**Comment by miguelcobain** [comment]
```hbs
<a href={{yourValue}}>A Link</a>
```

Please read: http://guides.emberjs.com/v1.12.0/templates/binding-element-attributes/
