### ISSUE TITLE
ember-cli-babel 5.x has been deprecated

### ISSUE THREAD

**Issue by beastmst** [miguelcobain/ember-paper#909]
ember-cli-babel 5.x has been deprecated

when do a 
ember install ember-paper 

in a new project, few lines of this warning come out, because of the 

ember-paper -> ember-composability-tools -> ember-cli-babel
ember-paper -> ember-composability-tools -> ember-wormhole -> ember-cli-babel
ember-paper -> ember-css-transitions -> ember-cli-babel
ember-paper -> virtual-each -> ember-cli-babel

**Comment by bjornharrtell** [comment]
Fixed with merge of https://github.com/miguelcobain/ember-paper/pull/916.
