### ISSUE TITLE
paper-input required=true fails on Ember 3.1

### ISSUE THREAD

**Issue by BryanHunt** [miguelcobain/ember-paper#910]
Create a new app with Ember 3.1 and add the following:

`{{paper-input label="Name" value=name required=true onChange=(action (mut name))}}`

When you enter text into the input and that input looses focus, it will go into the error state and say "This is required."

**Comment by wahhaj** [comment]
I had a similar issue. I tracked down the problem and created a PR (#911) that fixes it.

**Comment by miguelcobain** [comment]
Closed by #911
