### ISSUE TITLE
Release Ember 3.1-compatible beta

### ISSUE THREAD

**Issue by goroskob** [miguelcobain/ember-paper#913]
Ember 3.1 was released recently, but v1.0.0-beta.4  does not play well with it ([for instance](https://github.com/miguelcobain/ember-paper/issues/910)).
Could beta 5 be published to npm so that we could upgrade Ember without breaking too much?

**Comment by bjornharrtell** [comment]
@goroskob is this resolved by https://github.com/miguelcobain/ember-paper/releases/tag/v1.0.0-beta.5?

**Comment by goroskob** [comment]
@bjornharrtell not yet, there is still issue #921 which also reproduces in 1.0.0-beta.5 for me. It is not reproducing on a master branch however.
There is also still a deprecation warning about ember-cli-babel because of outdated virtual-each.

**Comment by miguelcobain** [comment]
Should be working on 1.0.0-beta.6. Please reopen if that isn't the case.
Keep in mind that beta.6 is only compatible with Ember > 2.10
