### ISSUE TITLE
Paper-Input: set placeholder and label at the same time

### ISSUE THREAD

**Issue by adiehl96** [miguelcobain/ember-paper#917]
Hey,
when I set placeholder and label each with a string, I see them both over each other instead of just the label:
![schermafbeelding 2018-05-02 om 18 15 59](https://user-images.githubusercontent.com/25660042/39535743-014fb848-4e35-11e8-9fa0-e3e1cff8a08d.png)
I expected the behavior to be something like described here, where apparently the placeholder is hidden until the label floats above the input field:
[Angular/Material2/input](https://github.com/angular/material2/blob/master/src/lib/input/input.md#placeholder)
I'm calling the component like so:
```javascript
{{paper-input class="flex-30" label="Name" placeholder="Address" value=object.text onChange=(action (mut object.text))}}
```
Is this something that will be supported or am I doing something wrong here?

**Comment by miguelcobain** [comment]
@adiehl96 we don't support both a label and a placeholder simultaneously at the moment.

**Comment by adiehl96** [comment]
Alright, good to know, I'll use your suggestion then.

**Comment by xomaczar** [comment]
Can we fix it so others can benefit from? Any known blockers?

**Comment by xomaczar** [comment]
@miguelcobain it’s lways stylesheet :), are you open to extending/overwriting them?

**Comment by miguelcobain** [comment]
If there's a compelling case for that, then yes. Is the label+placeholder part of the spec?
Also, if the overrides are relatively small, then I don't see a problem.
