### ISSUE TITLE
1.0.0-beta.5 broke paper-menu 

### ISSUE THREAD

**Issue by hoboman313** [miguelcobain/ember-paper#921]
I'm on Ember 3.1.2. paper-menu worked perfectly for me in beta 4. 
Now I see a:

> ember-wormhole.js:102 Uncaught Error: ember-wormhole failed to render content because the destinationElementId was set to an undefined or falsy value.
    at Class._appendToDestination (ember-wormhole.js:102)
    at ember-wormhole.js:68
    at invoke (backburner.js:205)
    at Queue.flush (backburner.js:125)
    at DeferredActionQueues.flush (backburner.js:278)
    at Backburner.end (backburner.js:410)
    at Backburner._boundAutorunEnd (backburner.js:372)
_appendToDestination @ ember-wormhole.js:102
(anonymous) @ ember-wormhole.js:68
invoke @ backburner.js:205
flush @ backburner.js:125
flush @ backburner.js:278
end @ backburner.js:410
Backburner._boundAutorunEnd @ backburner.js:372
setTimeout (async)
Backburner.platform.next @ backburner.js:360
_ensureInstance @ backburner.js:884
ensureInstance @ backburner.js:731
ensureRunloop @ ember-metal.js:1134
markObjectAsDirty @ ember-metal.js:1123
notifyPropertyChange @ ember-metal.js:1556
set @ ember-metal.js:3577
updateState @ basic-dropdown.js:251
open @ basic-dropdown.js:130
toggle @ basic-dropdown.js:162
handleMouseDown @ trigger.js:122
send @ action_support.js:128
superWrapper @ ember-utils.js:428
(anonymous) @ trigger.js:223

**Comment by goroskob** [comment]
I faced the same issue on Ember 3.1.2 with beta 4 also, so i don't think beta 5 broke it. Also it's already working on a master branch.

**Comment by kltdwrds** [comment]
sharing my experience on `ember 3.1.2`:

`1.0.0-beta.4`:
 - all components worked as expected in dev / prod 
 - in acceptance tests i've only experienced issues with the paper-dialog component (https://github.com/miguelcobain/ember-paper/issues/630)

`1.0.0-beta.5`
 - i see the error mentioned above

**Comment by miguelcobain** [comment]
Should be working on `1.0.0-beta.6`. Please reopen if that isn't the case.
Keep in mind that beta.6 is only compatible with Ember > 2.10

**Comment by kltdwrds** [comment]
Can confirm, `1.0.0-beta.6` fixes the issues described above for all environments 👍
