### ISSUE TITLE
Error paper-chips autocomplete with version 1.0.0-beta.7 and ember 3

### ISSUE THREAD

**Issue by filianer** [miguelcobain/ember-paper#926]
"Assertion Failed: You attempted to access `defaultAttrs.positionIndex` (on `<(unknown mixin):ember1386>`), but `defaultAttrs` is a computed property.↵↵Due to certain internal implementation details of Ember, the `defaultAttrs` property previously contained a private "descriptor" object, therefore `defaultAttrs.positionIndex` would have been `undefined`.↵↵This implementation detail has now changed and the "descriptor" object is no longer present at this location. Soon, accessing `defaultAttrs` on this object will return the computed property's current value (see RFC #281 for more details).↵↵If you are seeing this error, you are likely using an addon that relies on this now-defunct private implementation detail. If you can, identify the addon from the stack trace below and report this bug to the addon authors. If you feel stuck, the Ember Community Slack (https://ember-community-slackin.herokuapp.com/) may be able to offer some help.↵↵If you are an addon author and need help transitioning your code, please get in touch in the #dev-ember channel in the Ember Community Slack.

**Comment by youalreadydid** [comment]
Happens when I interact with paper-autocomplete, any interaction (hover/click), with and without search. Besides that, the value is selected, but the menu keeps open.

I'm using ember 3.1.4 and version 1.0.0-beta.7

**Comment by chris-aeviator** [comment]
I'm experiencing the same issue with ember 3 and "paper-autocomplete" it completely makes autocomplete unusable

more output:

```
TypeError: items.slice(...).map is not a function
[Learn More]
paper-virtual-repeat.js:211
Error: Assertion Failed: You must use set() to set the `hasMoved` property (of <icm-webapp@component:paper-autocomplete-content::ember554>) to `false`.
error.js:40
```

**Comment by BobrImperator** [comment]
I've actually submitted a PR for dependency of ``virtual-repeat`` that is, ``virtual-each`` regarding the same problem.
https://github.com/jasonmit/virtual-each/pull/124
