### ISSUE TITLE
paper-progress-circular error while in fastboot

### ISSUE THREAD

**Issue by betocantu93** [miguelcobain/ember-paper#927]
Just discovered that this line makes fastboot fail, the easiest way around this is just use the fastboot service for conditional rendering in the template, but I don't know if the component itself should tackle this.

https://github.com/miguelcobain/ember-paper/blob/a45979e6d68b0530cb6eecbe02ad94f4546a8e9a/addon/components/paper-progress-circular.js#L175

**Comment by betocantu93** [comment]
This is what I did, and should work
``` 
//component.js
 fastboot: service()

//template.hbs
{{#unless fastboot.isFastBoot}}
  {{paper-progress-circular accent=true diameter=40}}
{{//unless}}

```

**Comment by miguelcobain** [comment]
@betocantu93 @marcgiovannoni can any of you test if using the master branch solves this issue?
It should.

**Comment by betocantu93** [comment]
Sorry @miguelcobain forgot the feedback, I tried to replicate my problem and it seems its working with master, thanks...!

**Comment by betocantu93** [comment]
By the way, how do you get the Fastboot global? it's convenient

**Comment by miguelcobain** [comment]
@betocantu93 It's just defined on Fastboot environments!
