### ISSUE TITLE
paper-tooltip: annoying display issue when used on inlined component

### ISSUE THREAD

**Issue by panthony** [miguelcobain/ember-paper#931]
There is a quite annoying issue with paper-tooltip/ember when you are using it on an inline component.

Because of how ember work by default (spawning a `<div id="emberXXX"></div>`), when you use ember tooltip like so:

```hbs
<span>
{{#paper-button}}
   {{yield}}
{{/paper-button}}

{{#paper-tooltip}}
   {{tooltip}}
{{/paper-tooltip}}
</span>
``` 

And you hover the component, then the DOM will look like this:

```html
<span>
  <button></button>
  <div id="emberXXXX"></div>
</span>
```

And the `<div>` will fucked up the layout.

I had to override the `paper-tooltip` component to add a css class on it and the following css:

```scss
.paper-tooltip {
  > * {
    display: none;
  }
}
```

This way I'm sure that the added empty (because the content is actually rendered in the wormhole) `div` added by ember does not impact the layout.

Do you think there is something worth fixing directly in ember-paper?

**Comment by xomaczar** [comment]
It uses native -in-element helper instead of wormwhole, the tagName=‘’, it shouldn’t generate any dom in place - which version are you on?

**Comment by panthony** [comment]
@xomaczar `beta.4`, it's true that I'm lagging a little behind. I see that `-in-element` was introduced later so upgrading paper will probably fix this issue.

Can't do it right know though as I'm not sure what kind of regressions I could expect from all the updates there was.

Closing this issue, thanks 👍
