### ISSUE TITLE
paper-autocomplete: item not selected when using keyboard (requires two attempts)

### ISSUE THREAD

**Issue by pauln** [miguelcobain/ember-paper#935]
Pressing `enter` with a suggestion highlighted does not select the item, although it does set the searchText to the item's full text and close the dropdown.  This is confusing, as it looks as though the item was selected - but in reality, no item was selected.  If you then backspace a letter, highlight the item again and press `enter` a second time, the item is selected.  The same seems to hold true when using `tab` rather than `enter`.

Watch the "Nothing is selected" / "Selected country is..." text below the autocomplete in the following recording:
![recording](https://user-images.githubusercontent.com/574359/40639260-1f6d0a08-6364-11e8-8ea1-408c5bba9ea4.gif)

**Comment by xomaczar** [comment]
@pauln can you verify if this has been resolved

**Comment by pauln** [comment]
This does indeed appear to have been resolved by #956 - thanks again for your work on that!
