### ISSUE TITLE
paper-select: typing on keyboard trigger bunch of errors

### ISSUE THREAD

**Issue by panthony** [miguelcobain/ember-paper#937]
On the `master` branch and `1.0.0-beta.4`, when I open a paper-select and start typing on the keyboard I have a bunch of errors in the console such as:

```
Assertion Failed: {{power-select}} If you want the default filtering to work on options that are not plain strings, you need to provide `searchField`
```

- I do not pass `searchEnabled` or anything related. The defaults is supposed to be false.
- I can't reproduce on live documentation (probably because options are always an array of string)

**Comment by panthony** [comment]
You can obviously "fix" the issue by passing `searchField="whatever"` since `searchEnabled` is false but it shouldn't be required

**Comment by backspace** [comment]
[This comment](https://github.com/cibernox/ember-power-select/issues/1040#issuecomment-465579400) on Ember Power Select suggests that `searchField` is mandatory even if `!searchEnabled` 😯

**Comment by panthony** [comment]
Makes sense, thanks for bringing that up. Closing this issue.
