### ISSUE TITLE
paper-switch: how to interact within an application test

### ISSUE THREAD

**Issue by gmurphey** [miguelcobain/ember-paper#942]
I tried to fire the `onChange` action using the `click` and `tap` helpers from `ember-test-helpers`, but neither worked. I'd be happy to write documentation or a test helper for this if someone can point me in the right direction.

**Comment by panthony** [comment]
@gmurphey I'm using keypress:

```js
import { render, triggerKeyEvent } from '@ember/test-helpers';

module('Integration | Component | crazy-toggler', function(hooks) {
  setupRenderingTest(hooks);

  test('it toggles', async function(assert) {

    await render(hbs`{{crazy-toggler}}`);

    await triggerKeyEvent('md-switch', 'keypress', 13 /* Enter */);

  });
});
```

Can't make it work using `click` helper, maybe it also needs focus-related events (https://github.com/miguelcobain/ember-paper/blob/master/tests/integration/components/paper-switch-test.js#L43)
