### ISSUE TITLE
Autoprefixer's process() method is deprecated

### ISSUE THREAD

**Issue by benedikt-d** [miguelcobain/ember-paper#96]
Autoprefixer's process() method is deprecated and will removed in next major release. Use postcss([autoprefixer]).process() instead

I think autoprefix needs to be updated

**Comment by miguelcobain** [comment]
It is fixed on master. Need to release a new version.

Meanwhile you can use master using `"ember-paper": "miguelcobain/ember-paper"` in your `package.json`.

**Comment by miguelcobain** [comment]
`0.1.1` was published.
