### ISSUE TITLE
paper-select-dropdown persists when dialog is closed

### ISSUE THREAD

**Issue by BobrImperator** [miguelcobain/ember-paper#967]
##   STEPS
  - Open the dialog
  - click on the category field to open drop down
  - hit ESCAPE
  - the dropdown HTML should persist
  - the components are destroyed (judging based on what ember-inspector shows)

## The heroku app
https://morning-headland-34714.herokuapp.com/

## Repo
https://github.com/BobrImperator/dropdown-not-closing-on-escape

**Comment by miguelcobain** [comment]
@BobrImperator Thanks a lot for the detailed reproduction. This will make it a lot easier to solve the problem.

**Comment by schekin** [comment]
How to fix this error?

**Comment by panthony** [comment]
@miguelcobain @BobrImperator I think this is a duplicate of #808

**Comment by ctwoolsey** [comment]
Additionally, I've created a dialog within a parent and if I click outside of the dropdown, the dropdown does not automatically close.
