### ISSUE TITLE
Theming?

### ISSUE THREAD

**Issue by admarrs** [miguelcobain/ember-paper#97]
Great to see a native ember approach to MD. At the moment I'm still trying to understand some of the nuances (e.g. the undocumented flex layout) and have a question regarding theming.

Angular Material will let you set the theme for `<md-content>` for example based on the Input demo example you can declare `<md-theme md-theme="docs-dark">` to change the theme to a dark theme. Is it possible to do this in ember-paper?

**Comment by miguelcobain** [comment]
The only way right now is to define your own themes in sass.
You can take a look at the sass stylesheets (`variables.scss`) and override any variable you need.

Example: 

```scss
//change primary color palette
$primary-color-palette: $color-indigo;
@import "ember-paper";
```

This should work.
Regarding the undocumented flex grid, it would be great to have such documentation.

**Comment by matheusdavidson** [comment]
You can have a look here for flex grid used in this project:
https://material.angularjs.org/latest/#/layout/container

**Comment by nucleartide** [comment]
For people coming from google: as of ember-paper v0.2.10, you should override the variables in `default-theme.scss`. For example, this sets the primary color to orange:

```scss
$primary: "orange";
@import "ember-paper";
```

**Comment by jeffdill2** [comment]
@nucleartide how do you define one of the color subsets from the `color-palette` file as the `$primary` color? For instance, the `700` type of the `$color-cyan` color?

**Comment by nabihahossain** [comment]
@jeffdill2 @nucleartide @miguelcobain did anyone figure out how to select a hue of a color as a primary color?

**Comment by AMS777** [comment]
For the 2 last questions, on your theme, initialize **$default-color**. Steps:

Copy **node_modules/ember-paper/app/styles/default-theme.scss** on **app/styles/** and rename it:

**app/styles/_example-theme.scss**
```
$theme-name: "default" !default;

$primary: "indigo" !default;
$accent: "pink" !default;
$warn: "red" !default;
$link: "light-blue" !default;

$dark: false !default;

$foreground: "foreground-dark" !default;
$background: "background-light" !default;

$base-color: rgba(0, 0, 0, 0.87) !default;
```

Add **$default-color** below **$base-color** and remove **!default** (and you may replace double quotes with single quotes):

**app/styles/_example-theme.scss**
```
$theme-name: 'example';

$primary: 'blue-grey';
$accent: 'grey';
$warn: 'red';
$link: 'light-blue';

$dark: true;

$foreground: 'foreground-dark';
$background: 'background-light';

$base-color: rgba(0, 0, 0, 0.87);
$default-color: '800';
```

Import your theme on **app.scss**:

**app/styles/app.scss**
```
@import "example-theme";

@import "ember-paper";
@import "ember-paper-link";
```

You can also check **node_modules/ember-paper/app/styles/color-palette.scss** to understand better how ember-paper works.

What I don't figure out yet is what **$dark** variable is for. I guess is just a control variable to use on our own css, and it's not used for ember-paper.
