### ISSUE TITLE
paper-menu bugged in Firefox

### ISSUE THREAD

**Issue by HenryVonfire** [miguelcobain/ember-paper#970]
In firefox 61.0.2, scrolling with a `paper-menu` opened, makes it to get stuck to the right border of the screen. It can be tested with the demo page but here is a screenshot:

![ember-paper-bug](https://user-images.githubusercontent.com/10612765/44137284-2096245c-a070-11e8-82ca-1b3bf972e43f.png)

**Comment by firstsano** [comment]
+1, having same issue in chrome

**Comment by patodevilla** [comment]
#939 maybe this can help you as a temporary fix

**Comment by miguelcobain** [comment]
Shouldn't happen anymore since ember-basic-dropdown was updated some time ago.
Make sure that, if you're using ebd in your app, that it is the same version that ember-paper uses.
Please reopen if issue still persists.
