### ISSUE TITLE
`send-action` deprication

### ISSUE THREAD

**Issue by ike** [miguelcobain/ember-paper#989]
I am getting quite a few of these warnings. Is there an existing plan to support the Ember 3.4 [changes to `send-action`](https://deprecations-app-prod.herokuapp.com/deprecations/v3.x/#toc_ember-component-send-action)?

```
DEPRECATION: Please refactor `{{input focus-out="inputBlur"}}` to `{{input focus-out=(action "inputBlur")}}. ('ember-paper/templates/components/paper-chips.hbs' @ L53:C8)  [deprecation id: ember-component.send-action] See https://emberjs.com/deprecations/v3.x#toc_ember-component-send-action for more details.
```

**Comment by Subtletree** [comment]
This should be fixed from ember-paper 1.0.0-beta.11 😃
