### ISSUE TITLE
#Canary breaks module importing

### ISSUE THREAD

**Issue by brianmbutler** [miguelcobain/ember-paper#99]
Looks like the pod bug may be back.   Ember-paper works great in fresh install on 1.12.1, but ember#canary results in this error:

    Uncaught Error: Could not find module `ember-paper/components/paper-toolbar` imported from `my-    app/components/paper-toolbar`

**Comment by miguelcobain** [comment]
@brianmbutler Unit tests are passing with ember-canary with the latest version `0.1.2`.

Can you try it again and report if the problem persists, please?

**Comment by miguelcobain** [comment]
@brianmbutler ping?

**Comment by brianmbutler** [comment]
Seems to be fixed.
